### ISSUE TITLE
增加类似于Clash Verge Rev的测试功能

### ISSUE THREAD

**Issue by huoyan1231** [LibNyanpasu/clash-nyanpasu#1007]
### 需求 / Requirement

对特定网站的延迟ping

### 建议实现 / Suggested implements

通过代理对特定ip进行延迟和访问测试

### 备注 / Addition details

已在dddeed5版本查看并未发现此功能

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### 是否为 Pre-release / Is pre-release version

dddeed5

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by Yamooya** [comment]
觉得这个功能用处不大，目前已经有网站提供了更加丰富的功能。

**Comment by huoyan1231** [comment]
> 觉得这个功能用处不大，目前已经有网站提供了更加丰富的功能。

不了解 能否提供一下网站链接？

**Comment by Yamooya** [comment]
> > 觉得这个功能用处不大，目前已经有网站提供了更加丰富的功能。
> 
> 不了解 能否提供一下网站链接？

**Comment by Yamooya** [comment]
> > 觉得这个功能用处不大，目前已经有网站提供了更加丰富的功能。
> 
> 不了解 能否提供一下网站链接？

https://ip.skk.moe/
https://ipcheck.ing/

**Comment by huoyan1231** [comment]
> 你的意思是，使用特定的链接进行延迟测试吗

是的

**Comment by keiko233** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/commit/b572c8cfe5da52874818d91e6fc5741f6f039704
https://github.com/LibNyanpasu/clash-nyanpasu/commit/d6d45050349e082976c1a96bb2a3be9cef9f9f0b
