### ISSUE TITLE
希望增加日志清理功能(.config\clash-nyanpasu\storage文件夹相关)

### ISSUE THREAD

**Issue by 68star89** [LibNyanpasu/clash-nyanpasu#1014]
### 需求 / Requirement

近日清理C盘时，发现.config\clash-nyanpasu\storage文件夹堆积了900mb+的文件，且多为.log格式，想了解该类文件是否可以安全删除而不影响应用实际功能的实现

### 建议实现 / Suggested implements

由于storage文件夹实际上并不只有log文件，因此为防止误删，如果能提供一个一键清理缓存的选项那就再好不过了

### 备注 / Addition details

无

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### 是否为 Pre-release / Is pre-release version

否

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [ ] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
可以直接删除，这是rocksdb的缓存数据，nyanpasu在1.6.0将直接废弃这个文件夹，届时升级自动删除。

如果现在你觉得体积过大的话，可以在app非运行期自行删除解决

**Comment by 68star89** [comment]
了解了，感谢
