### ISSUE TITLE
不退出应用直接关机，开机后还是能代理

### ISSUE THREAD

**Issue by krkrchan** [LibNyanpasu/clash-nyanpasu#1031]
### 复现步骤 / Step to reproduce

Tun模式、服务模式，开启。
系统代理、开机自启、静默启动，关闭。

1、启动clash后，电脑能访问外网。
2、不手动退出clash，直接将电脑关机。
3、下次需要使用电脑时，开机。

### 预期行为 / Expected behaviour

开机后clash不会自动启动（因为【开机自启】未开启），这时电脑应该无法访问外网。

### 实际行为 / Actual Behaviour

使用浏览器访问外网如Google、YouTube，均能正常访问。
这时点击clash图标启动，会发现代理tab是空白的，似乎没有正常启动。
退出clash应用。这时电脑就不能访问外网了。
重新打开clash，代理tab出现代理组内容了，且能访问外网了。

### Clash Nyanpasu 版本号 / Clash Nyanpasu

v1.5.1

### Clash 核心及其版本号 / Clash core and version

v1.18.3 Meta

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windows 11 专业版 22635.3720

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
已在 dev builds中修复
