### ISSUE TITLE
不退出应用直接关机，开机后无法启动tun模式

### ISSUE THREAD

**Issue by Minonyah** [LibNyanpasu/clash-nyanpasu#1052]
### 复现步骤 / Step to reproduce

Tun模式、服务模式，开机自启，开启。
系统代理、静默启动，关闭。

1、启动clashTun模式后，电脑能访问外网。
2、不手动退出clash，直接将电脑关机。
3、下次需要使用电脑时，开机。
4、clash自动启动，显示Tun模式已开启，实际无虚拟网卡存在，无法访问外网，不影响国内网站

### 预期行为 / Expected behaviour

它应该自动启动并启动tun模式

### 实际行为 / Actual Behaviour

在复现步骤描述的前提下，无论重启clash应用，开关TUN模式，开关服务模式，重新安装服务模式，在已关闭的情况下开关机，在未关闭的情况下开关机，均无法重新启用TUN模式
开启代理模式则正常代理
只有卸载clash重新安装可以正常启用TUN模式

### 备注 / Addition details

此问题在最近一周的Pre-release 版本中均存在，在[v1.5.1]中也存在

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.2-alpha+c7f7daa

### Clash 核心及其版本号 / Clash core and version

mihomo v1.18.5

### 是否为 Pre-release / Is pre-release version

c7f7daa

### 操作系统及版本 / OS version

windows 10 专业版 22H2 19045.4412

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
clash tun需要管理员权限才能使用，所以有一个服务模式，如果想不用管理员的话需要启用一下，否则自启动的权限进程权限不足会导致网卡创建失败

**Comment by Minonyah** [comment]
> clash tun需要管理员权限才能使用，正常情况下必须有UAC授权才能正常开启，所以有一个服务模式，如果想不用管理员的话需要启用一下，否则自启动的权限进程权限不足会导致网卡创建失败

![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/169628824/c3598bd4-0d16-44a0-8a1e-25d54ac3e65a)
如果是这个的话是启用的

**Comment by keiko233** [comment]
> > clash tun需要管理员权限才能使用，正常情况下必须有UAC授权才能正常开启，所以有一个服务模式，如果想不用管理员的话需要启用一下，否则自启动的权限进程权限不足会导致网卡创建失败
> 
> ![image](https://private-user-images.githubusercontent.com/169628824/339302926-c3598bd4-0d16-44a0-8a1e-25d54ac3e65a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzEyMzksIm5iZiI6MTcxODI3MDkzOSwicGF0aCI6Ii8xNjk2Mjg4MjQvMzM5MzAyOTI2LWMzNTk4YmQ0LTBkMTYtNDRhMC04YTFlLTI1ZDU0YWMzZTY1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwOTI4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTc5ZjIwOWNmZDY5M2JkODA5MmU4MzQ2OTM3MGUxMGIyMzZmM2M0YTU5MzU1NzNkZmIxZDYzNDJiM2RiMjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zw5rVWJIYaCYRnQ1pO-a-0XsLiwqywNNgNZ4ylbOs5M) 如果是这个的话是启用的

那可能有点奇怪了，我这边没有遇到，需要提供一下最小的复现日志供排查使用

**Comment by Minonyah** [comment]
> > > clash tun需要管理员权限才能使用，正常情况下必须有UAC授权才能正常开启，所以有一个服务模式，如果想不用管理员的话需要启用一下，否则自启动的权限进程权限不足会导致网卡创建失败
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/169628824/339302926-c3598bd4-0d16-44a0-8a1e-25d54ac3e65a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgyNzEyMzksIm5iZiI6MTcxODI3MDkzOSwicGF0aCI6Ii8xNjk2Mjg4MjQvMzM5MzAyOTI2LWMzNTk4YmQ0LTBkMTYtNDRhMC04YTFlLTI1ZDU0YWMzZTY1YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYxM1QwOTI4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTc5ZjIwOWNmZDY5M2JkODA5MmU4MzQ2OTM3MGUxMGIyMzZmM2M0YTU5MzU1NzNkZmIxZDYzNDJiM2RiMjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Zw5rVWJIYaCYRnQ1pO-a-0XsLiwqywNNgNZ4ylbOs5M) 如果是这个的话是启用的
> 
> 那可能有点奇怪了，我这边没有遇到，需要提供一下最小的复现日志供排查使用

现在问题修改为服务模式无法正常启动（

**Comment by Minonyah** [comment]
管理员模式与非管理员模式均尝试：安装服务模式 -> installed-> 启动服务模式 -> 显示已启动-> 打开代理页面-> 回到设置页面-> 服务模式显示未启动

**Comment by keiko233** [comment]
> 管理员模式与非管理员模式均尝试：安装服务模式 -> installed-> 启动服务模式 -> 显示已启动-> 打开代理页面-> 回到设置页面-> 服务模式显示未启动

服务模式开关的问题应该修好了，可以下载最新pre release试试
