### ISSUE TITLE
切换Clash内核提示：Switching failed, please check log and modifyour profile file.

### ISSUE THREAD

**Issue by yinyuncan** [LibNyanpasu/clash-nyanpasu#1056]
### 复现步骤 / Step to reproduce

问题1
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/56066641/253b4450-e227-473c-bbaf-c63681cc5a0c)
问题2
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/56066641/bb242f2f-d2b5-4354-82d6-64d39fb0572a)

### 预期行为 / Expected behaviour

切换到Clash rust 后核心不能再次切换为Minhomo回来，应该要能正确切换核心

### 实际行为 / Actual Behaviour

问题1：切换Clash内核提示：Switching failed, please check log and modifyour profile file.
问题2：切换到Clash rust代理组为空，似乎是不兼容

### Clash Nyanpasu 版本号 / Clash Nyanpasu

v1.5.2

### Clash 核心及其版本号 / Clash core and version

Clash rust

### 是否为 Pre-release / Is pre-release version

c34a235

### 操作系统及版本 / OS version

windows10

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by cubizio** [comment]
我也遇到上面一样的问题，内核选错后，无法切换回来，

**Comment by greenhat616** [comment]
目前最新的夜间版本应该能够正确的报告切换内核的错误信息了。
