### ISSUE TITLE
“连接”一栏始终为空，速度始终为零

### ISSUE THREAD

**Issue by intzaaa** [libnyanpasu/clash-nyanpasu#1058]
### 复现步骤 / Step to reproduce

https://github.com/LibNyanpasu/clash-nyanpasu/assets/64564727/cb373b2b-a824-4bf5-8a8a-81db968d5985

### 预期行为 / Expected behaviour

应该会显示很多很多连接

### 实际行为 / Actual Behaviour

同上

https://github.com/LibNyanpasu/clash-nyanpasu/assets/64564727/cb373b2b-a824-4bf5-8a8a-81db968d5985

### 应用日志 / App logs

```plaintext
{"timestamp":"2024-06-15T01:05:25.071201Z","level":"WARN","fields":{"message":"NewEvents emitted without explicit RedrawEventsCleared","log.target":"tao::platform_impl::platform::event_loop::runner","log.module_path":"tao::platform_impl::platform::event_loop::runner","log.file":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.8\\src\\platform_impl\\windows\\event_loop\\runner.rs","log.line":359},"target":"tao::platform_impl::platform::event_loop::runner","filename":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.8\\src\\platform_impl\\windows\\event_loop\\runner.rs","line_number":359}
{"timestamp":"2024-06-15T01:05:25.076147Z","level":"WARN","fields":{"message":"RedrawEventsCleared emitted without explicit MainEventsCleared","log.target":"tao::platform_impl::platform::event_loop::runner","log.module_path":"tao::platform_impl::platform::event_loop::runner","log.file":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.8\\src\\platform_impl\\windows\\event_loop\\runner.rs","log.line":345},"target":"tao::platform_impl::platform::event_loop::runner","filename":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.8\\src\\platform_impl\\windows\\event_loop\\runner.rs","line_number":345}

```

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### Clash 核心及其版本号 / Clash core and version

1.18.3 Meta

### 是否为 Pre-release / Is pre-release version

不是

### 操作系统及版本 / OS version

Windows 11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [x] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by intzaaa** [comment]
1.4.5版本没有此问题

**Comment by keiko233** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/issues/763#issuecomment-2060237317

初步判断可以参考这个进行修复
