### ISSUE TITLE
1.5.0以上版本不能在Windows7下运行

### ISSUE THREAD

**Issue by sb16123131** [LibNyanpasu/clash-nyanpasu#1080]
### 复现步骤 / Step to reproduce

在Windows7下使用1.5.0以上版本

### 预期行为 / Expected behaviour

可以启动

### 实际行为 / Actual Behaviour

只有1.5.0以下版本的可以启动

### 应用日志 / App logs

没有

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.0

### Clash 核心及其版本号 / Clash core and version

v1.18.5 meta compatible go120

### 是否为 Pre-release / Is pre-release version

不是

### 操作系统及版本 / OS version

Windows7

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/issues/664#issuecomment-2177876205

Nyanpasu 不再对停止维护的系统做支持，包括但不限于Windows

**Comment by minusmulticoloredper** [comment]
问题在rust身上，目前好像有个方法可以，但是目前rust的维护者没有测试过它。
https://github.com/rust-lang/rust/blob/master/src/doc/rustc/src/platform-support/win7-windows-msvc.md

**Comment by minusmulticoloredper** [comment]
rust对win7的支持等级降低到Tier3，目前好像有个方法可以，但是目前rust的维护者没有测试过它。
https://doc.rust-lang.org/beta/rustc/platform-support/win7-windows-msvc.html

**Comment by minusmulticoloredper** [comment]
问题在Rust身上，Rust降低了对Windows7的支持等级，目前好像有个方法可以，但是目前rust的维护者没有测试过它。
https://doc.rust-lang.org/beta/rustc/platform-support/win7-windows-msvc.html

**Comment by minusmulticoloredper** [comment]
问题在Rust身上，Rust把对Windows7的支持单独做成了一个Target，但是目前rust的维护者没有测试过它，且这个Target无法直接添加。
https://doc.rust-lang.org/beta/rustc/platform-support/win7-windows-msvc.html

**Comment by minusmulticoloredper** [comment]
问题在Rust身上，在1.77.2版本之后放弃了对Windows7的主要支持并把它单独做成了一个Target，但是目前Rust的维护者没有测试过它，且这个Target无法直接添加。
https://doc.rust-lang.org/beta/rustc/platform-support/win7-windows-msvc.html
