### ISSUE TITLE
应用目录迁移之后，服务模式没有更新可执行文件路径，导致tun模式启动失败

### ISSUE THREAD

**Issue by xuhuanxxx** [libnyanpasu/clash-nyanpasu#1102]
### 复现步骤 / Step to reproduce

1、安装并激活服务模式，启用tun模式
2、迁移应用目录
3、重启应用或重启电脑

### 预期行为 / Expected behaviour

因为`nyanpasu`把clash verge service相关的可执行文件也放到了应用目录里，所以迁移之后应该更新一下service的可执行文件路径。

应用内重新安装服务模式似乎也没有效果。

### 实际行为 / Actual Behaviour

未正确配置服务模式，tun模式启动失败

### 备注 / Addition details

更新服务或者重装服务在windows下似乎不是一个好的解决办法。

service相关的文件、wintun.dll等算是nyanpasu功能的一部分，放在`C:\Program Files\<软件名>`应该更好一点，`C:\ProgramData\<软件名>`似乎也可以。如果一台电脑存在多个用户账户，这些也是可以复用的，而不是每个用户分别安装一个服务模式的service。

另外在windows下，默认的应用目录，不知道能不能把.config改为`C:\Users\<用户名>\AppData\Local\<软件名>`或者`C:\Users\<用户名>\AppData\Roaming\<软件名>`这种比较符合规范的目录，`C:\Users\<用户名>\Documents\<软件名>`应该也可以。如果有计划这么改的话，<软件名>可能也得注意避免配置成bundle id。

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.0

### Clash 核心及其版本号 / Clash core and version

v1.8.1

### 是否为 Pre-release / Is pre-release version

207bec0

### 操作系统及版本 / OS version

Windows 11 专业版，23H2，22631.3810

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by sheatwo** [comment]
最好可以像Clash verge rev那样，可以自己设置DNS端口和堆栈，gvisor堆栈不需要服务模式，只需以管理员身份运行即可。
如果用的是Mihomo内核，则使用Mihomo内置的wintun.dll，如果不是则使用外置wintun.dll。

**Comment by with344** [comment]
最好能让用户自己设置Tun堆栈，gvisor堆栈不需要服务模式，只需要以管理员身份运行即可。
如果使用Mihomo内核则使用Mihomo内置的wintun.dll，否则使用外置wintun.dll。

**Comment by greenhat616** [comment]
> 最好能让用户自己设置Tun堆栈，gvisor堆栈不需要服务模式，只需要以管理员身份运行即可。 如果使用Mihomo内核则使用Mihomo内置的wintun.dll，否则使用外置wintun.dll。

可以新开个 Issue

**Comment by greenhat616** [comment]
这个应该在最新的开发版中修复了，服务模式已重写，不会有这个问题了。
