### ISSUE TITLE
外部资源的节点订阅显示流量条和到期时间

### ISSUE THREAD

**Issue by dyphire** [LibNyanpasu/clash-nyanpasu#1116]
### 需求 / Requirement

clash-nyanpasu 的新版测试 ui 很不错，但和旧版本 ui 一样对于外部资源的节点订阅内容不会展示流量使用情况和到期时间
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/61936050/2a875ea9-0c60-42d6-bb88-928fb3f03585)

### 建议实现 / Suggested implements

希望能够像 clash-verge-rev 那样显示外部资源的节点订阅的流量使用情况和到期时间
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/61936050/68cc10b2-fd13-493d-a5b3-7a8184b10557)

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.2-alpha

### 是否为 Pre-release / Is pre-release version

da9497c

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
proxy provider是直接由内核管理，而proxies由nyanpasu管理，nyanpasu会单独处理http头的subscription-userinfo获取订阅信息，内核那边如果没有这个实现的话就获取不到了，暂时没仔细去了解，目前内核给到的subscriptionInfo是空的，具体原因未知

![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/76520798/4f2fa0e2-954b-42c0-b07d-825e3083bd03)

**Comment by dyphire** [comment]
> proxy provider是直接由内核管理，而proxies由nyanpasu管理，nyanpasu会单独处理http头的subscription-userinfo获取订阅信息，内核那边如果没有这个实现的话就获取不到了，暂时没仔细去了解，目前内核给到的subscriptionInfo是空的，具体原因未知
> 
> ![image](https://private-user-images.githubusercontent.com/76520798/344520051-4f2fa0e2-954b-42c0-b07d-825e3083bd03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4MDQxMjIsIm5iZiI6MTcxOTgwMzgyMiwicGF0aCI6Ii83NjUyMDc5OC8zNDQ1MjAwNTEtNGYyZmEwZTItOTU0Yi00MmMwLWIwN2QtODI1ZTMwODNiZDAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAxVDAzMTcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiM2QwNTY3ZDE2YzE5ZjAzZTdiNzJkMzdjNjQ2OTRlOGVkNDcxZWY4ZDZkZGFlNDI5ODk0Y2FmYmY1ZGIzYjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I_dfpARmbXjRohdgI35EoBt_BxT05dGlxWKKJUzaJ5Q)

直接使用 meta 内核的 webui 面板可以正常显示相关内容：
<img width="898" alt="image" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/61936050/cdc02538-cb67-4cc3-829c-091b14f34f67">

所以应该还是 nyanpasu 的相关实现存在问题

**Comment by dyphire** [comment]
找了下 clash-verge-rev 实现此功能的提交：https://github.com/clash-verge-rev/clash-verge-rev/commit/e970880059c54aaf7b8cffec42f4caed95778cc4
发现它也是基于 meta 内核 api 提供的 subscription-userinfo 信息实现的，nyanpasu 这块的 api 代码估计存在某种问题导致没能正常获取到正确的 subscription-userinfo 信息

**Comment by keiko233** [comment]
done.
https://github.com/LibNyanpasu/clash-nyanpasu/commit/10792ce2ab349a1f4c1100baac2d2d94063eb7aa
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/76520798/9e2b2621-9085-4415-9e05-85b52ae663c3)
