### ISSUE TITLE
日志和规则无法正常显示

### ISSUE THREAD

**Issue by Soniceso** [LibNyanpasu/clash-nyanpasu#1141]
### 复现步骤 / Step to reproduce

日志和规则显示不正常，日志只有最上面一点可以显示文字，如图
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/10915608/59faf433-2689-47ce-ab54-563d8c89ac61)
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/10915608/549c514a-c9dc-4789-8ea7-a42ffff7d29b)
规则压根就不显示了
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/10915608/dd425a4c-1874-42f8-b9ec-7215d66db8d4)

### 预期行为 / Expected behaviour

之前用1.5.1的时候日志和规则是可以正常显示的
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/10915608/3514b8e1-d73d-400b-be9b-1524a0ed3784)
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/10915608/2614c039-9aa8-4cb5-a062-98cb93acd0f4)

### 实际行为 / Actual Behaviour

如上

### 备注 / Addition details

顺便规则好像没汉化直接写的rules（虽然也没啥影响）

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.2+14e2c58

### Clash 核心及其版本号 / Clash core and version

1.18.6 meta

### 是否为 Pre-release / Is pre-release version

14e2c58

### 操作系统及版本 / OS version

WIN11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by Energetic3906** [comment]
同样有这个问题~~~

**Comment by greenhat616** [comment]
提供一份当前使用的 profile 发送至维护者邮箱。此外，请提供程序配置文件和程序日记方便调查

**Comment by keiko233** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/commit/e42f846c403c8c7f134e1adbd5acc049b0a5e551
https://github.com/LibNyanpasu/clash-nyanpasu/commit/66406d3ba3779720678bfe9e1d7c9e41eb041c2f

fixed
