### ISSUE TITLE
设置中添加Tun堆栈配置。

### ISSUE THREAD

**Issue by test5uninstall** [LibNyanpasu/clash-nyanpasu#1150]
### 需求 / Requirement

最好能让用户自己设置Tun堆栈，gvisor堆栈不需要服务模式，只需要以管理员身份运行即可，Mixed堆栈性能最好。

### 建议实现 / Suggested implements

https://wiki.metacubex.one/config/inbound/tun

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### 是否为 Pre-release / Is pre-release version

否

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
由于要顾及其他内核，臂如clash rust，该功能可能会在未来支持

**Comment by imoyy** [comment]
wsl2开启`networkingMode = mirrored`配置后必须使用`gvisor`才可以正常使用`tun`的网络，`mixed``system`都无法正常使用。这是wsl2长期的bug。

**Comment by greenhat616** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/commit/e48c1254a73d76fd0c35446135d53a12cb2321dd

已经实现此功能，欢迎测试。如果另有bug请新开 issue。

@imoyy nyanpasu 默认使用的 `gvisor` 堆栈，如果开启 tun 后仍有网络问题请再次调查。
