### ISSUE TITLE
Dev版本设置颜色错误后，导致软件无法打开界面。

### ISSUE THREAD

**Issue by Yueping1211** [LibNyanpasu/clash-nyanpasu#1162]
### 复现步骤 / Step to reproduce

![屏幕截图 2024-07-09 205322](https://github.com/LibNyanpasu/clash-nyanpasu/assets/57556789/d13291e3-2dd5-4b72-9162-144591a2645c)
在软件界面设置界面颜色错误（可能是删除了颜色框中的内容），导致软件界面无法打开，但服务正常。
卸载软件重新安装也无效。

### 预期行为 / Expected behaviour

软件正常打开

### 实际行为 / Actual Behaviour

软件故障

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.2

### Clash 核心及其版本号 / Clash core and version

软件无法打开，无法获得。

### 是否为 Pre-release / Is pre-release version

软件无法打开，无法获得。

### 操作系统及版本 / OS version

win11

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
fixed.
https://github.com/LibNyanpasu/clash-nyanpasu/commit/020fd18984bbca922fe3e96bc655a6880bf9bf09
等待构建完成就可以使用
