### ISSUE TITLE
希望可以单独关闭连接

### ISSUE THREAD

**Issue by Soniceso** [LibNyanpasu/clash-nyanpasu#1166]
### 需求 / Requirement

现在关闭连接只能选择关闭所有连接，希望可以出一个关闭指定连接的功能

### 建议实现 / Suggested implements

比如在所有连接的前面或者后面增加一个关闭该连接的button，或者直接选中后右键选择关闭
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/10915608/2ff0ed37-58d7-499c-a03f-317eeed68c6f)

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.2

### 是否为 Pre-release / Is pre-release version

020fd18

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/commit/883dfbbd6c36ad1eb82d5b168c5926e62dde3132
done.
