### ISSUE TITLE
1.5.1版本 订阅更新失败

### ISSUE THREAD

**Issue by Gogoworks** [LibNyanpasu/clash-nyanpasu#1178]
### 复现步骤 / Step to reproduce

报错提示
![image](https://github.com/user-attachments/assets/63270500-2065-44e5-8bf8-b7100e554759)

内核版本：
![image](https://github.com/user-attachments/assets/e249b6ca-b12c-4465-8417-ae1471aeaa8a)

### 预期行为 / Expected behaviour

之前订阅都是正常的，昨天突然发现更新不了。

### 实际行为 / Actual Behaviour

更新失败：

![image](https://github.com/user-attachments/assets/63270500-2065-44e5-8bf8-b7100e554759)

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### Clash 核心及其版本号 / Clash core and version

Mihomo V1.18.3

### 是否为 Pre-release / Is pre-release version

无

### 操作系统及版本 / OS version

Windows11

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly

或许应该去检查你的订阅地址？亦或是网络环境？
