### ISSUE TITLE
优化新版 UI 的代理界面下的菜单项选中时的强调色

### ISSUE THREAD

**Issue by dyphire** [LibNyanpasu/clash-nyanpasu#1179]
### 需求 / Requirement

目前新版 UI 的代理界面下的菜单项选中时的强调色和背景色过于接近，很不明显，尤其是黑暗模式下
![image](https://github.com/user-attachments/assets/1b79c462-9191-4a23-a666-1e998ca983d7)
![image](https://github.com/user-attachments/assets/52d2c507-4d16-4bbd-9249-078a3ec2198c)

### 建议实现 / Suggested implements

改进菜单项选中时的强调色，增加区分度和可读性

顺便新 UI 几乎都是圆角设计，只有代理组的菜单项的选中框还残留着直角设计，整个界面很不协调，也需要改进下这里的 UI
![image](https://github.com/user-attachments/assets/f58fe165-ee13-4640-9872-c4ff6f390a66)

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.2-alpha

### 是否为 Pre-release / Is pre-release version

5d3cbbc

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
也许可以通过引用html滚动条来解决滚动条占位置的问题，颜色的问题预计后期会提交commit修复下

**Comment by keiko233** [comment]
fixed on https://github.com/LibNyanpasu/clash-nyanpasu/commit/f12d5773a7b163c9319f8f59fb93d6f5e9383bec

![image](https://github.com/user-attachments/assets/8bd4f025-04a2-4768-aae3-6f5402f871b3)
