### ISSUE TITLE
新增加的连通性检测模块在使用IPV6地址时UI会显示错误

### ISSUE THREAD

**Issue by Soniceso** [LibNyanpasu/clash-nyanpasu#1189]
### 复现步骤 / Step to reproduce

RT，在一定的比例下，使用IPV6地址会导致新增加的模块以这样的形式展示
![image](https://github.com/user-attachments/assets/5db3b2f8-c37b-40e0-8590-b7be4f07dfa5)

### 预期行为 / Expected behaviour

应该是都在框框里才对，或者用其他形式表现

### 实际行为 / Actual Behaviour

如上

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.2

### Clash 核心及其版本号 / Clash core and version

1.18.2

### 是否为 Pre-release / Is pre-release version

4d414b8

### 操作系统及版本 / OS version

win11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
fixed on https://github.com/LibNyanpasu/clash-nyanpasu/commit/91a9144f720157168647f5e98b35e5d337046cf9
