### ISSUE TITLE
关于连接的一个很奇怪的BUG

### ISSUE THREAD

**Issue by Soniceso** [LibNyanpasu/clash-nyanpasu#1208]
### 复现步骤 / Step to reproduce

RT，打开软件处于除了连接外的任意页面，软件工作一切正常
![image](https://github.com/user-attachments/assets/595119d3-9a1b-49ef-9687-240cac4ab085)
当处于连接页面时，连接就会一个接着一个被关闭。
![image](https://github.com/user-attachments/assets/4fb88fb1-6a2f-4457-a05e-5f1863a439fa)

### 预期行为 / Expected behaviour

正常工作

### 实际行为 / Actual Behaviour

外在的体现为，当处于除连接外的界面时，QQ在托盘中的状态一切正常，当处于连接页面时，托盘中QQ的状态就会在 在线-离线-在线-离线-在线来回反复。从连接界面也可以看出连接在被一个一个断开-建立-断开-建立之间反复

### 备注 / Addition details

顺便单独关闭连接的功能貌似也不可用

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.2

### Clash 核心及其版本号 / Clash core and version

1.18.2

### 是否为 Pre-release / Is pre-release version

10b3bcc

### 操作系统及版本 / OS version

win11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
疑似组件的事件问题，这个关闭连接的组件将会在后期慢慢修改完善
