### ISSUE TITLE
clash字段过滤问题

### ISSUE THREAD

**Issue by Restia-Ashbell** [libnyanpasu/clash-nyanpasu#121]
杂项设置中关闭clash字段过滤但设置页面clash字段选项并没有隐藏，还发现”unified-delay: true“该项一直存在在运行配置中，但我并未写在配置中也没有勾选，这是默认值吗？

OS: WIN10
Clash Nyanpasu Version: 1.4.1
Clash Core: Clash Meta

**Comment by ttimochan** [comment]
`unified-delay: true` is default value

**Comment by ttimochan** [comment]
> unified-delay: true

mihomo provided the relevant options, and 'unified-delay: true' is the default behavior set by the author

**Comment by ttimochan** [comment]
> 我疑惑的是为什么配置文件填写false不能覆盖gui默认，也就是说gui默认>用户配置>核心默认，这使得无法自定义unified-delay和tcp-concurrent

When I was using it on Linux, I didn't encounter that situation; I applied the patch using a Merge type of file.
