### ISSUE TITLE
左上角会有图标和苹果图标重合

### ISSUE THREAD

**Issue by gufeng0** [LibNyanpasu/clash-nyanpasu#1213]
### 复现步骤 / Step to reproduce

无

### 预期行为 / Expected behaviour

没有图标

### 实际行为 / Actual Behaviour

<img width="1017" alt="image" src="https://github.com/user-attachments/assets/4d8462e7-3ba4-4586-bb40-51a35ed3dcc8">

### 环境信息 / Environment information

macOS 14.2.1 (23C71) 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
试试这个操作 https://github.com/LibNyanpasu/clash-nyanpasu/issues/62#issuecomment-2049875936
这个是上游的 Bug
