### ISSUE TITLE
[Feature] Dashboard 页添加 Shortcuts（快捷操作）栏

### ISSUE THREAD

**Issue by yangyzp** [LibNyanpasu/clash-nyanpasu#1217]
### 需求 / Requirement

建议如下：

### 建议实现 / Suggested implements

新版UI很好看，比之前也好用了。
为了更加简单易用一些，对新版UI提一个小建议，如下图：
![jy](https://github.com/user-attachments/assets/3dce4d44-22bd-416b-b18a-64316bf39d1c)

因为对于一般用户来说，订阅好配置文件后，后面的每次使用，基本就是选择节点，然后打开、关闭代理开关。
如果用户不切换节点，那就一个常用步骤：打开、关闭代理开关。

所以，建议把最常用的开关，放到第一个“概览”页面（如果把“代理开关”放到这个页面，叫做“概览”好像不太合适，可以叫“首页”或者“主页”）
**~~~~最后，这个是个人建议·~~~~**

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.2

### 是否为 Pre-release / Is pre-release version

d3b5ae4

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
有一个 issue 单独写 dashboard 的需求，可以转到这里讨论 https://github.com/LibNyanpasu/clash-nyanpasu/issues/584

**Comment by keiko233** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/commit/69e6f396fae15f93140132a8f4e8f9e55d2389b7

![image](https://github.com/user-attachments/assets/ca74e2c1-bc05-4959-a45c-809049d59143)
