### ISSUE TITLE
New Chain 脚本类型无法选择

### ISSUE THREAD

**Issue by fu050409** [LibNyanpasu/clash-nyanpasu#1223]
### 复现步骤 / Step to reproduce

![QQ_1721804458404](https://github.com/user-attachments/assets/03925455-b046-4cf8-b68b-afab4e91f4d3)

### 预期行为 / Expected behaviour

下拉框选择

### 实际行为 / Actual Behaviour

不可点击

### 环境信息 / Environment information

Windows 11 64位
dev版本

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
已知 bug，是 dialog 和 mui select 的冲突问题，请等待修复

**Comment by keiko233** [comment]
明天我有空的话看看，dialog目前动画也有问题，顺带一起修了

**Comment by keiko233** [comment]
fixed on https://github.com/LibNyanpasu/clash-nyanpasu/commit/a49a4a1c697fffb911a3b58e92eebd54406b45e8
dev build state https://github.com/LibNyanpasu/clash-nyanpasu/actions/runs/10105249195
