### ISSUE TITLE
代理组在少量规则的情况下展示存在异常

### ISSUE THREAD

**Issue by fu050409** [LibNyanpasu/clash-nyanpasu#1224]
### 复现步骤 / Step to reproduce

![QQ_1721804705126](https://github.com/user-attachments/assets/dde07ee3-5cce-4d4d-8bb4-05f87b488506)

### 预期行为 / Expected behaviour

内容量低于高度的情况下不应该存在`scrollbar-gutter: stable;`样式，或许我们可以使用`scrollbar-gutter: auto;`？

### 实际行为 / Actual Behaviour

UI偏移

### 环境信息 / Environment information

Windows 11 64位
dev版本

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
我们考虑采用手绘滚动条的方式让这类 scrollbar 悬浮（position: absolute）在父容器侧边。不过最近可能安排不上了。
