### ISSUE TITLE
Dev版本 `migration event` 的错误

### ISSUE THREAD

**Issue by imoyy** [LibNyanpasu/clash-nyanpasu#1235]
### 复现步骤 / Step to reproduce

1. 打开App
2. 出现bug

"Please see the migration.log in your data dir, and submit it." 在`~/.config/clash-nyanpasu`目录下的log目录没有出现日志文件，已经尝试彻底清理，并没有解决问题。

### 预期行为 / Expected behaviour

正常打开程序

### 实际行为 / Actual Behaviour

![CleanShot 2024-07-25 at 21 13 27@2x](https://github.com/user-attachments/assets/c92635f6-f96a-4883-945c-d408defe4b7f)
如图

### 备注 / Addition details

'0725eaf'这个版本之前的是没问题的，重新安装后可以正常打开程序，但从'7391392'这个版本就出现了上述bug。

### 环境信息 / Environment information

macOS x64
版本号: Clash.Nyanpasu_1.5.2-alpha+7391392_x64.dmg
系统信息: macOS Sonoma 14.5 (23F79)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by imoyy** [comment]
是macOS的逻辑还没写吗 :)

**Comment by greenhat616** [comment]
目录使用时间比创建时间早，所以出这个问题了，稍晚提交一个 build 修复一下。

**Comment by imoyy** [comment]
问题并未解决，如果告诉我日志的位置，我可以提交日志

**Comment by keiko233** [comment]
Windows 这边测试没问题了，macos 日志应该在 /Library/Application Support/Clash Nyanpasu 里面，或者等我稍晚时候去看看，暂时没有macos 环境

**Comment by imoyy** [comment]
> Windows 这边测试没问题了，macos 日志应该在 /Library/Application Support/Clash Nyanpasu 里面，或者等我稍晚时候去看看，暂时没有macos 环境

在这个位置并无该文件夹

**Comment by keiko233** [comment]
> > Windows 这边测试没问题了，macos 日志应该在 /Library/Application Support/Clash Nyanpasu 里面，或者等我稍晚时候去看看，暂时没有macos 环境
> 
> 在这个位置并无该文件夹

是我看错了，也许该看看用户下的 Library 路径
[pub fn suggest_data_dir(placeholder: &str) -> Option<PathBuf> {](https://github.com/LibNyanpasu/nyanpasu-utils/blob/main/dirs-utils/src/lib.rs#L21)

**Comment by imoyy** [comment]
> > > Windows 这边测试没问题了，macos 日志应该在 /Library/Application Support/Clash Nyanpasu 里面，或者等我稍晚时候去看看，暂时没有macos 环境
> > 
> > 
> > 在这个位置并无该文件夹
> 
> 是我记错了，也许该看看用户下的 Library 路径 [source code track](https://github.com/LibNyanpasu/nyanpasu-utils/blob/main/dirs-utils/src/lib.rs?rgh-link-date=2024-07-26T01%3A39%3A43Z#L21)

是的，是用户下的Library路径，现在我的问题得到了修复，下面是我发现的几个异常的点。
1. /Users/moyy/Library/Application Support 该路径下的clash-nyanpasu文件夹，在首次创建时会默认创建为”文稿“格式的文件，而不是文件夹。
2. 问题一得到解决后，再次打开软件会出现错误，日志如下
	```
	Running all upcoming migrations.
	Migration Split App Home Dir to Config and Data failed: Path "/Users/xxxx/.config/clash-nyanpasu" does not exist
	thread 'main' panicked at tauri/src/cmds/migrate.rs:59:45:
	Running all upcoming units. It is supposed to run in Nightly build. If you see this message in Stable channel, report it in Github Issues Tracker please.
	called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: Error { kind: NotFound, message: "Path \"/Users/xxxx/.config/clash-nyanpasu\" does not exist" } }
	note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
	Running unit: 1 migrations for v1.6.0
	Running migration: Split App Home Dir to Config and Data
	Advice: Pending
	Creating app config and data dir
	Moving other files and dirs to data dir
	```
解决方法
1. 当我手动删除异常文稿文件，手动创建同名文件夹后，问题一解决了
2. 出现问题二的原因是我在重装时，手动将用户下的.config文件夹中的clash-nyanpasu文件夹进行了删除。当我手动重新创建clash-nyanpasu文件夹后，再次打开软件问题就得到了解决。

**Comment by keiko233** [comment]
> > > > Windows 这边测试没问题了，macos 日志应该在 /Library/Application Support/Clash Nyanpasu 里面，或者等我稍晚时候去看看，暂时没有macos 环境
> > > 
> > > 
> > > 在这个位置并无该文件夹
> > 
> > 
> > 是我记错了，也许该看看用户下的 Library 路径 [source code track](https://github.com/LibNyanpasu/nyanpasu-utils/blob/main/dirs-utils/src/lib.rs?rgh-link-date=2024-07-26T01%3A39%3A43Z#L21)
> 
> 是的，是用户下的Library路径，现在我的问题得到了修复，下面是我发现的几个异常的点。
> 
> 1. /Users/moyy/Library/Application Support 该路径下的clash-nyanpasu文件夹，在首次创建时会默认创建为”文稿“格式的文件，而不是文件夹。
> 2. 问题一得到解决后，再次打开软件会出现错误，日志如下
>    ```
>    Running all upcoming migrations.
>    Migration Split App Home Dir to Config and Data failed: Path "/Users/xxxx/.config/clash-nyanpasu" does not exist
>    thread 'main' panicked at tauri/src/cmds/migrate.rs:59:45:
>    Running all upcoming units. It is supposed to run in Nightly build. If you see this message in Stable channel, report it in Github Issues Tracker please.
>    called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: Error { kind: NotFound, message: "Path \"/Users/xxxx/.config/clash-nyanpasu\" does not exist" } }
>    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
>    Running unit: 1 migrations for v1.6.0
>    Running migration: Split App Home Dir to Config and Data
>    Advice: Pending
>    Creating app config and data dir
>    Moving other files and dirs to data dir
>    ```
> 
> 解决方法
> 
> 1. 当我手动删除异常文稿文件，手动创建同名文件夹后，问题一解决了
> 2. 出现问题二的原因是我在重装时，手动将用户下的.config文件夹中的clash-nyanpasu文件夹进行了删除。当我手动重新创建clash-nyanpasu文件夹后，再次打开软件问题就得到了解决。

感谢测试非常详细，看来是判断路径的逻辑有点问题，稍晚一些时候我们这边看看

**Comment by greenhat616** [comment]
最新开发分钟将 `clash-nyanpasu` 目录改成 `Clash Nyanpasu` 目录了。
https://github.com/LibNyanpasu/clash-nyanpasu/issues/1251#issuecomment-2256476700
