### ISSUE TITLE
macOS 1.5.2 版本的服务模式开关异常

### ISSUE THREAD

**Issue by imoyy** [LibNyanpasu/clash-nyanpasu#1241]
### 复现步骤 / Step to reproduce

打开设置界面，查看System Service板块

### 预期行为 / Expected behaviour

应该正常安装卸载，打开关闭

### 实际行为 / Actual Behaviour

如图，点击卸载无反应，也无法开关服务模式。
可以通过官网提供的
```
sudo chown root:admin /Applications/Clash\ Nyanpasu.app/Contents/MacOS/mihomo-alpha
sudo chmod +sx /Applications/Clash\ Nyanpasu.app/Contents/MacOS/mihomo-alpha
```
命令正常运行tun模式。
![CleanShot 2024-07-26 at 12 56 56@2x](https://github.com/user-attachments/assets/1aba5e02-bf8d-42a8-a378-be3f6a7159ce)

### 备注 / Addition details

查找以往issue，我发现在[该issue](https://github.com/LibNyanpasu/clash-nyanpasu/issues/551#issue-2166591450)有着类似的问题。但他是Windows，我出现问题的平台在macOS。

### 环境信息 / Environment information

macOS Sonoma 14.5 (23F79) x64
Clash Nyanpasu 1.5.2 所有版本
所有clash核心

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
服务模式目前还在合并中，届时不可使用

**Comment by greenhat616** [comment]
最新开发版已经集成新的跨平台服务，欢迎测试反馈，谢谢。
