### ISSUE TITLE
软件内配置编辑器样式异常

### ISSUE THREAD

**Issue by imoyy** [LibNyanpasu/clash-nyanpasu#1242]
### 复现步骤 / Step to reproduce

在配置菜单中，点击Menu，选择Edit

### 预期行为 / Expected behaviour

应该占据全部的右侧空间

### 实际行为 / Actual Behaviour

如图所示
![CleanShot 2024-07-26 at 16 46 59@2x](https://github.com/user-attachments/assets/3b9af650-53d5-470d-9855-49c09f661413)

### 环境信息 / Environment information

版本号: Clash.Nyanpasu_1.5.2-alpha 版本
系统信息: macOS Sonoma 14.5 (23F79)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
fixed on https://github.com/LibNyanpasu/clash-nyanpasu/commit/9ea28052ca4c11e5be0ff94560265b1f356ec30b
