### ISSUE TITLE
全局代理模式下无法按延迟排序

### ISSUE THREAD

**Issue by greenhat616** [LibNyanpasu/clash-nyanpasu#1248]
### 复现步骤 / Step to reproduce

![Snipaste_2024-07-27_07-18-22](https://github.com/user-attachments/assets/967d516e-0759-4fd7-a8b1-a231ab626c26)

### 预期行为 / Expected behaviour

能按延迟排序

### 实际行为 / Actual Behaviour

未排序

### 应用日志 / App logs

x

### 环境信息 / Environment information

> ----------- System -----------
> OS: Windows 11 Pro 26100
> Arch: x86_64
> ----------- Device -----------
> CPU: Intel(R) Core(TM) i9-14900KF @ 3.20GHz x 32
> Memory: 63.84 GiB
> ----------- Core -----------
> mihomo: `Mihomo Meta v1.18.6 windows amd64 with go1.22.4 Mon Jul  1 15:03:47 UTC 2024 Use tags: with_gvisor`
> mihomo-alpha: `Mihomo Meta alpha-303f6e4 windows amd64 with go1.22.5 Fri Jul 26 14:33:33 UTC 2024 Use tags: with_gvisor`
> clash: `Clash n2023-09-05-gdcc8d87 windows amd64 with go1.21.0 Tue Sep  5 14:32:57 UTC 2023`
> clash-rs: `clash-rs 0.1.20`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 1.5.2-alpha+f7ce9e5
> Commit Hash: f7ce9e53f6ccc8930799b64ef2dbc502a2da2228
> Commit Author: Petard Jonson
> Commit Date: 2024-07-26T19:03:12.000Z
> Build Date: 2024-07-26T19:15:51.969Z
> Build Profile: Nightly
> Build Platform: x86_64-pc-windows-msvc
> Rustc Version: rustc 1.82.0-nightly (7120fdac7 2024-07-25)
> Llvm Version: 18.1
> 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
![image](https://github.com/user-attachments/assets/1eee00f8-10c7-4398-a63b-a12b34053279)
这里的sort直接排除了全局，稍后对代码进行整理修复

**Comment by keiko233** [comment]
fixed on https://github.com/LibNyanpasu/clash-nyanpasu/commit/9b687118bafb461b5fca708748904cd5c6b4f8ec
