### ISSUE TITLE
最新版TUN启动不了，需使用管理员权限打开

### ISSUE THREAD

**Issue by wqwxxxihhjjejesssooennc** [libnyanpasu/clash-nyanpasu#1250]
### 复现步骤 / Step to reproduce

CLASH及META内核，安装SERVICE MODE后，可不使用管理员权限，即可打开TUN。

### 预期行为 / Expected behaviour

安装并启动系统服务后，不需要管理员权限，即可正常启动TUN。

### 实际行为 / Actual Behaviour

已成功安装并启动系统服务，点击TUN，无法出现META网卡。
改用管理员权限打开程序，点击TUN，方能成功启动META网卡。

### 环境信息 / Environment information

windows 10，Clash.Nyanpasu_1.5.2-alpha+f09a073_x64，Meta 1.18.6

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
#1241
