### ISSUE TITLE
无法完成迁移事件

### ISSUE THREAD

**Issue by chen-jingliang** [LibNyanpasu/clash-nyanpasu#1251]
### 复现步骤 / Step to reproduce

1. 安装最新dev版本
2. 打开即显示上述错误

### 预期行为 / Expected behaviour

正常打开

### 实际行为 / Actual Behaviour

打开即报错
<img width="261" alt="SCR-20240727-splw" src="https://github.com/user-attachments/assets/dd05139d-40ff-44fd-ba56-8d256e954631">

### 环境信息 / Environment information

操作系统： macOS Sequoia BETA
Clash Nyanpasu 版本号：Clash.Nyanpasu_1.5.2-alpha+f09a073

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
https://github.com/LibNyanpasu/nyanpasu-utils/blob/a4d554586049a548528ed88c3f33a44450610f51/dirs-utils/src/lib.rs#L19-L23

目录应该是在这里：/// * - macOS: Resolves to $HOME/Library/Application Support/{placeholder}/data.

**Comment by chen-jingliang** [comment]
<img width="773" alt="SCR-20240728-iymu" src="https://github.com/user-attachments/assets/e55ac52f-25ea-4ba0-a69e-d9edd5dc7024">
没有找到此log文件，已经关掉隐藏功能。

**Comment by kingjoydom** [comment]
M1 Pro 上面有同样的问题

**Comment by greenhat616** [comment]
经过调查此问题是由目录创建错误导致的，由于不明原因导致 `/Users/{username}/Library/Application Support/clash-nyanpasu` 被创建成了文件（目前还没调查清楚是怎么导致的）。
和这个问题的行为一致：https://github.com/LibNyanpasu/clash-nyanpasu/issues/1235#issuecomment-2251915412

**Comment by greenhat616** [comment]
目前调查下来的结论是和当前的单例检测冲突了，最新的提交已修复。且为了规避检测不到的问题，将采用 Title 风格的目录名称。
![图片](https://github.com/user-attachments/assets/6014e96d-e5fb-4e29-bcc7-a03aa411ca7b)



https://github.com/LibNyanpasu/clash-nyanpasu/actions/runs/10148764692
