### ISSUE TITLE
clash nyanpasu crash/clash nyanpasu 打开直接崩溃

### ISSUE THREAD

**Issue by carrotluo5** [LibNyanpasu/clash-nyanpasu#1258]
### 复现步骤 / Step to reproduce

1 打开 clash 直接弹窗报错

### 预期行为 / Expected behaviour

正常打开

### 实际行为 / Actual Behaviour

>
![4DC548BEF48DD08E5B32A5617002B6E6](https://github.com/user-attachments/assets/b88bfd0c-02fb-4c4b-bc3e-c09596beff0e)

### 应用日志 / App logs

应用没打开.config/clash nyanpasu 没有生成日志，但我找到了他说的 migration.log
[migration.log](https://github.com/user-attachments/files/16408411/migration.log)

### 备注 / Addition details

上一个 dev 版就这样的(就是昨天的)，但是版本号我也不知道是多少了。昨天发现这种情况直接退回正式版去用了，能正常使用。今天又试着更新最新的 Dev 版结果还是同样的问题。

### 环境信息 / Environment information

系统版本  Windows 11 23h2 22631.3958
软件版本  Clash Nyanpasu Dev 47f5415

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/commit/fdfe0973341044630002020a6551bd9138e247e0

就你提交的日记，我尝试提交了一次修复，希望你能测试一下是否能解决这个问题，谢谢。
