### ISSUE TITLE
无法选择其他订阅链接

### ISSUE THREAD

**Issue by Jimie165** [LibNyanpasu/clash-nyanpasu#1264]
### 复现步骤 / Step to reproduce

![IMG_20240730_211024](https://github.com/user-attachments/assets/be309784-fda9-44f5-9b92-453c6cd1cdf8)
![IMG_20240730_211925](https://github.com/user-attachments/assets/113253b9-6113-49b6-9cdd-0578cbf64f46)

### 预期行为 / Expected behaviour

可以选择其他订阅链接

### 实际行为 / Actual Behaviour

无法通过点击来选择其他订阅，并且点使用没有反应

### 应用日志 / App logs

No response

### 备注 / Addition details

No response

### 环境信息 / Environment information

Windows 11 24H2 26100.560
Dev版

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
![image](https://github.com/user-attachments/assets/56c5f4ef-ac49-474a-8956-27a350df4f48)
这种情况可能是配置文件测试失败导致的，此前应用中是没有状态反馈的，昨日已经加上加载动画，
亦或者是chains修改没有通过导致，后续会改进这个问题
另外需要提供日志供诊断

**Comment by Jimie165** [comment]
更新后解决问题了，貌似是代理链的原因

**Comment by 4o3F** [comment]
Issue seems to be resolved, please reopen if the issue still exist
