### ISSUE TITLE
修改 Remote Profile 的 subscription url 类型为 `Array<string>`

### ISSUE THREAD

**Issue by greenhat616** [libnyanpasu/clash-nyanpasu#1276]
### 需求 / Requirement

尽管 Mihomo 提供了原生的 `proxies-providers` 支持，可以用于自定义刷新任何订阅后做合并。但是通过这种操作，用户需要了解 mihomo 自定义的语法（比如说 filter）来创建组等规则，对于专业用户来说可能会造成不便。
而目前 UI 没有集成此功能，用户想使用 UI 侧的 Chains 功能时，必须借助 SubStore 来整合多个订阅，这非常不方便。

### 建议实现 / Suggested implements

希望将 Remote Profile 的 url 类型修改成列表类型。
后端侧使用列表第一个元素作为基础 profile，然后其他列表的 url 仅提取其中的 proxies 字段，整合进 proxies 列表中。
UI 测将展示多个可删减的 TextInput，并利用 Framer Motion 的 ReOrder 组件来实现拖动排序。

通过这种做法，允许使用者利用专有链或全局链的 `Merge`、`Lua`、`Script` 处理单元的强大能力来自定义配置。
这样，在整合源提供 Clash 订阅格式的情况下，将无需借助 SubStore 即可进行订阅整合，降低使用者的心智负担。

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.6.x

### 是否为 Pre-release / Is pre-release version

x

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
> 如果可以内置SubStore的功能，那必须给你点赞呀，1.6.0会上这个功能不？ btw祝早日成为windows平台的surge平替

这个功能没计划在 1.6.0 中发布，考虑作为补丁版本的更新。

**Comment by zhang33ya** [comment]
一个实现建议：**开放的插件市场**
可以参考gui for clash项目，把不同的功能的脚本做成插件市场，用户根据自己的需求安装插件即可。开放的插件市场也有利于更多的人上传不同功能的插件，更加活跃繁荣。
![image](https://github.com/user-attachments/assets/210cb0c9-7d9b-4884-aad3-6d25023f9736)

**Comment by greenhat616** [comment]
此 PR 实现了后端支持，等测试通过后将实现前端支持。
https://github.com/libnyanpasu/clash-nyanpasu/pull/1663

**Comment by greenhat616** [comment]
关闭此 issue 以支持 #1701
