### ISSUE TITLE
代理为空，旧版本可以。

### ISSUE THREAD

**Issue by qianyueping1211** [LibNyanpasu/clash-nyanpasu#1303]
### 复现步骤 / Step to reproduce

![微信图片_20240805175924](https://github.com/user-attachments/assets/d1c80c87-c022-42f3-b94f-054e141d2a0e)
![微信图片_20240805175940](https://github.com/user-attachments/assets/d8d8afc6-7640-4aa3-b3fe-d37c204cba12)
![微信图片_20240805180010](https://github.com/user-attachments/assets/f0dea465-f4f7-4bc3-8d44-18a0ca4ff3d4)

使用今天的Windows新版本后，代理界面是空的，恢复上周版本正常。

### 预期行为 / Expected behaviour

一切正常

### 实际行为 / Actual Behaviour

代理异常为空，设置中ipv6无法选择。

### 环境信息 / Environment information

今天发布的版本

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
请正确提交应用日志，开发组们没法赛博诊断

**Comment by qianyueping1211** [comment]
[Uploading 2024-08-06-log.zip…]()

**Comment by keiko233** [comment]
日志无法打开

> Uploading 2024-08-06-log.zip…

**Comment by qianyueping1211** [comment]
[2024-08-07-log.zip](https://github.com/user-attachments/files/16518948/2024-08-07-log.zip)
抱歉，我重新上传了今天最新版本的日志。并且我换了一台Windows也是遇到一样的问题。
我在今天的操作日志路径是：
1、正常打开，选择系统设置中的系统代理，到代理组下什么没有。
2、切换clash内核报错，再去代理组下还是什么没有。
3、期间也尝试更新配置文件，后依然有问题。

**Comment by greenhat616** [comment]
![image](https://github.com/user-attachments/assets/de4601d0-99fc-4650-85e7-9c06e00d56ba)
![image](https://github.com/user-attachments/assets/afd72edc-a16a-41c1-93ca-146d013f4f9d)

初步分析 runtime profile 存在问题以及网络环境存在问题，有可能和 DNS 干扰有关系。
如果 profile 中使用了 proxy provider 和 rules provider 需要自己担保网络环境无污染

**Comment by qianyueping1211** [comment]
同样的配置文件，同样网络 切换为旧版本就可以。

**Comment by greenhat616** [comment]
是的，这是有可能的。mihomo 给你的错误信息是 `invaild mode`。出现这个情况的时候可以把 runtime-config、draft config 如果🈶️，提交给我们。邮件或者去除 rules，subscriptions 的文件
![image](https://github.com/user-attachments/assets/8e0306ad-0810-445c-9dae-118658536807)

**Comment by greenhat616** [comment]
亦或是你可以通过这个观察一下配置有没有问题：
![image](https://github.com/user-attachments/assets/2fbbf7ee-f2b8-4f2e-a860-2e5b87e0bc56)

**Comment by greenhat616** [comment]
你提供的配置已经收到。目前已经定位到的错误是什么原因导致的，不出意外的话这个错误很快就会被修复，但可能需要你手动删除 `clash-guard-overrides.yaml` 文件

**Comment by greenhat616** [comment]
稍微可以尝试一下这个 build 能不能解决这个问题：https://github.com/LibNyanpasu/clash-nyanpasu/actions/runs/10367815236

**Comment by qianyueping1211** [comment]
确认，新版本已经解决。感谢感谢!
