### ISSUE TITLE
RuleSet 名称大小写问题

### ISSUE THREAD

**Issue by PctAIGM** [LibNyanpasu/clash-nyanpasu#1323]
### 复现步骤 / Step to reproduce

```
const common = {
    type: "http",
    behavior: "classical",
    interval: 86400
}

export default function (profile) {
    const ruleProviders  = {
        ...profile['rule-providers'],
        "Telegram": {
            ...common,
            path: "./ruleset/Telegram.yaml",
            url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Telegram/Telegram.yaml"
        }
    }
        profile['rule-providers'] = ruleProviders
        return profile;
    }
```

```
prepend-rules:
  - RULE-SET,Telegram,AllHk
```

### 预期行为 / Expected behaviour

不报错

### 实际行为 / Actual Behaviour

![image](https://github.com/user-attachments/assets/a8a503b4-f5c4-454e-b6ce-5c0aadb0d458)

需要把ruleset的规则名改为小写才能通过，例外如果机场有用到ruleset且名称大写，也会导致该机场的订阅无法使用。

### 环境信息 / Environment information

![image](https://github.com/user-attachments/assets/158795fe-dbc8-4b5b-a8b0-69969d4a2fd1)

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
cc @4o3F
