### ISSUE TITLE
UBUNTU 24.04 无法启动

### ISSUE THREAD

**Issue by alexanderywy** [LibNyanpasu/clash-nyanpasu#1329]
### 复现步骤 / Step to reproduce

重启系统并在开机时进入NYANPASU三次

### 预期行为 / Expected behaviour

成功启动NYANPUSU

### 实际行为 / Actual Behaviour

启动失败

### 应用日志 / App logs

{"timestamp":"2024-08-07T12:07:52.733648Z","level":"ERROR","fields":{"message":"panic hook: PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: single instance check failed: app still exists after 4s), location: Location { file: \"tauri/src/main.rs\", line: 79, col: 45 }, can_unwind: true, force_no_backtrace: false }","log.target":"app","log.module_path":"clash_verge","log.file":"tauri/src/main.rs","log.line":70},"target":"app","filename":"tauri/src/main.rs","line_number":70} 

### 环境信息 / Environment information

UBUNTU 24.04 Latest
1.5.1

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
最新开发版可用么？
自1.5.1已经有1000 commits提交进主线了，所以我们不考虑对1.5.1单独back port修复了。

如果最新开发版不可用的话，我们会将这个问题标记为 release blocker，在1.6发布前解决。

**Comment by alexanderywy** [comment]
试过了用不了，24.04变化蛮大的发自我的 iPhone在 2024年8月7日，20:37，Jonson Petard ***@***.***> 写道：﻿
最新开发版可用么？
自1.5.1已经有1000 commits提交进主线了，所以我们不考虑对1.5.1单独back port修复了。
如果最新开发版不可用的话，我们会将这个问题标记为 release blocker，在1.6发布前解决。

**Comment by greenhat616** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/commit/bfa82036b959327325884c377a2ddfceccec3b6e
