### ISSUE TITLE
替换托盘图标时，用户自定义的图标永远要比默认图标小，即使使用了512*512的大小的图标

### ISSUE THREAD

**Issue by 1001ace1001** [LibNyanpasu/clash-nyanpasu#1332]
### 复现步骤 / Step to reproduce

![image](https://github.com/user-attachments/assets/1a7f98be-e37b-48b0-969a-d9e6dd1c6a43)
![image](https://github.com/user-attachments/assets/c8523fe3-3358-40d4-9a3b-2aaa9e2d93d6)
![image](https://github.com/user-attachments/assets/aa900ff6-1c69-46d1-83bb-2fd1e83c51e6)

### 预期行为 / Expected behaviour

它应该和默认图标一样大的诶~
![image](https://github.com/user-attachments/assets/022020f3-f828-4dee-bceb-cd122f584154)

### 实际行为 / Actual Behaviour

现在他变小了，不知道这个是不是bug，我使用的图标是512×512的png格式的图片。
![image](https://github.com/user-attachments/assets/181b0bdb-d165-4cfb-96eb-ff83735657fa)
![Clash Nyanpasu3reverse](https://github.com/user-attachments/assets/65bbbce0-4a68-4c0b-ab55-933fc9eea722)

### 应用日志 / App logs

这个bug的复现应该用到日志么？
如果需要日志的话请告知~

### 备注 / Addition details

![image](https://github.com/user-attachments/assets/afc744e9-8192-4295-8723-845978492186)
不知道在以后的版本中能不能默认释出这三个图标呢？

### 环境信息 / Environment information

![image](https://github.com/user-attachments/assets/f133a6d7-8ed3-4b15-97c3-b5cc1ea0b2bf)
版本如上。
![image](https://github.com/user-attachments/assets/0a7cf4f8-9227-48ff-ae0c-44e2b1be3dd2)
Windows版本如上。

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by 1001ace1001** [comment]
这应该打上一个UI的标签的）

**Comment by greenhat616** [comment]
妳的图标没裁白边，肯定小一圈的

**Comment by 1001ace1001** [comment]
> 妳的图标没裁白边，肯定小一圈的

原来是要自己做一个白边么）

**Comment by 1001ace1001** [comment]
也就是说只要图标周边是透明这东西就是会这样？

**Comment by greenhat616** [comment]
我们不会裁切图片，未来也没计划内嵌裁切图片的功能。
我们只会并且已经实现根据dpi缩放图标以确保托盘图标不会被系统的缩放导致过度锯齿化。

**Comment by 1001ace1001** [comment]
好，我回去试试看。

**Comment by 1001ace1001** [comment]
![Clash Nyanpasubacktest3](https://github.com/user-attachments/assets/6e9eff7a-a05b-462c-ac17-933c2dd30501)
在几十次失败之后终于找到了方法）
感谢开发者的协助~！
