### ISSUE TITLE
直连测速延迟很高，其他节点也高，平均5000ms以上

### ISSUE THREAD

**Issue by Byte-Chimera** [libnyanpasu/clash-nyanpasu#1383]
### 复现步骤 / Step to reproduce

![1723684997913](https://github.com/user-attachments/assets/769e9372-34c7-4547-a89a-791b933446b6)

### 预期行为 / Expected behaviour

实际延迟应该100左右
![image](https://github.com/user-attachments/assets/f0e62075-e6ef-482d-af98-356bb1ce0bef)
![image](https://github.com/user-attachments/assets/0ad68c00-d922-49b6-99c6-383ef133b57f)

### 实际行为 / Actual Behaviour

如上

### 环境信息 / Environment information

window 11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
测速地址是哪个，应用日志是否提供

**Comment by Byte-Chimera** [comment]
> 测速地址是哪个，应用日志是否提供

![image](https://github.com/user-attachments/assets/c1099efb-7856-4ff4-bce2-b52bb87417f1)
是这个日志吗，还是有其他文件，测速地址是软件默认的，没有修改过

**Comment by keiko233** [comment]
默认测速是谷歌的，在中国大陆理论是无法连接的，如果你要直连延迟低请自行修改配置或测速地址

**Comment by Byte-Chimera** [comment]
代理节点的延迟也很高，都是5000以上

**Comment by keiko233** [comment]
请检查节点连通性，网络环境，配置文件，没有日志我们也没法隔空听脉

**Comment by NEK2eRo** [comment]
您的clash 内核是否使用 clash rust

**Comment by Byte-Chimera** [comment]
> 您的clash 内核是否使用 clash rust

怎么查看呢
