### ISSUE TITLE
规则和日志界面上方搜索栏UI出现bug，右边不正常显示

### ISSUE THREAD

**Issue by cnblackhole** [LibNyanpasu/clash-nyanpasu#1395]
### 复现步骤 / Step to reproduce

<img width="664" alt="1" src="https://github.com/user-attachments/assets/e0edd1fd-055e-46b4-ac65-d758a1404295">

https://github.com/user-attachments/assets/747866a6-fa2e-4112-8ef6-6b73d51c30b2

### 预期行为 / Expected behaviour

正常应该左右对称，UI显示不超过界面

### 实际行为 / Actual Behaviour

实际上搜索框右边超过界面显示，界面向左拉伸仍然无法正确显示

### 环境信息 / Environment information

win11，1.5.1，1.18.3meta

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version
