### ISSUE TITLE
打开软件前台界面后，无法运行calibre电子书管理软件

### ISSUE THREAD

**Issue by wrlssqi** [LibNyanpasu/clash-nyanpasu#1417]
### 复现步骤 / Step to reproduce

1. 打开 clash-nyanpasu 前台界面
2. 尝试打开 calibre。发现无法打开。在任务管理器看到有一瞬间的calibre条目，随即消失，说明calibre闪退
3. 关闭clash-nyanpasu前台界面，保留在后台运行，再尝试运行calibre后，成功打开calibre

另外，还发现在calibre打开的状态下，从托盘单击图标尝试打开clash-nyanpasu的界面时，会发生严重的延迟，差不多要 10s 以上才能打开界面。而在不运行calibre的情况下，点击托盘图标后，clash-nyanpasu界面能立即打开。

因为目前不清楚是哪方的问题，姑且在此提一下issue。

### 预期行为 / Expected behaviour

两个软件不应互相影响

### 实际行为 / Actual Behaviour

两个软件互相影响

### 环境信息 / Environment information

win 11 22631.4037 ， Clash Nyanpasu prerelease  created at Fri Aug 23 08:56:54 CST 2024. , mihomo v1.18.7, tun模式

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
![图片](https://github.com/user-attachments/assets/bdffbf5b-0d37-434c-817e-d0d20471a921)
未能复现这个问题

**Comment by wrlssqi** [comment]
ok，我自己摸索摸索，可能是我电脑环境哪里有问题。非常感谢
