### ISSUE TITLE
日志页的暂停键不起作用

### ISSUE THREAD

**Issue by easyinplay** [LibNyanpasu/clash-nyanpasu#1429]
### 复现步骤 / Step to reproduce

![image](https://github.com/user-attachments/assets/8d6896dc-9deb-409d-af56-1c67c3ed7f80)
打开日志页点击暂定按钮

### 预期行为 / Expected behaviour

正常情况下暂停不产生新日志，现在暂停不暂停都在一直产生

### 实际行为 / Actual Behaviour

![image](https://github.com/user-attachments/assets/4d17607a-30de-4c30-b505-48d62abb6a78)

### 应用日志 / App logs

[2024-08-26-log.zip](https://github.com/user-attachments/files/16743218/2024-08-26-log.zip)

### 环境信息 / Environment information

> ----------- System -----------
> OS: Windows 11 Pro for Workstations 27686
> Arch: x86_64
> ----------- Device -----------
> CPU: Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz @ 2.90GHz x 6
> Memory: 31.87 GiB
> ----------- Core -----------
> mihomo-alpha: `Mihomo Meta alpha-50d0cd3 windows amd64 with go1.22.5 Tue Aug 13 06:23:10 UTC 2024 Use tags: with_gvisor`
> mihomo: `Mihomo Meta v1.18.7 windows amd64 with go1.22.5 Sun Jul 28 05:48:59 UTC 2024 Use tags: with_gvisor`
> clash: `Clash n2023-09-05-gdcc8d87 windows amd64 with go1.21.0 Tue Sep  5 14:32:57 UTC 2023`
> clash-rs: `clash-rs 0.2.0`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 1.5.2-alpha+479457d
> Commit Hash: 479457d90b82eeac66406db543ec26e1c1d8c150
> Commit Author: github-actions[bot]
> Commit Date: 2024-08-13T22:20:21.000Z
> Build Date: 2024-08-14T00:43:08.960Z
> Build Profile: Nightly
> Build Platform: x86_64-pc-windows-msvc
> Rustc Version: rustc 1.82.0-nightly (91376f416 2024-08-12)
> Llvm Version: 19.1
> 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
fix at https://github.com/LibNyanpasu/clash-nyanpasu/commit/270dd25f388912f0928ef26063ade90025d07391
