### ISSUE TITLE
DEV版在MACOS 15.1BETA菜单栏再次打开面板大概率卡死

### ISSUE THREAD

**Issue by chen-jingliang** [libnyanpasu/clash-nyanpasu#1441]
### 复现步骤 / Step to reproduce

1. 打开DEV版，最小化到菜单栏
2. 点击图标，选择打开面板
3. 大概率卡死，必须退出，重新打开

### 预期行为 / Expected behaviour

不卡死

### 实际行为 / Actual Behaviour

最近几个DEV版本一直有这个问题，主要发生在第二次打开面板

### 环境信息 / Environment information

系统：MACOS 15.1BETA
Clash Nyanpasu 版本号：Clash.Nyanpasu_1.5.2-alpha+020e1e3

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
可能和 Safari（Webkit）自身的缺陷有关系，这个问题应该在 Linux 上也能复现（最小化再恢复）。这几天尝试下能否将 MacOS 的窗口干掉，这样就能规避这个 Webkit 自身的缺陷了

**Comment by greenhat616** [comment]
Dev build 正在构建了，稍微请尝试一下这个 commit 是否工作正常：https://github.com/LibNyanpasu/clash-nyanpasu/commit/e0a2a71578c90159a7410274e27f742707c906dc
