### ISSUE TITLE
快捷键添加之后 用两次就失效了 配置没了

### ISSUE THREAD

**Issue by algerkong** [libnyanpasu/clash-nyanpasu#1449]
### 复现步骤 / Step to reproduce

1、配置快捷键  使用开启或关闭面板的快捷键 用几次就失效了  快捷键的配置都没了

### 预期行为 / Expected behaviour

正常使用快捷键

### 实际行为 / Actual Behaviour

快捷键失效  配置消失

### 备注 / Addition details

1. 快捷键不好用
2. 希望可以一键打开或关闭系统代理
3. 为啥要设置不同的快捷键 打开关闭同一个功能
4. 另外 tun模式的蓝色图标为什么优先级比系统代理的红色图标优先级高  应该系统代理优先级高

### 环境信息 / Environment information

windows11 23h2
Clash Nyanpasu 1.5.1
Clash 核心 1.18.7 Mata

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
您已搜索过 Issue Tracker，没有找到类似内容 / I have searched on Issue Tracker, No duplicate or related open issue has been found
 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
