### ISSUE TITLE
建议在开启 Tun 模式时提示开启服务模式

### ISSUE THREAD

**Issue by lemonicy** [libnyanpasu/clash-nyanpasu#1451]
### 需求 / Requirement

在目前的测试版本中，开启 Tun 模式不会有任何提示，但如果用户没有手动开启服务模式，电脑重启后 Clash Nyanpasu 无法自动添加名为 Meta 的虚拟网卡，导致无法翻墙，所以这里加个提示就显得非常有必要。

### 建议实现 / Suggested implements

可参考目前 Clash Verge Rev 的实现，把服务模式的开关和 Tun 模式放在一块，并在开启 Tun 模式时提示需要先给予管理员权限并开启服务模式。

### Clash Nyanpasu 版本号 / Clash Nyanpasu

v1.5.2-alpha+1f1d752

### 是否为 Pre-release / Is pre-release version

1f1d752

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
有这个计划，在跑运行配置前分析配置。准备之后的补丁版本做。

**Comment by greenhat616** [comment]
https://github.com/libnyanpasu/clash-nyanpasu/commit/38b2512ef5488a3365a3bc486e7623adeb10206a
