### ISSUE TITLE
卸载后软件依然在 Windows 的启动项中

### ISSUE THREAD

**Issue by lemonicy** [libnyanpasu/clash-nyanpasu#1453]
### 复现步骤 / Step to reproduce

卸载软件即可复现，复现率为 100%，哪怕勾选清除数据也可以复现。

### 预期行为 / Expected behaviour

预期是卸载后删除启动项

### 实际行为 / Actual Behaviour

实际上并未销毁启动项，如下图。
![image](https://github.com/user-attachments/assets/1be273ce-1ad8-416c-8190-dd134b858ad1)

### 应用日志 / App logs

卸载重装后日志没有了

### 环境信息 / Environment information

> ----------- System -----------
> OS: Windows 11 Pro 22631
> Arch: x86_64
> ----------- Device -----------
> CPU: 13th Gen Intel(R) Core(TM) i7-13700K @ 3.40GHz x 24
> Memory: 63.77 GiB
> ----------- Core -----------
> mihomo: `Mihomo Meta v1.18.7 windows amd64 with go1.22.5 Sun Jul 28 05:48:59 UTC 2024 Use tags: with_gvisor`
> clash-rs: `clash-rs 0.3.0`
> mihomo-alpha: `Mihomo Meta alpha-38fd371 windows amd64 with go1.23.0 Thu Aug 29 16:08:34 UTC 2024 Use tags: with_gvisor`
> clash: `Clash n2023-09-05-gdcc8d87 windows amd64 with go1.21.0 Tue Sep  5 14:32:57 UTC 2023`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 1.6.0
> Commit Hash: edf8e8d1c2fa7ac3dcbfedddb376da2437c70885
> Commit Author: github-actions[bot]
> Commit Date: 2024-08-29T19:09:44.000Z
> Build Date: 2024-08-29T19:18:20.042Z
> Build Profile: Release
> Build Platform: x86_64-pc-windows-msvc
> Rustc Version: rustc 1.82.0-nightly (100fde524 2024-08-28)
> Llvm Version: 19.1
> 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
请尝试一下最新的开发版：https://github.com/libnyanpasu/clash-nyanpasu/actions/runs/10749327897

**Comment by lemonicy** [comment]
> 请尝试一下最新的开发版：https://github.com/libnyanpasu/clash-nyanpasu/actions/runs/10749327897
> 
> 注：卸载程序需要安装后再尝试，旧版本卸载将调用旧的卸载程序。

我试了一下，已确认解决
