### ISSUE TITLE
安装最新版本的 1.6.0 在 MacOS Pro(M1) 无法打开，提示无权限迁移配置文件

### ISSUE THREAD

**Issue by zhgqthomas** [libnyanpasu/clash-nyanpasu#1454]
### 复现步骤 / Step to reproduce

从低版本升级到 1.6.0时

### 预期行为 / Expected behaviour

正常打开

### 实际行为 / Actual Behaviour

程序报错：
Failed to finish migration event: child process failed: ExitStatus(unix_wait_status(25856)), err: Migration Split App Home Dir to Config and Data failed: Permission denied (os error 13); trying to discard changes
Migration Split App Home Dir to Config and Data discarded.
thread 'main' panicked at tauri/src/cmds/migrate.rs:67:22:
called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: Error { kind: PermissionDenied, message: "Permission denied (os error 13)" } }

### 应用日志 / App logs

Failed to finish migration event: child process failed: ExitStatus(unix_wait_status(25856)), err: Migration Split App Home Dir to Config and Data failed: Permission denied (os error 13); trying to discard changes
Migration Split App Home Dir to Config and Data discarded.
thread 'main' panicked at tauri/src/cmds/migrate.rs:67:22:
called `Result::unwrap()` on an `Err` value: Custom { kind: InvalidInput, error: Error { kind: PermissionDenied, message: "Permission denied (os error 13)" } }

### 环境信息 / Environment information

Clash Nyanpasu 版本：1.6.0
操作系统： MacOS M1

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
请提交 `migration.log`，他应该在 `$HOME/Library/Application Support/Clash Nyanpasu/data` 目录下

**Comment by freeNestor** [comment]
我是新安装1.6.0 macos m1，点击启动服务模式，输入管理员密码后，报服务模式start failed

**Comment by DeShuiYu** [comment]
> 我是新安装1.6.0 macos m1，点击启动服务模式，输入管理员密码后，报服务模式start failed
我的mac m1 电脑，也是点击启动服务模式，报start failed 错误，并且感觉新版本的内存占用达到了200多M，比之前的占用内存多很多

**Comment by kratos9394** [comment]
还是用回老版本先

**Comment by zhgqthomas** [comment]
> 请提交 `migration.log`，他应该在 `$HOME/Library/Application Support/Clash Nyanpasu/data` 目录下。 题外话，你之前有尝试使用 `sudo` 方式启动 App 么？

我尝试过使用 sudo 来启动 App了，因为已经回退到 1.5.0 的版本，因此电脑上已经没有 migration.log 文件了

**Comment by greenhat616** [comment]
这个目录不会因回退删除的
