### ISSUE TITLE
macos（m2）关闭gui后，打开面板无法打开gui

### ISSUE THREAD

**Issue by Amnesiash** [libnyanpasu/clash-nyanpasu#1457]
### 复现步骤 / Step to reproduce

macos（m2）关闭gui后，打开面板无法打开gui

### 预期行为 / Expected behaviour

macos（m2）关闭gui后，打开面板无法打开gui

### 实际行为 / Actual Behaviour

macos（m2）关闭gui后，打开面板无法打开gui

### 环境信息 / Environment information

macos（m2）关闭gui后，打开面板无法打开gui

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly

**Comment by Kfkcome** [comment]
我也出现了这个问题，是在重启前设置重启后重新打开应用，然后重启状态栏显示有此应用的图标，但是无法打开gui界面

> 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly

**Comment by greenhat616** [comment]
有可能和这个 commit 有关系，具体原因还得调查一下。
https://github.com/libnyanpasu/clash-nyanpasu/commit/cdf2ec1a60ff4bdf8733f9b7d1a8fc66c905ea47

目前手头无 macOS 设备，今天没法测试了。

**Comment by Kfkcome** [comment]
> 有可能和这个 commit 有关系，具体原因还得调查一下。 [cdf2ec1](https://github.com/libnyanpasu/clash-nyanpasu/commit/cdf2ec1a60ff4bdf8733f9b7d1a8fc66c905ea47)
> 
> 目前手头无 macOS 设备，今天没法测试了。

感谢，要是需要测试，我可以帮忙测试

**Comment by greenhat616** [comment]
我这里没法复现这个问题，请尝试将 `App Log` 修改为 `TRACE`，然后复现此问题后提交日记到这个 issue。
怎么修改请参考文档 FAQ。
