### ISSUE TITLE
导入clash meta订阅时只导入了原版内核支持协议的节点

### ISSUE THREAD

**Issue by jwstaceyOvO** [libnyanpasu/clash-nyanpasu#1473]
### 复现步骤 / Step to reproduce

导入任意包含新协议节点（vless reality、 hy2等）的clash meta订阅

### 预期行为 / Expected behaviour

应该能导入所有节点，包括vless reality等新协议的节点，此问题在其他mihomo客户端（ clash verge rev/ clash meta for android / flclash / mihomo party）上未发现

### 实际行为 / Actual Behaviour

只导入了原版内核支持协议（shadowsocks等）的节点

### 环境信息 / Environment information

win11 
Clash Nyanpasu v1.6.0
Clash 核心： mihomo v1.18.7

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
https://nyanpasu.elaina.moe/zh-CN/others/faq#_5-%E7%BC%BA%E5%B0%91%E8%AE%A2%E9%98%85%E8%8E%B7%E5%8F%96%E8%8A%82%E7%82%B9%E7%B1%BB%E5%9E%8B
