### ISSUE TITLE
Connection 界面功能建议

### ISSUE THREAD

**Issue by wqwxxxihhjjejesssooennc** [libnyanpasu/clash-nyanpasu#1474]
### 需求 / Requirement

Connection界面功能建议

1）添加自定义字段功能，可选择是否显示某些不需要的字段，比如source。
![CONNECTIONS](https://github.com/user-attachments/assets/26118e18-3fcb-4a46-994c-3e11bd6fdb2a)

2）添加查看代理节点连接的国内中转入口IP，或直连的国外vps的IP的功能。

### 建议实现 / Suggested implements

比如，某mihomo内核软件，通过代理连接到google，目标IP显示的是clash解析出的google ip，而远程目标显示的就是国内阿里云中转的IP地址。这对查看节点信息是颇为有用的功能。

![屏幕截图 2024-09-01 125943](https://github.com/user-attachments/assets/1ce38144-8613-4a54-ae21-52f3ce97377a)

### Clash Nyanpasu 版本号 / Clash Nyanpasu

v1.6.1

### 是否为 Pre-release / Is pre-release version

84a0a78

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
单独的信息页已经支持
