### ISSUE TITLE
使用本地配置时配置yaml格式错误无报错提示

### ISSUE THREAD

**Issue by getopenwrt** [libnyanpasu/clash-nyanpasu#1491]
### 复现步骤 / Step to reproduce

1）配置页面添加Local Profile配置，留空新建，点菜单编辑信息删除默认行“rules: []”，粘贴一份配置（配置中有一处缩进错误）点击ok后配置保存完成，点击这个配置文件出现绿点，再次点击菜单编辑信息界面仍显示默认行“rules: []”，点击菜单打开文件可以看到粘贴的配置信息。这个情况配置本身不可用，但界面没有任何错误提示。
2）添加Local Profile配置时选择文件方式添加有同样的问题。

### 预期行为 / Expected behaviour

1）如果添加Local Profile配置有问题不可用应给出错误提示。
2）如果对添加Local Profile配置yaml格式不做校验也行，但在点击配置后配置不可用应该给出错误提示。

### 实际行为 / Actual Behaviour

添加的配置信息：
![image](https://github.com/user-attachments/assets/84f75ad1-a791-41bc-a324-3f3326ea51a2)

点击ok后：
![image](https://github.com/user-attachments/assets/9f1bfa47-54de-43df-9753-fbae40186e75)

点击菜单编辑信息：
![image](https://github.com/user-attachments/assets/c0dcef48-e067-4dad-b80a-f1f00c5c3562)
点击菜单打开文件：
![image](https://github.com/user-attachments/assets/f0c5a144-3c6a-4fa4-8a64-380071f3d18a)

### 应用日志 / App logs

1）描述现象进行了多次复现操作且容易复现，考虑到终端本身有网络活动，日志有节点及连接信息，不便提供日志。

### 环境信息 / Environment information

> ----------- System -----------
> OS: Windows 10 Pro 19045
> Arch: x86_64
> ----------- Device -----------
> CPU: AMD Ryzen 7 4800U with Radeon Graphics          @ 1.80GHz x 16
> Memory: 14.87 GiB
> ----------- Core -----------
> clash-rs: `clash-rs 0.3.0`
> clash: `Clash n2023-09-05-gdcc8d87 windows amd64 with go1.21.0 Tue Sep  5 14:32:57 UTC 2023`
> mihomo-alpha: `Mihomo Meta alpha-38fd371 windows amd64 with go1.23.0 Thu Aug 29 16:08:34 UTC 2024 Use tags: with_gvisor`
> mihomo: `Mihomo Meta v1.18.7 windows amd64 with go1.22.5 Sun Jul 28 05:48:59 UTC 2024 Use tags: with_gvisor`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 1.6.0
> Commit Hash: edf8e8d1c2fa7ac3dcbfedddb376da2437c70885
> Commit Author: github-actions[bot]
> Commit Date: 2024-08-29T19:09:44.000Z
> Build Date: 2024-08-29T19:18:20.042Z
> Build Profile: Release
> Build Platform: x86_64-pc-windows-msvc
> Rustc Version: rustc 1.82.0-nightly (100fde524 2024-08-28)
> Llvm Version: 19.1
> 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [x] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
@keiko233 cc https://github.com/remcohaszing/monaco-yaml
