### ISSUE TITLE
希望托盤圖標右鍵菜單可以適配深色主題

### ISSUE THREAD

**Issue by RyanLeigh1221** [libnyanpasu/clash-nyanpasu#1493]
### 需求 / Requirement

希望托盤圖標右鍵菜單可以適配深色主題
![image](https://github.com/user-attachments/assets/b0241ec3-ec41-4772-9853-ac8ccdf4e1b4)

### 建议实现 / Suggested implements

托盤圖標右鍵菜單隨系統變更淺色/深色

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.6.0

### 是否为 Pre-release / Is pre-release version

否

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
tauri的tray Windows实现没有深色，建议到tauri官方进行反馈

**Comment by greenhat616** [comment]
muda 支持了深色，但是这只在 v2 可用。tauri v1 算是被彻底放弃了，哪怕在 v2 没有发行的阶段。

**Comment by greenhat616** [comment]
https://github.com/libnyanpasu/clash-nyanpasu/issues/627#issuecomment-2002379573
