### ISSUE TITLE
使用 JavaScript 代理链报错

### ISSUE THREAD

**Issue by EricWangQvQ** [libnyanpasu/clash-nyanpasu#1509]
### 复现步骤 / Step to reproduce

配置文件中存在特殊字符时

### 预期行为 / Expected behaviour

正常解析

### 实际行为 / Actual Behaviour

猜测在解析为 json 时报错

### 应用日志 / App logs

{"timestamp":"2024-09-05T13:31:54.142379Z","level":"ERROR","fields":{"message":"builtin script error `JsNativeError(JsNativeError { kind: Syntax, message: \"control character (\\\\u0000-\\\\u001F) found while parsing a string at line 3472 column 45\", cause: None, .. })`","log.target":"app","log.module_path":"clash_nyanpasu::enhance","log.file":"tauri/src/enhance/mod.rs","log.line":134},"target":"app","filename":"tauri/src/enhance/mod.rs","line_number":134}

### 环境信息 / Environment information

M1， MacOS 15， Clash Nyanpasu：v1.6.1-alpha+2fb93fa

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
请提供 Profile 方便测试

**Comment by ericwang-wsq** [comment]
@greenhat616 
<img width="687" alt="image" src="https://github.com/user-attachments/assets/efe2b027-2cbe-4ca7-a519-3af0e396cace">

proxies:
- name: "[Trojan]\t[倍率:0.8]"
  type: trojan
  server: cdd
  port: 4701
  password: cdd
  sni: cdd
  udp: true

对该配置文件启用 JavaScript 类型的代理链时会报错

**Comment by greenhat616** [comment]
稍晚请尝试一下最新的开发版。
https://github.com/libnyanpasu/clash-nyanpasu/actions/runs/10731514751

**Comment by EricWangQvQ** [comment]
好了，大佬🐂🍺
