### ISSUE TITLE
优化空闲状态下 webview2 的性能 (cpu 占用)

### ISSUE THREAD

**Issue by ShenHongFei** [libnyanpasu/clash-nyanpasu#1515]
### 我希望在开启 webview2 界面的情况下（前台、后台显示或点击最小化按钮隐藏到任务栏，不是关闭界面最小化到托盘），不要持续占用 3% 左右的 cpu 和 5% 左右的 gpu
![image](https://github.com/user-attachments/assets/6a1fd0eb-f00f-4d76-8fa7-ac4013dc8a80)

### 以同样是 webview2 实现的 clash verge rev 对比，clash verge rev 只占用了 1% 不到的 cpu 和 1% 左右的 gpu, 在我可以接受的范围内
![image](https://github.com/user-attachments/assets/33bcbd05-99aa-4df2-8b17-d394726852dd)

### 再对比 clash for windows.exe 这个资源占用甚至更低，称得上低碳环保
![image](https://github.com/user-attachments/assets/4e17045b-2bd3-40f5-a1b6-bdbf8642e851)

### 建议实现 / Suggested implements

前端界面的实现中去掉一些轮询的逻辑？或者降低频率？
做一些 benchmark，或者打点计时，看看时间处理时间花费在哪里

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.6.0

### 是否为 Pre-release / Is pre-release version

否

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by ShenHongFei** [comment]
### clash verge rev 关闭流量图显之后，能做到基本零占用，舒服了
![image](https://github.com/user-attachments/assets/3f05a9f8-5cf3-4c44-902c-ae28be259d0b)

**Comment by NalCol** [comment]
![image](https://github.com/user-attachments/assets/619ee852-d827-4897-9e99-910c4b470acd)
这是我笔记本在前台挂着的占用，基本都在1%左右。
![image](https://github.com/user-attachments/assets/98c71df4-e9ef-4e5d-8e13-4bdda802359b)
拉大一点窗口会变大，但也能在接受范围（2%）左右。
后台更低，大多数时间<1%
至于概览界面的一堆动态图表嘛，确实吃资源（
所以我选择直接关掉主窗口，Webview2直接不用占资源（
~~不知道任务管理器和你这个软件的数据能不能准确对应，仅供参考~~

**Comment by ShenHongFei** [comment]
别的程序都不占 CPU，就它占，排第一了，所以看着很显眼。2% 很多了，相当于一直是在进行计算，窗口开着可以按快捷键（我这里是 ctrl + win + s) 直接切换到这个窗口，看看状态
clash verge rev 前台都基本上是 0%，不过要在配置中关闭流量图显
![image](https://github.com/user-attachments/assets/8ed6a6a0-689e-49ce-a612-df670e9e0b71)

**Comment by keiko233** [comment]
tracked on https://github.com/libnyanpasu/clash-nyanpasu/issues/1484#issuecomment-2325040703

**Comment by qxdxx** [comment]
这个软件可以在ubuntu1804上使用吗？
