### ISSUE TITLE
卸载后配置文件仍然存在

### ISSUE THREAD

**Issue by lemonicy** [libnyanpasu/clash-nyanpasu#1518]
### 复现步骤 / Step to reproduce

卸载后重装即可触发，复现率 100%

### 预期行为 / Expected behaviour

卸载时应删除所有残留文件

### 实际行为 / Actual Behaviour

卸载后只有安装目录被删除，以下目录都没有删除：
- C:\Users\用户名\AppData\Local\Clash Nyanpasu
- C:\Users\用户名\AppData\Roaming\Clash Nyanpasu\config（这个应该是关键 ）

### 应用日志 / App logs

卸载软件应该不会写在日志里吧，干脆不贴了

### 环境信息 / Environment information

> ----------- System -----------
> OS: Windows 11 Pro 22631
> Arch: x86_64
> ----------- Device -----------
> CPU: 13th Gen Intel(R) Core(TM) i7-13700K @ 3.40GHz x 24
> Memory: 63.77 GiB
> ----------- Core -----------
> mihomo-alpha: `Mihomo Meta alpha-faaa90f windows amd64 with go1.23.0 Tue Sep  3 09:58:22 UTC 2024 Use tags: with_gvisor`
> mihomo: `Mihomo Meta v1.18.8 windows amd64 with go1.23.0 Mon Sep  2 08:37:40 UTC 2024 Use tags: with_gvisor`
> clash: `Clash n2023-09-05-gdcc8d87 windows amd64 with go1.21.0 Tue Sep  5 14:32:57 UTC 2023`
> clash-rs: `clash-rs 0.3.1`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 1.6.1-alpha+a3f3c5f
> Commit Hash: a3f3c5f9c9205a437e4720020a36f047ed18873c
> Commit Author: renovate[bot]
> Commit Date: 2024-09-06T22:34:40.000Z
> Build Date: 2024-09-07T00:43:25.979Z
> Build Profile: Nightly
> Build Platform: x86_64-pc-windows-msvc
> Rustc Version: rustc 1.83.0-nightly (9c01301c5 2024-09-05)
> Llvm Version: 19.1
> 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
请尝试一下最新的开发版，https://github.com/libnyanpasu/clash-nyanpasu/actions/runs/10749327897。

**Comment by lemonicy** [comment]
> 请尝试一下最新的开发版，[https://github.com/libnyanpasu/clash-nyanpasu/actions/runs/10749327897。](https://github.com/libnyanpasu/clash-nyanpasu/actions/runs/10749327897%E3%80%82)

最新版本确认已解决
