### ISSUE TITLE
在属性-兼容性中勾选以管理员身份启动后，开机自启动失效

### ISSUE THREAD

**Issue by 68star89** [libnyanpasu/clash-nyanpasu#1522]
### 复现步骤 / Step to reproduce

1.在属性-兼容性中勾选以管理员身份启动
2.软件-设置勾选开机自启与静默启动
3.重新开机后喵帕斯未能启动

### 预期行为 / Expected behaviour

正常自启动

### 实际行为 / Actual Behaviour

如上

### 备注 / Addition details

目前的问题在于，如果不让喵帕斯以管理员身份启动，那么软件tun模式无法正常运行（哪怕状态栏图标可以变蓝），以管理员身份启动又无法静默自启

### 环境信息 / Environment information

> ----------- System -----------
> OS: Windows 11 Home China 22631
> Arch: x86_64
> ----------- Device -----------
> CPU: AMD Ryzen 7 7840H  w/ Radeon 780M Graphics      @ 2.52GHz x 16
> Memory: 31.31 GiB
> ----------- Core -----------
> clash: `Clash n2023-09-05-gdcc8d87 windows amd64 with go1.21.0 Tue Sep  5 14:32:57 UTC 2023`
> mihomo-alpha: `Mihomo Meta alpha-ade4234 windows amd64 with go1.23.1 Sat Sep  7 12:25:36 UTC 2024 Use tags: with_gvisor`
> clash-rs: `clash-rs 0.3.1`
> mihomo: `Mihomo Meta v1.18.8 windows amd64 with go1.23.0 Mon Sep  2 08:37:40 UTC 2024 Use tags: with_gvisor`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 1.6.1
> Commit Hash: 07312702907e7cb459427f41dc7fd2b1bd270e6b
> Commit Author: github-actions[bot]
> Commit Date: 2024-09-07T16:09:54.000Z
> Build Date: 2024-09-07T16:58:22.032Z
> Build Profile: Release
> Build Platform: x86_64-pc-windows-msvc
> Rustc Version: rustc 1.83.0-nightly (26b5599e4 2024-09-06)
> Llvm Version: 19.1
> 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [ ] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
请使用服务模式替代以管理员身份启动 UI

**Comment by 68star89** [comment]
通过服务模式自启动的喵帕斯在tun模式上存在问题，具体表现为控制面板中不显示meta网卡

**Comment by greenhat616** [comment]
服务模式的问题请新开 issue 并提交应用日记和服务日记以便分析。此问题已通过 8cf7b3148b6f0567c4b76cc079f671e17268b723 修复。

**Comment by greenhat616** [comment]
https://github.com/libnyanpasu/clash-nyanpasu/actions/runs/10756264566 稍晚可以通过开发板测试。
