### ISSUE TITLE
每次打开软件，左侧菜单栏都被会重置

### ISSUE THREAD

**Issue by 0xCandy** [libnyanpasu/clash-nyanpasu#1523]
### 需求 / Requirement

我的电脑是Win10。软件版本1.6.1

当我把左侧菜单栏的宽度缩小时（如下图1所示），关闭再重新打开软件，菜单栏的宽度会被重置（图2所示）！这非常影响使用体验。
![image](https://github.com/user-attachments/assets/babe3df5-6545-4a6c-866d-2ed803a0bd1e)

此外，我希望每次打开软件显示我上次关闭时的界面，例如“代理”界面，这样我可以打开即选择节点，而不用事先从初始的“概览”界面切换到“代理”界面，这样的使用体验会舒畅很多。
![image](https://github.com/user-attachments/assets/09614c41-eef3-47aa-a897-48b39b3b4e04)

### 建议实现 / Suggested implements

未知

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.6.1

### 是否为 Pre-release / Is pre-release version

否

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [x] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by NalCol** [comment]
关掉主界面后丢失全部操作确实非常影响体验，应该做一个参数的持久化保留😂
虽然是因为关掉主界面后 Edge Webview2 直接停了，后台运行资源友好 ;)

**Comment by greenhat616** [comment]
等实现后会 backport 到 v1.6.2 作为补丁修复发布的

**Comment by keiko233** [comment]
fix on https://github.com/libnyanpasu/clash-nyanpasu/commit/48bf4779da74b0e8ee69069c9666e7fc01d9ba5c

**Comment by keiko233** [comment]
> 当前该问题已经可以通过设置里面的按钮《图标导航栏》进行控制，但目前有个小问题就是，已经锁死图标导航栏和带文字的导航栏，以前是手动调整的，建议做成自动模式和手动模式，自动模式可以分图标导航栏和带文字的导航栏，手动模式可以进行导航栏宽度的调整。

由于我们这边存在多种导航栏样式，导致代码变得些许复杂，从而带来更多的问题，目前我们没法很好的去解决，比如隐藏侧边是卸载dom，卸载dom后resize bar就不认挂载回来的dom了，没有很好的方法去主动控制dom元素大小，也就是侧边栏宽度，在我们完成解决方案之前先采用比较稳定的方法
