### ISSUE TITLE
托盘中代理模式和UI界面中存在不一致的情况

### ISSUE THREAD

**Issue by Soniceso** [libnyanpasu/clash-nyanpasu#1525]
### 复现步骤 / Step to reproduce

大致在托盘或者打开软件更改代理模式时，比如将代理模式改为直连模式，在UI界面操作后，实际变为了直连模式，但是托盘中的状态还是代理模式，同样引发的问题还有在托盘中勾选直连模式关闭软件后，再次启动后托盘中会一保持无配置文件的状态，但是实际打开UI界面可以看到配置文件被正常加载也可以正常使用。
![image](https://github.com/user-attachments/assets/da970e07-cbc9-4777-b51c-3354bbb3d6f7)

### 预期行为 / Expected behaviour

无论哪边更改另一边也会更新当前状态

### 实际行为 / Actual Behaviour

如上

### 环境信息 / Environment information

win11；1.6.1；1.18.8

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by ShenHongFei** [comment]
好像我也遇到过一样的问题

**Comment by greenhat616** [comment]
已在开发构建中修复，日后会移植到 1.6.2 发布中
