### ISSUE TITLE
使用Clash Premium内核时tun模式失效

### ISSUE THREAD

**Issue by 68star89** [libnyanpasu/clash-nyanpasu#1526]
### 复现步骤 / Step to reproduce

在开启管理员身份时使用clash pre内核

### 预期行为 / Expected behaviour

虚拟网卡正常生成，代理有效

### 实际行为 / Actual Behaviour

状态栏图标变蓝，但实际并未生效

### 环境信息 / Environment information

> ----------- System -----------
> OS: Windows 11 Home China 22631
> Arch: x86_64
> ----------- Device -----------
> CPU: AMD Ryzen 7 7840H  w/ Radeon 780M Graphics      @ 2.52GHz x 16
> Memory: 31.31 GiB
> ----------- Core -----------
> clash: `Clash n2023-09-05-gdcc8d87 windows amd64 with go1.21.0 Tue Sep  5 14:32:57 UTC 2023`
> clash-rs: `clash-rs 0.3.1`
> mihomo: `Mihomo Meta v1.18.8 windows amd64 with go1.23.0 Mon Sep  2 08:37:40 UTC 2024 Use tags: with_gvisor`
> mihomo-alpha: `Mihomo Meta alpha-ade4234 windows amd64 with go1.23.1 Sat Sep  7 12:25:36 UTC 2024 Use tags: with_gvisor`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 1.6.1
> Commit Hash: 07312702907e7cb459427f41dc7fd2b1bd270e6b
> Commit Author: github-actions[bot]
> Commit Date: 2024-09-07T16:09:54.000Z
> Build Date: 2024-09-07T16:58:22.032Z
> Build Profile: Release
> Build Platform: x86_64-pc-windows-msvc
> Rustc Version: rustc 1.83.0-nightly (26b5599e4 2024-09-06)
> Llvm Version: 19.1
> 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [ ] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
请提供应用日记，如果使用服务模式请提供服务模式的日记。
注：服务模式日记在 `%PROGRAMDATA%/nyanpasu-service/data/logs` 目录下

**Comment by 68star89** [comment]
> 请提供应用日记，如果使用服务模式请提供服务模式的日记。 注：服务模式日记在 `%PROGRAMDATA%/nyanpasu-service/data/logs` 目录下

请问对日志等级有要求吗？我后续试着复现一下

**Comment by greenhat616** [comment]
最好是 TRACE 级别

**Comment by 68star89** [comment]
[nyanpasu-service.2024-09-09.app.log](https://github.com/user-attachments/files/16930309/nyanpasu-service.2024-09-09.app.log)
复现时发现当前在clash pre内核下点击tun模式按键会直接弹出报错

**Comment by greenhat616** [comment]
看起来像是 `wintun.dll` 不存在造成的，你的数据目录下有 `wintun.dll` 吗？

**Comment by 68star89** [comment]
> 看起来像是 `wintun.dll` 不存在造成的，你的数据目录下有 `wintun.dll` 吗？

没有

**Comment by greenhat616** [comment]
可以先手动复制一份过去。在程序安装目录下的 `resources` 目录有。

**Comment by 68star89** [comment]
> 安装目录下的 `resources` 目录

安装目录下的 resources 目录没有发现wintun.dll，只有
Country.mmdb
enableLoopback.exe
geoip.dat
geosite.dat
四个文件

**Comment by 68star89** [comment]
> 😦该不会被你的杀软删掉了吧

火绒的隔离区没见有东西啊😦

**Comment by greenhat616** [comment]
https://www.wintun.net 这里下一份复制进去看看吧

**Comment by 68star89** [comment]
> https://www.wintun.net 这里下一份复制进去看看吧

使用amd64的wintun.dll可以正常激活clash pre的tun模式，所以是当前的喵帕斯版本没有在数据目录生成wintun.dll的原因吗？

**Comment by greenhat616** [comment]
> > https://www.wintun.net 这里下一份复制进去看看吧
> 
> 使用amd64的wintun.dll可以正常激活clash pre的tun模式，所以是当前的喵帕斯版本没有在数据目录生成wintun.dll的原因吗？

```json
{"timestamp":"2024-09-09T12:13:59.780645Z","level":"ERROR","fields":{"message":"failed to copy resources 'wintun.dll', 系统找不到指定的文件。 (os error 2)","log.target":"app","log.module_path":"clash_nyanpasu::utils::init","log.file":"tauri\\src\\utils\\init\\mod.rs","log.line":194},"target":"app","filename":"tauri\\src\\utils\\init\\mod.rs","line_number":194}
```

不知道为什么你的安装目录里面 `wintun.dll` 不存在，所以自然不能拷贝过去

**Comment by greenhat616** [comment]
经调查，是 CI 服务出了问题。最新开发版已修复，这几天有空 patch 一下 1.6.1，重新上新的二进制包
