### ISSUE TITLE
无法确定 Linux 下的“系统代理”的行为

### ISSUE THREAD

**Issue by goddaneel** [libnyanpasu/clash-nyanpasu#1531]
### 复现步骤 / Step to reproduce

1. 普通用户权限下正常启动nyanpasu
2. 打开“系统代理”开关
3. 检查系统代理配置

### 预期行为 / Expected behaviour

环境变量、dconf、pac或者其他代理相关配置发生改变

### 实际行为 / Actual Behaviour

无法确定相关代理是否发生改变，可以确定：
1. 系统环境变量未发生改变
2. dconf相关键值未发生改变

### 环境信息 / Environment information

软件版本：1.6.1（deb）
操作系统：debian 12
硬件设备：amd64
桌面环境：kde

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
kde 下应使用 `kwriteconfig`

**Comment by greenhat616** [comment]
我再次确认了一下，行为符合预期。
![图片](https://github.com/user-attachments/assets/fcdf8a18-6a5e-49b3-8455-f5147b422f4d)
