### ISSUE TITLE
Win11， Tun 模式 重启后无法启动

### ISSUE THREAD

**Issue by Jaydar** [libnyanpasu/clash-nyanpasu#1545]
### 复现步骤 / Step to reproduce

 重启电脑以后， 网络适配器中的 Meta 消失了 。
需要重新安装 才会出现
![image](https://github.com/user-attachments/assets/7908358a-7fbc-41ca-8b4b-df6f8b7d3ace)1

### 预期行为 / Expected behaviour

11

### 实际行为 / Actual Behaviour

1

### 备注 / Addition details

1111

### 环境信息 / Environment information

Windows 11  
Clash Nyanpasu 1.6.1
Mihomo 1.18.8

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly

**Comment by Jaydar** [comment]
这是一个普遍现象， 随便找个windows 都会有这个问题 。
