### ISSUE TITLE
应用位于前台时没有显示Menu栏，点击关闭之后没有Dock图标，也无法从 Dock 被唤醒

### ISSUE THREAD

**Issue by o8x** [libnyanpasu/clash-nyanpasu#158]
### 复现步骤 / Step to reproduce

1. 双击启动，使应用处于前台

### 预期行为 / Expected behaviour

像浏览器或其他应用一样，拥有Menu
关闭后，有Dock图标，重新点击Dock图标可以重新唤起应用

![image](https://github.com/keiko233/clash-nyanpasu/assets/20666153/38758bf6-ba45-480f-b071-93fe68953c5c)

### 实际行为 / Actual Behaviour

没有Menu

不能唤起应用

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.1

### 是否为 Pre-release / Is pre-release version

34cb796

### 操作系统及版本 / OS version

macos 14

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by Jancat** [comment]
确实，没有 Dock 图标不太方便，主面板被其它窗口覆盖后无法通过 command + tab 切换回来，只能重新在 menu 栏上点 打开面板

**Comment by greenhat616** [comment]
Blocked by https://github.com/tauri-apps/tauri/issues/2358

需要寻找其他 workaround

**Comment by greenhat616** [comment]
Nope. And tauri v2 rc don't provide a method to solve this issue.

we can't dive into the `tao` internal interface, so that we can not change the policy dynamic, even via `cocoa` api.

It just the tauri limit, not the program limit. We just need wait the fucking tauri team fix it.

**Comment by ayangweb** [comment]
我以为是在 tauri 的 issue 评论区发言，还特地机翻了一下😂

我一直在用 cocoa 和 objc 尝试解决问题，可怎么都搞不定。看样子想让 tauri v1 支持这个功能有点悬，有点想放弃使用 tauri 了！

**Comment by greenhat616** [comment]
@ayangweb 好像不管 `tao` 直接操作 ActivityPolicy 就好了。
https://github.com/libnyanpasu/clash-nyanpasu/commit/cdf2ec1a60ff4bdf8733f9b7d1a8fc66c905ea47

具体是否有效果得看反馈了。

**Comment by ayangweb** [comment]
> @ayangweb 好像不管 `tao` 直接操作 ActivityPolicy 就好了。 [cdf2ec1](https://github.com/libnyanpasu/clash-nyanpasu/commit/cdf2ec1a60ff4bdf8733f9b7d1a8fc66c905ea47)
> 
> 具体是否有效果得看反馈了。

不过我主要想解决的是从 dock 栏唤醒窗口🫣

**Comment by ayangweb** [comment]
> @ayangweb 好像不管 `tao` 直接操作 ActivityPolicy 就好了。 [cdf2ec1](https://github.com/libnyanpasu/clash-nyanpasu/commit/cdf2ec1a60ff4bdf8733f9b7d1a8fc66c905ea47)
> 
> 具体是否有效果得看反馈了。

这个动态显隐的效果在我的项目中无效🫣
