### ISSUE TITLE
热键无法设置 "\" 

### ISSUE THREAD

**Issue by DBeidachazi** [libnyanpasu/clash-nyanpasu#1607]
### 复现步骤 / Step to reproduce

在热键设置中，无法将 "\\" 设置为热键

### 预期行为 / Expected behaviour

设置前: ![image](https://github.com/user-attachments/assets/c5cb3592-e8c6-4040-9c2f-b5c5048c0b47)

### 实际行为 / Actual Behaviour

重新打开: 
![image](https://github.com/user-attachments/assets/d4a0a697-6e0e-4b40-af90-cb449ed5c84b)

配置文件中手动修改也无法生效

### 环境信息 / Environment information

> ----------- System -----------
> OS: Windows 10 Enterprise LTSC 2021 19044
> Arch: x86_64
> ----------- Device -----------
> CPU: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz @ 2.30GHz x 16
> Memory: 31.85 GiB
> ----------- Core -----------
> mihomo: `Mihomo Meta v1.18.8 windows amd64 with go1.23.0 Mon Sep  2 08:37:40 UTC 2024 Use tags: with_gvisor`
> clash: `Clash n2023-09-05-gdcc8d87 windows amd64 with go1.21.0 Tue Sep  5 14:32:57 UTC 2023`
> mihomo-alpha: `Mihomo Meta alpha-a08aa10 windows amd64 with go1.23.1 Thu Sep 19 10:43:08 UTC 2024 Use tags: with_gvisor`
> clash-rs: `clash-rs 0.4.0`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 1.6.1
> Commit Hash: 14b04075d8f256b1a4ee0a704f985d8f654f2453
> Commit Author: Jonson Petard
> Commit Date: 2024-09-10T03:59:13.000Z
> Build Date: 2024-09-10T04:55:14.413Z
> Build Profile: Release
> Build Platform: x86_64-pc-windows-msvc
> Rustc Version: rustc 1.83.0-nightly (c2f74c3f9 2024-09-09)
> Llvm Version: 19.1
> 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
有尝试过最新的 2.0 开发版么？此设置有在 2.0 中修复吗？

**Comment by DBeidachazi** [comment]
> 有尝试过最新的 2.0 开发版么？此设置有在 2.0 中修复吗？

刚尝试了2.0开发板，现在又有不一样的行为了。

1. 我在设置切换系统代理时，按键是可以设置为"\\"，但是所有的热键仅会在按键按压时间内触发，在按压结束后恢复按压前的状态。

2. 使用热键设置打开关闭面板时，出现了报错
![image](https://github.com/user-attachments/assets/decbe2cf-1a48-4fe3-842f-2d3a8e03d597)

3. 设置热键时大概率出现清除先前热键设置的问题，没找到具体的触发条件。

**Comment by greenhat616** [comment]
2 那个问题是上游的问题：https://github.com/tauri-apps/tauri/issues/10546

剩下的我抽空调查一下

**Comment by greenhat616** [comment]
试一下今早的开发版本有没有这个问题了。
https://github.com/libnyanpasu/clash-nyanpasu/commit/186a65e65dcf2ebf2da9d94d07bb3cd862c4075f

**Comment by DBeidachazi** [comment]
> 试一下今早的开发版本有没有这个问题了。 [186a65e](https://github.com/libnyanpasu/clash-nyanpasu/commit/186a65e65dcf2ebf2da9d94d07bb3cd862c4075f)

用到现在目前没有发现问题
