### ISSUE TITLE
软件关闭窗口时崩溃

### ISSUE THREAD

**Issue by 114514test01** [libnyanpasu/clash-nyanpasu#1610]
### 复现步骤 / Step to reproduce

1.关闭软件前台窗口

### 预期行为 / Expected behaviour

它应该关闭窗口

### 实际行为 / Actual Behaviour

实际上他弹出多个错误信息窗口
![屏幕截图 2024-09-21 233559](https://github.com/user-attachments/assets/07cacc32-e0bc-4f3d-ba85-1b0aa3b8f2d8)

### 应用日志 / App logs

[2024-09-21-log.zip](https://github.com/user-attachments/files/17084669/2024-09-21-log.zip)

### 环境信息 / Environment information

Windows 11 专业工作站预览版 Build 27695 版本 内核：Clash Premium n2023-09-05 Clash版本 v2.00 alpha

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [ ] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
请关注这个 issue：https://github.com/libnyanpasu/clash-nyanpasu/issues/1544，这个是上游的问题，且上游对此问题修复并不积极。因此我们尝试显示忽略此崩溃（似乎忽略并不会造成任何问题？）

**Comment by greenhat616** [comment]
上游 issue 地址：https://github.com/tauri-apps/tauri/issues/10546

**Comment by greenhat616** [comment]
https://github.com/libnyanpasu/clash-nyanpasu/commit/8412a6e61bff5ed520d4dc9b4cc9cc9f7d5c1910
