### ISSUE TITLE
pnpm build  error[E0554]

### ISSUE THREAD

**Issue by wahello** [libnyanpasu/clash-nyanpasu#1646]
### 复现步骤 / Step to reproduce

1. clone repo.
2. `pnpm i`
3. `pnpm build`

### 预期行为 / Expected behaviour

build successful

### 实际行为 / Actual Behaviour

build failed. 

### 应用日志 / App logs

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> boa_utils/src/lib.rs:1:1
  |
1 | #![feature(trait_alias)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> boa_utils/src/lib.rs:2:1
  |
2 | #![feature(auto_traits)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^

error[E0554]: `#![feature]` may not be used on the stable release channel
 --> boa_utils/src/lib.rs:3:1
  |
3 | #![feature(negative_impls)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0554`.
error: could not compile `boa_utils` (lib) due to 3 previous errors
       Error failed to build app: failed to build app
 ELIFECYCLE  Command failed with exit code 1.
```

### 环境信息 / Environment information

os: macos 14.5
rustc 1.81.0 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
**目前项目只支持 nightly 工具链。**
不要使用 brew 提供的 `rustc` 或 `cargo`，改用 `rustup` 管理工具链。
