### ISSUE TITLE
[Bug] Settings 中 Layout Settings 弹出窗口中的下方的按钮不应该是 Cancel, 而是 Back

### ISSUE THREAD

**Issue by foobarjohnny** [LibNyanpasu/clash-nyanpasu#165]
### 复现步骤 / Step to reproduce

点击 Settings 中 Layout Settings, 会弹出窗口.

### 预期行为 / Expected behaviour

其中的下方的按钮应该是 Back

### 实际行为 / Actual Behaviour

其中的下方的按钮却是 Cancel

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.1

### 是否为 Pre-release / Is pre-release version

No

### 操作系统及版本 / OS version

Windows 10

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
fixed on 1.6.x
