### ISSUE TITLE
1.6.1 规则模式 不能选择其他代理，只能是第一个

### ISSUE THREAD

**Issue by wolfcdd** [libnyanpasu/clash-nyanpasu#1677]
### 复现步骤 / Step to reproduce

https://github.com/user-attachments/assets/a83db7f7-2d78-4c29-896a-491423f1eaf9

### 预期行为 / Expected behaviour

跟随鼠标点击选中

### 实际行为 / Actual Behaviour

鼠标点任意一个，永远选中的第一个

### 应用日志 / App logs

[2024-10-02-log.zip](https://github.com/user-attachments/files/17218910/2024-10-02-log.zip)

### 备注 / Addition details

无

### 环境信息 / Environment information

win11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
请上传 Profile

**Comment by wolfcdd** [comment]
> 请上传 runtime profile，或者直接截图 runtime profile 的 proxy-group 区

![image](https://github.com/user-attachments/assets/3780f682-365e-4e24-acad-4261aed1e832)

**Comment by wolfcdd** [comment]
> TRACE

[2024-10-05-log.zip](https://github.com/user-attachments/files/17264875/2024-10-05-log.zip)
![image](https://github.com/user-attachments/assets/c1d5b91e-6b4f-4229-a377-b0a2c0392ecf)
![image](https://github.com/user-attachments/assets/8afd1d9f-8bfe-40c5-ba4a-69159a91033e)
开发版已经试了，一样的问题。

**Comment by greenhat616** [comment]
可以考虑将 Profile 直接发给我们的机器人，之后有空可以尝试复现一下：https://t.me/nyanpasu_message_bot
