### ISSUE TITLE
window 下 代理过多，导致退出键得拖动好久

### ISSUE THREAD

**Issue by BZBY** [libnyanpasu/clash-nyanpasu#1710]
### 需求 / Requirement

任务栏，就是右下角，那里的小图标，由于我代理服务器过多，右键就会有大概30多个服务器选择，然后我就得一直往下拖才能找到退出键，要不这里搞个二级目录？。。。主要问题是我window下的使用感觉巨卡，UI界面，amd和inter的CPU都是卡，应该是window的问题。==。不知道其他人是不是ui界面也卡

### 建议实现 / Suggested implements

右下角，那里的小图标，由于我代理服务器过多，右键就会有大概30多个服务器选择，然后我就得一直往下拖才能找到退出键，要不这里搞个二级目录？

### Clash Nyanpasu 版本号 / Clash Nyanpasu

2.0.1

### 是否为 Pre-release / Is pre-release version

ae3da07

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
![图片](https://github.com/user-attachments/assets/f0db900c-e1f9-4d87-9708-db56eec81245)
![图片](https://github.com/user-attachments/assets/f56d7c57-31bb-4676-8c76-3cb794415795)

1.6.0 里已经支持。
