### ISSUE TITLE
在windows 系统下，未关闭 clash 情况下重启或关机导致 WSL 异常

### ISSUE THREAD

**Issue by ElvisWai** [libnyanpasu/clash-nyanpasu#1721]
### 复现步骤 / Step to reproduce

1. 在windows 系统下，未关闭 clash 情况下重启或关机
2. 重启/开机后，使用 WSL 会导致 异常，原因为：注册列表的 IPv6 值被修改，异常退出后无法重置为:0
3. 修复，参考：https://github.com/microsoft/WSL/issues/11002

### 预期行为 / Expected behaviour

异常退出后，重新打开应用并打开代理--关闭代理后，应该把 IPv6 恢复，不影响 WSL 工作

### 实际行为 / Actual Behaviour

在windows 系统下，未关闭 clash 情况下重启或关机导致 WSL 异常

### 备注 / Addition details

暂无

### 环境信息 / Environment information

系统：Windows 11
Clash Nyanpasu :  1.6.1
Clash 内核:  v1.18.8 Meta 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
Nyanpasu 内部配置是怎样的？启用了系统代理了么？

本地环境也是 WSL2 + Mirrored。在当前使用环境下，未碰到此问题。

**Comment by ElvisWai** [comment]
开启了系统代理 + 规则模式（规则主要是本地域名不走代理）
配置如下：
![image](https://github.com/user-attachments/assets/767ae347-0345-4bea-94c4-f3c11bbfb1e7)

不关闭系统代理的情况下重启电脑试试，重启后使用WSL

**Comment by greenhat616** [comment]
无法复现此问题
![图片](https://github.com/user-attachments/assets/8d555c5e-48f5-4816-965b-4c29c7a9b63d)
![图片](https://github.com/user-attachments/assets/62e3f2b1-5877-4e85-81a3-fe652840af93)
![图片](https://github.com/user-attachments/assets/3bc6c96f-67f1-42aa-be64-3b1f281b6dd9)
![图片](https://github.com/user-attachments/assets/37e03b72-d6d4-4b34-a3ed-6a8c1520f8f0)

**Comment by ElvisWai** [comment]
![image](https://github.com/user-attachments/assets/65248600-32b5-4dc8-bee8-8b2b1afb01e9)
本地能重复复现🤔

**Comment by greenhat616** [comment]
我观察了一下那个 issue 的上下文：
> Location: HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters
> Name: DisabledComponents
> Type: REG_DWORD
> Min Value: 0x00 (default value)
> Max Value: 0xFF (IPv6 disabled)
提及修改了 DisabledComponents 的值, 但实际上我们通过系统调用修改代理服务器,不涉及此注册表才对.
这是操作系统代理的源码: https://github.com/zzzgydi/sysproxy-rs/blob/main/src/windows.rs

**Comment by ElvisWai** [comment]
我查看相关的issues 是 VPN 不支持 IP6 代理，因此在开启代理后会因为网络修改而自动修改注册列表。该问题你可以通过查看注册表中该值去验证，在代理开启状态下，10进制为 255。
其次，在设置中 IP6 为打开状态的情况下【重启】后，该值处于无法选中的情况
![image](https://github.com/user-attachments/assets/2d8041a8-a250-4be3-94f2-c11f33902a87)
