### ISSUE TITLE
Unable to read/create profile

### ISSUE THREAD

**Issue by 3gf8jv4dv** [libnyanpasu/clash-nyanpasu#1743]
### 复现步骤 / Step to reproduce

🟡 Mouse Click

<details>
<summary>Preview</summary>

![nyanpasu-profile-issue](https://github.com/user-attachments/assets/4d3dd8de-7f2e-452e-b88b-7eb913d67525)

</details>

### 预期行为 / Expected behaviour

Existing profiles can be read and new profiles can be created.

### 实际行为 / Actual Behaviour

No profile was read, and no response was received when creating a profile.

### 备注 / Addition details

I have not encountered this problem when using this build: https://github.com/libnyanpasu/clash-nyanpasu/actions/runs/11226302246

This build starts having problems: https://github.com/libnyanpasu/clash-nyanpasu/actions/runs/11245967125

**EDIT:** Copied the wrong URL, edited.

### 环境信息 / Environment information

[Environment information](https://gist.github.com/3gf8jv4dv/acbabb05c6c5196407ca0289cf87c197)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
It might be fixed by 4b6eb3536b1f9e775dd609035b7bfa2e5ceabde, 90bbcf229dae0630f228aae5d34c5c23c32e59d8 and 4b6eb3536b1f9e775dd609035b7bfa2e5ceabdef

**Comment by greenhat616** [comment]
We have do a huge refactor on Profiles, so the issue should be fixed by a migration.

The null in chain value is unexpected, sometimes, it could interrupt our program logic. That's why we refactored it with builder pattern, and better ManagedState lifecycle.

**Comment by greenhat616** [comment]
I have drafted a migration for `chain` field on `profile.yaml`: https://github.com/libnyanpasu/clash-nyanpasu/commit/8d50f0c71484dc234d4937c4992b7a40721dce79

It should fix this issue.

If you continue to face with this issue, please open a new issue. Thank you.
