### ISSUE TITLE
Mihomo无限填充内存

### ISSUE THREAD

**Issue by 114514test01** [libnyanpasu/clash-nyanpasu#1751]
### 复现步骤 / Step to reproduce

1.打开Tun模式
问题就开始了
![屏幕截图 2024-10-11 193836](https://github.com/user-attachments/assets/5b9d8d10-660e-44b9-8f69-fa9e743a3f36)

### 预期行为 / Expected behaviour

只会开个Tun模式，至少肉眼可见的什么也不会发生

### 实际行为 / Actual Behaviour

无限填充内存了，蹦出来一万多个活动连接
![屏幕截图 2024-10-11 193836](https://github.com/user-attachments/assets/7818ce3c-0d3d-4e72-ba45-8a1d49e77a71)

### 应用日志 / App logs

[2024-10-11-log.zip](https://github.com/user-attachments/files/17342193/2024-10-11-log.zip)

### 备注 / Addition details

我原本寻思着把Tun模式关了可以，结果没想到，这东西**关不掉啊，点一下Tun模式就开始转圈圈，更重要的是任务管理器结束还拒绝访问啊，cmd也干不掉
![屏幕截图 2024-10-11 194200](https://github.com/user-attachments/assets/b79cefd2-daf5-4164-9202-7dd54353e751)
![屏幕截图 2024-10-11 194317](https://github.com/user-attachments/assets/9e30dbac-2fa9-472d-bf1c-4fa4645fc2ec)

### 环境信息 / Environment information

Windows 11 x64 bit (Preview 27718) Clash nyanpasu Alpha 2.00 ,Mihomo最新版

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
并发链接太多是会这样的，这个是 mihomo 的限制，我们这里没法多做什么。
从服务模式启动可以尝试进程序目录下执行 `./nyanpasu-service rpc stop-core` 看看能不能停止内核。

**Comment by keiko233** [comment]
是否开启了Windows热点，貌似热点+tun会无限回环

**Comment by 114514test01** [comment]
> 是否开启了Windows热点，貌似热点+tun会无限回环

的确
