### ISSUE TITLE
Unable to migrate `config/profiles.yaml` used by older versions

### ISSUE THREAD

**Issue by 3gf8jv4dv** [libnyanpasu/clash-nyanpasu#1760]
### 复现步骤 / Step to reproduce

1. Use an older version (e.g. 1.6.1) and create a profile
2. Replace the executable file with the new version
3. You can notice that the original profiles are not read

*Related discussion: #1743*

### 预期行为 / Expected behaviour

Regardless, old profiles can still be displayed in the new version.

### 实际行为 / Actual Behaviour

Profiles is empty.

### 环境信息 / Environment information

[Environment information](https://gist.github.com/3gf8jv4dv/62fcb1f9effac1e4f605e157aef93126)

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
Is that a clean install in 1.6.1? 
Our migration system will read the `migration.lock` in your config dir, and write the lockfile after committed the migration, which ensures the migrations run only once.

**Comment by greenhat616** [comment]
I figure out why it occurs: I forgot to enable the 200 unit migrations in list. 😢

**Comment by greenhat616** [comment]
it is fixed on latest dev build.

![图片](https://github.com/user-attachments/assets/27ab1d11-5a4b-4997-a4e4-0fa8476d1908)
![图片](https://github.com/user-attachments/assets/20550b36-632b-4702-860a-2099a1c03ce1)
