### ISSUE TITLE
[功能请求] 给 macOS 版添加对 Alt+Tab 快捷键的支持.

### ISSUE THREAD

**Issue by foobarjohnny** [libnyanpasu/clash-nyanpasu#178]
### 需求 / Requirement

本软件的 Windows 版是支持用 Alt+Tab 在 Browser 和 clash-nyanpasu 之间进行切换, 希望 macOS 版也能支持.

### 建议实现 / Suggested implements

Clash for windows 的 macOS 版是支持的, 可以参考一下.

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.1

### 是否为 Pre-release / Is pre-release version

No

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
似乎 v1.6.0 实验性添加的 dock 图标自动显示、隐藏功能可以解决这个问题。请尝试一下，谢谢。

**Comment by foobarjohnny** [comment]
> 似乎 v1.6.0 实验性添加的 dock 图标自动显示、隐藏功能可以解决这个问题。请尝试一下，谢谢。

新版在 dock  后, 支持 ALT+TAB 切换了, 谢谢.

**Comment by foobarjohnny** [comment]
新版在 dock 后, 支持 ALT+TAB 切换了, 谢谢.
