### ISSUE TITLE
[Bug] 启动时, 无法在第2显示器上恢复上次退出时的位置.

### ISSUE THREAD

**Issue by foobarjohnny** [LibNyanpasu/clash-nyanpasu#179]
### 复现步骤 / Step to reproduce

1. 把 clash-nyanpasu  移动到第二显示器的角落
2. 退出后重新启动 clash-nyanpasu 

### 预期行为 / Expected behaviour

clash-nyanpasu  应该还在第2显示器的角落处.

### 实际行为 / Actual Behaviour

clash-nyanpasu  却在第2显示器的正中央.

### 备注 / Addition details

当 clash-nyanpasu  处于第1显示器的角落时, 退出再启动后就可以准确的恢复为还在角落处, 但是对于第2显示器就会出错.
Clash for windows 在第1或第2显示器上都可以准确的恢复位置, 可以参考一下.

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.1

### 是否为 Pre-release / Is pre-release version

No

### 操作系统及版本 / OS version

Windows 10

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
开发版也不能正确记忆吗？

**Comment by foobarjohnny** [comment]
> 开发版也不能正确记忆吗？

昨天提交 Bug 时, 下载了当时最新的开发版, 也不行. 现在去看了一下, 开发版里 Assets 只有源代码, 没有 Windows 安装文件.

**Comment by foobarjohnny** [comment]
> [tauri-apps/tauri#6394 (comment)](https://github.com/tauri-apps/tauri/issues/6394#issuecomment-1456183520)
> 
> 需要手动处理生成的窗口，目前确实还没实现。

了解, 谢谢.

**Comment by foobarjohnny** [comment]
> [tauri-apps/tauri#6394 (comment)](https://github.com/tauri-apps/tauri/issues/6394#issuecomment-1456183520)
> 
> 需要手动处理生成的窗口，目前确实还没实现。

你好, 已经发2个新版本了, 对这个问题的手动解决还没见提上日程啊.

**Comment by 4o3F** [comment]
Fixed in 6a3acb3225ddf600497edeec8871e957bbda2f05
