### ISSUE TITLE
[Feature] 考虑支持 sing-box内核

### ISSUE THREAD

**Issue by ghost** [libnyanpasu/clash-nyanpasu#18]
**Is your feature request related to a problem? Please describe.**
clash上游已经全部停止维护

**Describe the solution you'd like**

考虑支持 sing-box内核

**Describe alternatives you've considered**

**Additional context**

**Comment by istek** [comment]
同意，或者支持xray也可以

**Comment by keiko233** [comment]
暂无考虑，因为这个项目叫clash
