### ISSUE TITLE
Hidden display of node attributes does not take effect

### ISSUE THREAD

**Issue by MNDIA** [libnyanpasu/clash-nyanpasu#1817]
### 复现步骤 / Step to reproduce
mihomo-alpha
A config file with a hidden display

### 预期行为 / Expected behavior

It should not be displayed, for example, on the WebUI
![image](https://github.com/user-attachments/assets/5496ec7c-05a1-411a-b8ee-90837bd240b0)

### 实际行为 / Actual behavior

Setting the format
```yaml
proxy-groups:
  - {name: DNSDNS,type: select, proxies: [DIRECT],hidden: true}
```
![image](https://github.com/user-attachments/assets/3fb62510-6393-488c-a95c-7e89b9211d1c)

### 环境信息 / Environment information

Clash Nyanpasu 1.6.1

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日志，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues) and [FAQ](https://nyanpasu.elaina.moe/others/faq)
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make multiply issue for multiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by MarkIvory2973** [comment]
+1
![image](https://github.com/user-attachments/assets/9861aa75-2139-4cc1-94e9-82a52541bbea)
