### ISSUE TITLE
debian12运行clash-nyanpasu报错

### ISSUE THREAD

**Issue by 906584305** [libnyanpasu/clash-nyanpasu#1830]
### 复现步骤 / Step to reproduce

root@lxcdebian10:~# dpkg -i '/home/admin/share/Share/Linux/clash/clash-nyanpasu/clash-nyanpasu_1.6.1_amd64.deb' 
(正在读取数据库 ... 系统当前共安装有 168980 个文件和目录。)
准备解压 .../clash-nyanpasu_1.6.1_amd64.deb  ...
正在解压 clash-nyanpasu (1.6.1) 并覆盖 (1.6.1) ...
正在设置 clash-nyanpasu (1.6.1) ...
正在处理用于 hicolor-icon-theme (0.17-2) 的触发器 ...
正在处理用于 mailcap (3.70+nmu1) 的触发器 ...
正在处理用于 gnome-menus (3.36.0-1.1) 的触发器 ...
正在处理用于 desktop-file-utils (0.26-1) 的触发器 ...
root@lxcdebian10:~# apt full-upgrade
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
正在计算更新... 完成
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
root@lxcdebian10:~# apt autoremove 
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
root@lxcdebian10:~# apt --fix-broken install
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 0 个软件包未被升级。
root@lxcdebian10:~# 

然后直接运行clash-nyanpasu
![屏幕截图 2024-10-20 181801](https://github.com/user-attachments/assets/25ea5b24-0fc2-4904-b839-57c8e7dbce6d)

clash-nyanpasu报错
![屏幕截图 2024-10-20 015150](https://github.com/user-attachments/assets/7069919a-a9f1-40cd-b89b-fe80f93b106f)

### 预期行为 / Expected behavior

不报错

### 实际行为 / Actual behavior

报错

### 备注 / Addition details

我是linux新手

### 环境信息 / Environment information

Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm

使用软件包：clash-nyanpasu_1.6.1_amd64.deb

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日志，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues) and [FAQ](https://nyanpasu.elaina.moe/others/faq)
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make multiply issue for multiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
请提交日记，此外请尝试一下 2.0-alpha 有没有这个问题

**Comment by 906584305** [comment]
> 请提交日记，此外请尝试一下 2.0-alpha 有没有这个问题

请问如何获取日记

**Comment by greenhat616** [comment]
数据目录在 $XDG_DATA_HOME/{placeholder} or $HOME/.local/share/{placeholder} 下方。
placeholder 可能是clash-nyanpasu。

点进去找到logs目录

**Comment by 906584305** [comment]
谢谢，找到了，应该是这个
[clash-nyanpasu.2024-10-20.app.log](https://github.com/user-attachments/files/17458521/clash-nyanpasu.2024-10-20.app.log)
appimage包双击没反应，连窗口都打不开，我用dpkg -i安装才能看到报错窗口

**Comment by 906584305** [comment]
> 数据目录在 $XDG_DATA_HOME/{placeholder} or $HOME/.local/share/{placeholder} 下方。 placeholder 可能是clash-nyanpasu。
> 
> 点进去找到logs目录
> 
> 此外，AppImage包有这个问题么？

谢谢，找到了，应该是这个
[clash-nyanpasu.2024-10-20.app.log](https://github.com/user-attachments/files/17458521/clash-nyanpasu.2024-10-20.app.log)
appimage包双击没反应，连窗口都打不开，我用dpkg -i安装才能看到报错窗口

**Comment by greenhat616** [comment]
> > 数据目录在 $XDG_DATA_HOME/{placeholder} or $HOME/.local/share/{placeholder} 下方。 placeholder 可能是clash-nyanpasu。
> > 点进去找到logs目录
> > 此外，AppImage包有这个问题么？
> 
> 谢谢，找到了，应该是这个 [clash-nyanpasu.2024-10-20.app.log](https://github.com/user-attachments/files/17458521/clash-nyanpasu.2024-10-20.app.log) appimage包双击没反应，连窗口都打不开，我用dpkg -i安装deb才能看到报错窗口

有可能是 app 不具备对 `/tmp` 的写权限。目前你当前用户有权限对 `/tmp` 目录写入么

**Comment by 906584305** [comment]
> > > 数据目录在 $XDG_DATA_HOME/{placeholder} or $HOME/.local/share/{placeholder} 下方。 placeholder 可能是clash-nyanpasu。
> > > 点进去找到logs目录
> > > 此外，AppImage包有这个问题么？
> > 
> > 
> > 谢谢，找到了，应该是这个 [clash-nyanpasu.2024-10-20.app.log](https://github.com/user-attachments/files/17458521/clash-nyanpasu.2024-10-20.app.log) appimage包双击没反应，连窗口都打不开，我用dpkg -i安装deb才能看到报错窗口
> 
> 有可能是 app 不具备对 `/tmp` 的写权限。目前你当前用户有权限对 `/tmp` 目录写入么. 试一下 2.0 测试版，看看还是相同位置报错么？是的话，等我有时间更新下插件看看能不能解决这个问题.

![屏幕截图 2024-10-22 110806](https://github.com/user-attachments/assets/cdd22884-514a-40d1-82c9-903bb29ac255)
可能我安装其他软件的时候顺便安装了一些依赖源，没想到今天我重新安装了一遍就能正常打开了！但appimage包还是打不开，不知道是啥原因。
奇怪的是 2.0 测试版我安装失败了，但我降级安装后1.6.1版本就能打开了，有点莫名其妙哈哈
![屏幕截图 2024-10-22 113459](https://github.com/user-attachments/assets/6ecb1cd2-859b-46c8-870f-a6001bc22a56)

**Comment by 906584305** [comment]
> > > > 数据目录在 $XDG_DATA_HOME/{placeholder} or $HOME/.local/share/{placeholder} 下方。 placeholder 可能是clash-nyanpasu。
> > > > 点进去找到logs目录
> > > > 此外，AppImage包有这个问题么？
> > > 
> > > 
> > > 谢谢，找到了，应该是这个 [clash-nyanpasu.2024-10-20.app.log](https://github.com/user-attachments/files/17458521/clash-nyanpasu.2024-10-20.app.log) appimage包双击没反应，连窗口都打不开，我用dpkg -i安装deb才能看到报错窗口
> > 
> > 
> > 有可能是 app 不具备对 `/tmp` 的写权限。目前你当前用户有权限对 `/tmp` 目录写入么. 试一下 2.0 测试版，看看还是相同位置报错么？是的话，等我有时间更新下插件看看能不能解决这个问题.
> 
> ![屏幕截图 2024-10-22 110806](https://private-user-images.githubusercontent.com/32992704/378665197-cdd22884-514a-40d1-82c9-903bb29ac255.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NzEwNDksIm5iZiI6MTcyOTU3MDc0OSwicGF0aCI6Ii8zMjk5MjcwNC8zNzg2NjUxOTctY2RkMjI4ODQtNTE0YS00MGQxLTgyYzktOTAzYmIyOWFjMjU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA0MTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFmZGIxY2NlN2QwYjNjNGQ1MTczY2Q0ODQ3M2E2MDhhZjYxYTYxNGM4YmRlYzVlOGExMzhlOTFjZWI1YTZjYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SvJdMzb02cwGT7tjz8eHLMqVcQZHCVCK0UxOKVYl0AQ) 可能我安装其他软件的时候顺便安装了一些依赖包，没想到今天我重新安装了一遍就能正常打开了！但appimage包还是打不开，不知道是啥原因。 奇怪的是 2.0 测试版我安装失败了，但我降级到1.6.1后，就能打开了，有点莫名其妙哈哈 ![屏幕截图 2024-10-22 113459](https://private-user-images.githubusercontent.com/32992704/378672625-6ecb1cd2-859b-46c8-870f-a6001bc22a56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NzEwNDksIm5iZiI6MTcyOTU3MDc0OSwicGF0aCI6Ii8zMjk5MjcwNC8zNzg2NzI2MjUtNmVjYjFjZDItODU5Yi00NmM4LTg3MGYtYTYwMDFiYzIyYTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDA0MTkwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNhMDk2MDcyYTQxY2EwYTg0ZmE0MzcyYTIwYjM5MTQ1ODU0MWIwMzk4YmIxM2I5Mzg4MzI3ZDA5M2Q4ZmRmZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.MW_Y6270IQyMBHupcGOBApllGgmuqhiJEhiyGWAGwq4)
