### ISSUE TITLE
最新的Pre-Release版本开机自启选项爆炸了喵

### ISSUE THREAD

**Issue by ColdLemonTea** [libnyanpasu/clash-nyanpasu#1869]
### 复现步骤 / Step to reproduce

1. 打开喵帕斯
2. 点击齿轮图标进入设置页面
3. 点击开机自启
4. 看它不停转圈圈

### 预期行为 / Expected behavior

它应该转一会儿圈圈然后亮起来喵

### 实际行为 / Actual behavior

实际它一直在转圈圈喵

### 应用日志 / App logs

[2024-10-23-log.zip](https://github.com/user-attachments/files/17492783/2024-10-23-log.zip)

### 环境信息 / Environment information

> ----------- System -----------
> OS: Windows 11 Home China 22631
> Arch: x86_64
> ----------- Device -----------
> CPU: Intel(R) Core(TM) i9-14900HX @ 2.20GHz x 32
> Memory: 31.80 GiB
> ----------- Core -----------
> clash-rs-alpha: `clash-rs 0.6.0`
> clash-rs: `clash-rs 0.6.0`
> mihomo-alpha: `Mihomo Meta alpha-3e966e8 windows amd64 with go1.23.2 Mon Oct 21 01:46:45 UTC 2024
> Use tags: with_gvisor`
> mihomo: `Mihomo Meta v1.18.9 windows amd64 with go1.23.1 Sun Sep 29 09:46:40 UTC 2024
> Use tags: with_gvisor`
> clash: `Clash n2023-09-05-gdcc8d87 windows amd64 with go1.21.0 Tue Sep  5 14:32:57 UTC 2023`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 2.0.0-alpha+1a0e047
> Commit Hash: 1a0e047f962803daed1d626ade8f4e783af16ab2
> Commit Author: github-actions[bot]
> Commit Date: 2024-10-22T22:21:20.000Z
> Build Date: 2024-10-23T00:48:05.936Z
> Build Profile: Nightly
> Build Platform: x86_64-pc-windows-msvc
> Rustc Version: rustc 1.84.0-nightly (439284741 2024-10-21)
> Llvm Version: 19.1
> 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日志，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues) and [FAQ](https://nyanpasu.elaina.moe/others/faq)
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make multiply issue for multiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by MarkIvory2973** [comment]
+1

**Comment by AntarcticBruin** [comment]
+1

**Comment by francisxie** [comment]
+1

**Comment by PandaFiredoge** [comment]
临时解决方案：
把Clash的快捷方式放到`%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`下

**Comment by ColdLemonTea** [comment]
> 下

一发现问题就放了但感觉不优雅（x

**Comment by ColdLemonTea** [comment]
> 临时解决方案：
> 
> 把Clash的快捷方式放到`%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`下

一发现问题就放了但感觉不优雅（x

**Comment by PandaFiredoge** [comment]
> > 临时解决方案：
> > 把Clash的快捷方式放到`%USERPROFILE%\AppData\Roaming\Microsoft\Windows\Start Menu\Programs\Startup`下
> 
> 一发现问题就放了但感觉不优雅（x

那就手写计划任务吧（

**Comment by Viomeat** [comment]
修复了 能不能踹我一下 谢谢大伙喵

**Comment by greenhat616** [comment]
试一下稍晚的开发版。
https://github.com/libnyanpasu/clash-nyanpasu/commit/44ca87ef9930389aa5113e2787ea14ee12fe6b82
