### ISSUE TITLE
Mac 下 System Service 的问题（不安装也不启动，开关都需要命令行手动）

### ISSUE THREAD

**Issue by jaywhj** [libnyanpasu/clash-nyanpasu#1870]
### 复现步骤 / Step to reproduce

1. Clash Nyanpasu安装后，服务模式默认是自动启动的还是手动的？今天才发现 system service 没安装也没启动，这是正常的吗？
另外，这个服务模式是管什么用的？

<img width="1077" alt="378690454-cad4b558-0661-4f74-a738-71e1ea9765dc" src="https://github.com/user-attachments/assets/61c20ac2-08a6-4524-860a-ffb2d45edabd">

2. 界面上我就手动安装一下，成功后，点击面板里的start，没法启动且报错，具体见下图。
3. 提示让我手动提权，命令行下手动start可以启动，最后stop也得在命令行下手动操作。
4. 重开app后，服务模式又回到了原点，得先安装再手动启动。

<img width="1076" alt="iShot_2024-10-23_22 53 39" src="https://github.com/user-attachments/assets/22b989ac-88cb-4b59-a110-f1e4da3846b5">

<br />

5. 最后，界面上再提一个强迫症建议🙏，菜单栏里的‘复制环境变量’能否放到二级目录？😂，我不知道这是不是常用操作啊，如果不是，可以放进去或者直接在面板里配置。
<img width="204" alt="iShot_2024-10-23_23 00 55" src="https://github.com/user-attachments/assets/2b2adf1e-fc9f-4205-81fe-730f2b98a135">

### 预期行为 / Expected behavior

正常启动

### 实际行为 / Actual behavior

不启动

### 应用日志 / App logs

日志文件我看了下，这个错误，日志里好像没什么记录，记录的都是之前反馈的dashboard显示异常的bug #1761 
clash-nyanpasu.2024-10-23.app.log

### 环境信息 / Environment information

Mac M1 12.2
Clash Nyanpasu 1.6.1

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日志，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues) and [FAQ](https://nyanpasu.elaina.moe/others/faq)
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make multiply issue for multiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by jaywhj** [comment]
日志文件我看了下，这个错误，日志里好像没什么记录，记录的都是之前反馈的dashboard显示异常的bug #1761 
[clash-nyanpasu.2024-10-23.app.log](https://github.com/user-attachments/files/17494687/clash-nyanpasu.2024-10-23.app.log)

**Comment by greenhat616** [comment]
已知问题，之后可能会尝试使用 `do shell` 来执行指令。目前是使用 objc 来调用的提权指令。

**Comment by jaywhj** [comment]
> 已知问题，之后可能会尝试使用 `do shell` 来执行指令。目前是使用 objc 来调用的提权指令。

好的，辛苦啦，已知问题就好，就怕没发现😄，加油！

**Comment by keiko233** [comment]
对于做开发的来说，复制环境变量是个常用操作，故没有作为二级菜单

**Comment by jaywhj** [comment]
> 对于做开发的来说，复制环境变量是个常用操作，故没有作为二级菜单

OK！
