### ISSUE TITLE
新的模式托盘图标在Windows下显示效果不佳

### ISSUE THREAD

**Issue by lainbo** [LibNyanpasu/clash-nyanpasu#188]
### 复现步骤 / Step to reproduce

1. 打开Clash Nyanpasu
2. 观察图标

### 预期行为 / Expected behaviour

在1.4.1版本中, 显示较为正常

### 实际行为 / Actual Behaviour

1.4.2版本中显示效果如下, 显示效果并不是很好
![image](https://github.com/keiko233/clash-nyanpasu/assets/46062895/2148c257-77ef-4235-a208-89069e8502b2)

![image](https://github.com/keiko233/clash-nyanpasu/assets/46062895/fb92379e-7863-430d-8f4d-cf7b709d59d2)

### 应用日志 / App logs

无日志

### 备注 / Addition details

显示屏分辨率为24寸1920×1080

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.2

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windwos 11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
低分辨率会存在这个问题，需要一点时间来解决

**Comment by realstephenzhao** [comment]
对的，🐱的眼睛和嘴巴太小太细，尾巴也很锯齿，几乎辨别不出来是啥图标。

**Comment by iugo** [comment]
在 https://tauri.app/v1/guides/features/system-tray/ 中, 图标是 png 没有针对多种分辨率进行调整的.

想要解决这个问题可能需要 tauri 更新.

或者在 https://github.com/keiko233/clash-nyanpasu/blob/85bc278c62768ee2758a05abb36e77d30e076fdc/backend/tauri/src/core/tray.rs#L146-L154 这里先使用图片处理的库进行针对性处理, 而不是直接读取原始文件交给 tauri. 比如 `let _ = tray.set_icon(tauri::Icon::Raw(resize_image_for_resolution(indication_icon)));`
