### ISSUE TITLE
希望增加支持多重代理的功能

### ISSUE THREAD

**Issue by hanyaxxx** [libnyanpasu/clash-nyanpasu#1888]
### 需求 / Requirement

我想支持多重代理的功能
比如代理地址A 代理地址B 
路径为 代理A->代理B->目标地址

### 建议实现 / Suggested implements

配置项目或者script实现感觉都可以

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.4.1

### 是否为 Pre-release / Is pre-release version

26f05a0

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 中的内容 / You have checked [Q&A](https://nyanpasu.elaina.moe/others/issues) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make multiply issue for multiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该功能在最新 Pre-release 版本中并未实现 / This feature have not implemented in latest Pre-release version

**Comment by MarkIvory2973** [comment]
已经有了，不过这是内核的事情，和客户端没关系。

https://wiki.metacubex.one/config/proxy-groups/relay/

**Comment by MarkIvory2973** [comment]
> relay 策略即将被弃用，请使用[dialer-proxy](https://wiki.metacubex.one/config/proxies/#dialer-proxy)
> wireguard 目前不支持在 relay 中使用，也请使用[dialer-proxy](https://wiki.metacubex.one/config/proxies/#dialer-proxy)

**Comment by keiko233** [comment]
不属于gui范畴，修改配置文件即可实现，不过倒是可以做一个可视化展示，但是目前该计划不在主线
