### ISSUE TITLE
[Bug] 无法定位程序输入点TaskDialogIndirect于动态链接库

### ISSUE THREAD

**Issue by caolonghao** [libnyanpasu/clash-nyanpasu#1917]
### 复现步骤 / Step to reproduce

1. Windows下载1.6.1版release msi （pre release中2.0.0_fixed_webview也可复现）
2. 安装软件
3. 运行第一次后退出，再次运行

### 预期行为 / Expected behavior

预期应当正常打开

### 实际行为 / Actual behavior

![image](https://github.com/user-attachments/assets/b255d64d-d621-4549-880c-e6031f52cc4e)
![image](https://github.com/user-attachments/assets/080a6862-1736-4538-8437-c57c0b357459)

### 备注 / Addition details

可能与tauri的变化有关？https://github.com/tauri-apps/tauri/issues/6926

### 环境信息 / Environment information

Windows11 
Clash Nyanpasu 1.6.1

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日志，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues) and [FAQ](https://nyanpasu.elaina.moe/others/faq)
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make multiply issue for multiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
无法复现，请检查系统环境？或者尝试在Windows sandbox运行

**Comment by caolonghao** [comment]
在windows sandbox安装1.6.1版release运行结果如下：
<img width="363" alt="1730538877586" src="https://github.com/user-attachments/assets/0b6bb8bb-678b-46ee-b106-f68e826453e8">

**Comment by keiko233** [comment]
> 在windows sandbox安装1.6.1版release运行结果如下： <img alt="1730538877586" width="363" src="https://private-user-images.githubusercontent.com/57024921/382460989-0b6bb8bb-678b-46ee-b106-f68e826453e8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NDExOTMsIm5iZiI6MTczMDU0MDg5MywicGF0aCI6Ii81NzAyNDkyMS8zODI0NjA5ODktMGI2YmI4YmItNjc4Yi00NmVlLWIxMDYtZjY4ZTgyNjQ1M2U4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDA5NDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE3NTM4ZWQ3YWE4ODU4M2FkNGZkZDQxNzJkNDdkYjc1ZTc0ODJjODlkNTczMGY3ZDk3NWE1OGRmMTdiMDVmNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vvDH93eOjKaooN-dXNYkwqQ3KDdE1knAHRS3s3zFNdw">

提示上说了，请安装vcruntime
https://learn.microsoft.com/zh-cn/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by caolonghao** [comment]
感谢回复，我试试您这个链接，我搜到的安装vs2015的那个包显示已安装。

**Comment by caolonghao** [comment]
怪了，我在沙盒中安装vcruntime后，能正常运行。但是在本机环境安装vcruntime后，重新安装clash nyanpasu，第一次可以运行，退出后再次打开就会出现无法定位动态链接库的问题。

**Comment by greenhat616** [comment]
尝试 DISM 修复下操作系统看看？

**Comment by caolonghao** [comment]
使用DISM修复过后，然后尝试[Clash.Nyanpasu_2.0.0_x64-setup.exe](https://github.com/libnyanpasu/clash-nyanpasu/releases/download/pre-release/Clash.Nyanpasu_2.0.0_x64-setup.exe)版本仍旧存在此问题，表现为安装完成时，勾选启动应用，能正常启动，退出后再进入就会出现这个bug。似乎开机后第一次启动也可以正常进入，但是退出后再次进入就会出现问题。

**Comment by greenhat616** [comment]
> 使用DISM修复过后，然后尝试[Clash.Nyanpasu_2.0.0_x64-setup.exe](https://github.com/libnyanpasu/clash-nyanpasu/releases/download/pre-release/Clash.Nyanpasu_2.0.0_x64-setup.exe)版本仍旧存在此问题，表现为安装完成时，勾选启动应用，能正常启动，退出后再进入就会出现这个bug。似乎开机后第一次启动也可以正常进入，但是退出后再次进入就会出现问题。我之前使用clash nyanpasu也一直是正常的，从一天突然开始报此错误，无论怎么重装都一样，很奇怪。
> 
> 另外，我测试了Clash Verge也是基于tauri开发的，没有复现这个问题。

系统里有安装什么杀毒软件，或有启用组策略吗？此外，之后更具体的信息，或着更深入的测试，可以通过这个 bot 与我们联系：<https://t.me/nyanpasu_message_bot>

> 我之前使用clash nyanpasu也一直是正常的，从一天突然开始报此错误，无论怎么重装都一样，很奇怪。

确实很奇怪，我这里也无法从沙盒复现问题。

> 另外，我测试了Clash Verge也是基于tauri开发的，没有复现这个问题。

是老版本的 Clash Verge 么？

**Comment by caolonghao** [comment]
抱歉，才看到您的回复。
1. 没有安装什么杀毒软件，就是windows defender
2. clash verge是v1.7.7版的，https://github.com/clash-verge-rev/clash-verge-rev/releases/tag/v1.7.7，应该也是基于老版的tauri才对。

**Comment by SuperMaskv** [comment]
> 使用DISM修复过后，然后尝试[Clash.Nyanpasu_2.0.0_x64-setup.exe](https://github.com/libnyanpasu/clash-nyanpasu/releases/download/pre-release/Clash.Nyanpasu_2.0.0_x64-setup.exe)版本仍旧存在此问题，表现为安装完成时，勾选启动应用，能正常启动，退出后再进入就会出现这个bug。似乎开机后第一次启动也可以正常进入，但是退出后再次进入就会出现问题。我之前使用clash nyanpasu也一直是正常的，从一天突然开始报此错误，无论怎么重装都一样，很奇怪。
> 
> 另外，我测试了Clash Verge也是基于tauri开发的，没有复现这个问题。

补充一个可能对你们有帮助的信息，我在`windows 10 x64专业版22H2内部版本号19045.5073`上使用`Clash Verge 1.7.7`也遇到`“无法定位程序输入点 TaskDialoglndirect 于动态链接库 D:\ProgramFiles\Clash Verge\Clash Verge.exe上”`的问题。但是和 @caolonghao 相反，我是在开机自启的时候Clash Verge会报这个错，稍后手动双击图标启动没有问题。
