### ISSUE TITLE
即使我完成了下载，导入了 clash 配置，但当我打开系统代理后，仍然无法访问国外网站

### ISSUE THREAD

**Issue by IAMLEIzZ** [libnyanpasu/clash-nyanpasu#1932]
### 复现步骤 / Step to reproduce

![image](https://github.com/user-attachments/assets/d2d600c3-2b3d-40fa-ae1b-a359d88a1713)
![image](https://github.com/user-attachments/assets/eb6ad067-c83c-48ea-977e-c25e515fb587)

### 预期行为 / Expected behavior

同时我也检查了我的系统代理设置
![image](https://github.com/user-attachments/assets/aeb48a83-6f2d-4bca-b233-d5af73de4306)

### 实际行为 / Actual behavior

但是我依旧无法访问外网，是右下角内核信息服务状态为 not_installed 的问题吗请问，如果是请问我该怎么解决

### 环境信息 / Environment information

Clash Nyanpasu 1.6.1

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日志，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues) and [FAQ](https://nyanpasu.elaina.moe/others/faq)
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make multiply issue for multiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by IAMLEIzZ** [comment]
我的系统是 Linux - Debian12 ，Clash版本为 clash-nyanpasu_1.6.1_amd64.deb

**Comment by greenhat616** [comment]
终端里需要：
![图片](https://github.com/user-attachments/assets/11827aff-4983-4144-863b-c4abd45dc73f)
浏览器需要安装 SmartProxy 或者设置遵循系统代理。

**Comment by IAMLEIzZ** [comment]
> 终端里需要： 浏览器需要安装SmartProxy或者设置遵循系统代理。 ![图片](https://private-user-images.githubusercontent.com/41122242/382988349-11827aff-4983-4144-863b-c4abd45dc73f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3ODA3NTIsIm5iZiI6MTczMDc4MDQ1MiwicGF0aCI6Ii80MTEyMjI0Mi8zODI5ODgzNDktMTE4MjdhZmYtNDk4My00MTQ0LTg2M2ItYzRhYmQ0NWRjNzNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDA0MjA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlODVjNDE1NGY2ZjBkMmQ2NjgwNWJlOTNiZWIyZjQ3MWZjZTFiNTIyY2RmMjlmMmMxYzJjZmEwYWFkNjI2YzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.yDnaWTfClCX0KKY57I8Mk-LW8aUzHZ8uB0ofGtM09Hw)

感谢您这么快的回复 我现在去试一下
