### ISSUE TITLE
日志debug级别下，日志页面依然显示info级别的日志

### ISSUE THREAD

**Issue by easyinplay** [libnyanpasu/clash-nyanpasu#1948]
### 复现步骤 / Step to reproduce

1、打开设置选择debug级别日志
![image](https://github.com/user-attachments/assets/3937a1bd-66b0-462b-a780-e634f86b978c)
2、打开日志页面
![image](https://github.com/user-attachments/assets/119a9a8f-1b85-44b8-b442-4cd59116b31c)

### 预期行为 / Expected behavior

选的不同的级别 日志可以输出不同级别的日志

### 实际行为 / Actual behavior

选择debug级别 无法输出debug级别的日志

### 应用日志 / App logs

[2024-11-07-log.zip](https://github.com/user-attachments/files/17655666/2024-11-07-log.zip)

### 环境信息 / Environment information

> ----------- System -----------
> OS: Windows 11 Pro for Workstations 27729
> Arch: x86_64
> ----------- Device -----------
> CPU: Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz @ 2.90GHz x 6
> Memory: 31.87 GiB
> ----------- Core -----------
> clash-rs: `clash-rs 0.7.0`
> mihomo-alpha: `Mihomo Meta alpha-ce52c34 windows amd64 with go1.23.2 Tue Nov  5 02:06:21 UTC 2024
> Use tags: with_gvisor`
> clash-rs-alpha: `clash-rs 0.7.0`
> mihomo: `Mihomo Meta v1.18.10 windows amd64 with go1.23.2 Sun Nov  3 09:22:09 UTC 2024
> Use tags: with_gvisor`
> clash: `Clash n2023-09-05-gdcc8d87 windows amd64 with go1.21.0 Tue Sep  5 14:32:57 UTC 2023`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 2.0.0-alpha+7980c0b
> Commit Hash: 7980c0baf0ba34b4aa70d2c348913f785b720057
> Commit Author: github-actions[bot]
> Commit Date: 2024-11-05T22:20:45.000Z
> Build Date: 2024-11-06T00:40:04.242Z
> Build Profile: Nightly
> Build Platform: x86_64-pc-windows-msvc
> Rustc Version: rustc 1.84.0-nightly (fbab78289 2024-11-04)
> Llvm Version: 19.1
> 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日志，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues) and [FAQ](https://nyanpasu.elaina.moe/others/faq)
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make multiply issue for multiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
这个应该找 Clash 去反馈，目前使用的是其 Web API，其 API 不提供 Debug 级别的日记，且目前无计划专门针对其日记流作索引。
