### ISSUE TITLE
代理组页面 无法切换到“全局”和“直连”标签页

### ISSUE THREAD

**Issue by easyinplay** [libnyanpasu/clash-nyanpasu#1949]
### 复现步骤 / Step to reproduce

1、打开代理组页面点击 “全局”或者“直连”标签页
![image](https://github.com/user-attachments/assets/53424498-e35e-4370-9895-8493a7608299)

### 预期行为 / Expected behavior

可以切换到对应的模式

### 实际行为 / Actual behavior

目前只有规则模式可以生效，全局和直连模式无法生效，托盘右键菜单模式也无法切换成功（可以点击，但是不生效） 应该是同一个bug

### 应用日志 / App logs

[2024-11-07-log.zip](https://github.com/user-attachments/files/17655682/2024-11-07-log.zip)

### 环境信息 / Environment information

> ----------- System -----------
> OS: Windows 11 Pro for Workstations 27729
> Arch: x86_64
> ----------- Device -----------
> CPU: Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz @ 2.90GHz x 6
> Memory: 31.87 GiB
> ----------- Core -----------
> clash-rs-alpha: `clash-rs 0.7.0`
> clash-rs: `clash-rs 0.7.0`
> clash: `Clash n2023-09-05-gdcc8d87 windows amd64 with go1.21.0 Tue Sep  5 14:32:57 UTC 2023`
> mihomo: `Mihomo Meta v1.18.10 windows amd64 with go1.23.2 Sun Nov  3 09:22:09 UTC 2024
> Use tags: with_gvisor`
> mihomo-alpha: `Mihomo Meta alpha-ce52c34 windows amd64 with go1.23.2 Tue Nov  5 02:06:21 UTC 2024
> Use tags: with_gvisor`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 2.0.0-alpha+7980c0b
> Commit Hash: 7980c0baf0ba34b4aa70d2c348913f785b720057
> Commit Author: github-actions[bot]
> Commit Date: 2024-11-05T22:20:45.000Z
> Build Date: 2024-11-06T00:40:04.242Z
> Build Profile: Nightly
> Build Platform: x86_64-pc-windows-msvc
> Rustc Version: rustc 1.84.0-nightly (fbab78289 2024-11-04)
> Llvm Version: 19.1
> 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日志，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues) and [FAQ](https://nyanpasu.elaina.moe/others/faq)
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make multiply issue for multiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by easyinplay** [comment]
> 我这里无法复现，profile 发 https://t.me/nyanpasu_message_bot 看看

已发送，文件名为 ClashPremium.yaml （是Meta的配置文件，因为历史的原因做了个外网链接方便自己多设备同步没有修改名字）

**Comment by easyinplay** [comment]
> 我这里无法复现，profile 发 [t.me/nyanpasu_message_bot](https://t.me/nyanpasu_message_bot) 看看

20241109补充，同样的配置文件在我另一台pc上切换是没有问题的，但是在这个设备上就切换不了，感觉像是gui方面的bug，不太清楚是什么原因导致的，我截图一下两台设备页面对比

![image](https://github.com/user-attachments/assets/e19b6967-c677-4ed3-8c1d-271653b6be73)
![image](https://github.com/user-attachments/assets/79254584-9e51-4c41-b478-3a717064ce4a)
![image](https://github.com/user-attachments/assets/f87e76bb-c333-4740-8282-6af5aa06514a)

上面的设备为问题设备，无法切换选项卡
下面的设备同样的版本和配置文件，切换正常
[2024-11-09-log问题设备.zip](https://github.com/user-attachments/files/17688532/2024-11-09-log.zip)
[2024-11-09-log正常设备.zip](https://github.com/user-attachments/files/17688533/2024-11-09-log.zip)

**Comment by greenhat616** [comment]
需要点时间进行调查，最近周末和平时都没有空。

**Comment by easyinplay** [comment]
切换内核到Alpha 后消失
