### ISSUE TITLE
建议代理组选择可以与配置关联

### ISSUE THREAD

**Issue by a81n9** [libnyanpasu/clash-nyanpasu#1958]
### 需求 / Requirement

例如：
我是用 A 配置选择 “自动选择” 这个代理组，当切换 B 配置时我切换为了 “自动选择2” 代理组
希望下次切换为 A 配置时依然默认 “自动选择” 这个代理组，代理组选择与配置关联

### 建议实现 / Suggested implements

/

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.6.1

### 是否为 Pre-release / Is pre-release version

0731270

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 中的内容 / You have checked [Q&A](https://nyanpasu.elaina.moe/others/issues) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make multiply issue for multiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该功能在最新 Pre-release 版本中并未实现 / This feature have not implemented in latest Pre-release version

**Comment by easyinplay** [comment]
我记得配置文件里面可以添加相关的配置
profile:
  store-selected: true
