### ISSUE TITLE
错误提示 TUN 模式异常

### ISSUE THREAD

**Issue by ColdLemonTea** [libnyanpasu/clash-nyanpasu#1962]
### 复现步骤 / Step to reproduce

1.启动喵帕斯
2.等待奇迹发生（有时候有有时候没
3.喵帕斯啊啊大叫：没有启用服务模式喵！没有用管理员模式启动喵帕斯喵！所以喵帕斯不给你用 TUN 喵！

### 预期行为 / Expected behavior

因为咱用的系统代理且没有开启 TUN，所以即使我没有安装服务模式它也不应该在有关 TUN 和服务模式的事情上报错喵

### 实际行为 / Actual behavior

实际上它啊啊大叫了喵

### 应用日志 / App logs

[2024-11-08-log.zip](https://github.com/user-attachments/files/17680901/2024-11-08-log.zip)

### 备注 / Addition details

喵

### 环境信息 / Environment information

> ----------- System -----------
> OS: Windows 11 Pro for Workstations 22631
> Arch: x86_64
> ----------- Device -----------
> CPU: Intel(R) Core(TM) i9-14900HX @ 2.20GHz x 32
> Memory: 31.80 GiB
> ----------- Core -----------
> clash-rs: `clash-rs 0.7.0`
> clash: `Clash n2023-09-05-gdcc8d87 windows amd64 with go1.21.0 Tue Sep  5 14:32:57 UTC 2023`
> mihomo: `Mihomo Meta v1.18.9 windows amd64 with go1.23.1 Sun Sep 29 09:46:40 UTC 2024
> Use tags: with_gvisor`
> mihomo-alpha: `Mihomo Meta alpha-3e966e8 windows amd64 with go1.23.2 Mon Oct 21 01:46:45 UTC 2024
> Use tags: with_gvisor`
> clash-rs-alpha: `clash-rs 0.7.0`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 2.0.0-alpha+43476bd
> Commit Hash: 43476bd0b272f1170049d029993ec81dc8c70e94
> Commit Author: Jonson Petard
> Commit Date: 2024-10-31T13:38:57.000Z
> Build Date: 2024-11-02T00:48:22.828Z
> Build Profile: Nightly
> Build Platform: x86_64-pc-windows-msvc
> Rustc Version: rustc 1.84.0-nightly (a0d98ff0e 2024-10-31)
> Llvm Version: 19.1
> 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日志，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues) and [FAQ](https://nyanpasu.elaina.moe/others/faq)
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make multiply issue for multiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
日志里没有太多有用的信息，需要更详细的复现过程及tracing日志攻诊断使用
