### ISSUE TITLE
Connection界面UI文字重叠

### ISSUE THREAD

**Issue by HaoTian22** [LibNyanpasu/clash-nyanpasu#202]
### 复现步骤 / Step to reproduce

![image](https://github.com/keiko233/clash-nyanpasu/assets/48882584/0acf3dcd-a502-47a0-b168-eefa8064b6c4)
最上面的那一栏显示文字重叠

### 预期行为 / Expected behaviour

希望能够根据窗口宽度自动换行或省略部分显示文字/显示简写

### 实际行为 / Actual Behaviour

实际上就是宽度不够导致文字重叠了

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.2

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windows 11

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by ohhccwss** [comment]
把左右拉宽一点可以暂时解决这个问题

**Comment by greenhat616** [comment]
https://github.com/keiko233/clash-nyanpasu/issues/51

**Comment by keiko233** [comment]
close https://github.com/LibNyanpasu/clash-nyanpasu/commit/3fd461922344264f5debfc74e6a508248bc7591c
