### ISSUE TITLE
现在用的是Clash for Windows可以转过来吗

### ISSUE THREAD

**Issue by 107295472** [libnyanpasu/clash-nyanpasu#2028]
### 需求 / Requirement

用的server模式

### 建议实现 / Suggested implements

clash-core-service

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.4.1

### 是否为 Pre-release / Is pre-release version

bd1342b

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 中的内容 / You have checked [Q&A](https://nyanpasu.elaina.moe/others/issues) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make multiply issue for multiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该功能在最新 Pre-release 版本中并未实现 / This feature have not implemented in latest Pre-release version

**Comment by 107295472** [comment]
用的   "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt" 这些规则

**Comment by keiko233** [comment]
不明白什么意思，软件只是工具，用哪个都一样，功能请自行体验
