### ISSUE TITLE
代理链添加的自建节点无法使用

### ISSUE THREAD

**Issue by Nothingtodoforma** [libnyanpasu/clash-nyanpasu#2029]
### 复现步骤 / Step to reproduce

我在代理订阅时加了一个自建节点的代理链![image](https://github.com/user-attachments/assets/59163e31-68ef-4d8a-b6b4-45cb71fafc87)
![image](https://github.com/user-attachments/assets/8ea2daa8-3b4f-4d16-9363-ef5be8191016)

### 预期行为 / Expected behavior

但是我选择该节点时，数据应该走的mypoint节点才对（节点能ping通，代理链添加保存未报错）
![image](https://github.com/user-attachments/assets/502afe48-d0ab-40c6-957f-901abc9731e3)

### 实际行为 / Actual behavior

但是我选择该节点时，数据却是走的订阅代理的第一个节点
![image](https://github.com/user-attachments/assets/bf4b8ff5-5a4f-4764-9da7-f29718c81a88)

### 应用日志 / App logs

[2024-11-18-log.zip](https://github.com/user-attachments/files/17799032/2024-11-18-log.zip)

### 环境信息 / Environment information

> ----------- System -----------
> OS: Windows 10 Pro 19045
> Arch: x86_64
> ----------- Device -----------
> CPU: 11th Gen Intel(R) Core(TM) i5-11400H @ 2.70GHz @ 2.69GHz x 12
> Memory: 15.85 GiB
> ----------- Core -----------
> mihomo: `Mihomo Meta v1.18.9 windows amd64 with go1.23.1 Sun Sep 29 09:46:40 UTC 2024 Use tags: with_gvisor`
> clash: `Clash n2023-09-05-gdcc8d87 windows amd64 with go1.21.0 Tue Sep  5 14:32:57 UTC 2023`
> mihomo-alpha: `Mihomo Meta alpha-c63a851 windows amd64 with go1.23.2 Fri Oct  4 06:23:15 UTC 2024 Use tags: with_gvisor`
> clash-rs: `clash-rs 0.5.0`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 1.6.1
> Commit Hash: 14b04075d8f256b1a4ee0a704f985d8f654f2453
> Commit Author: Jonson Petard
> Commit Date: 2024-09-10T03:59:13.000Z
> Build Date: 2024-09-10T04:55:14.413Z
> Build Profile: Release
> Build Platform: x86_64-pc-windows-msvc
> Rustc Version: rustc 1.83.0-nightly (c2f74c3f9 2024-09-09)
> Llvm Version: 19.1
> 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日志，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues) and [FAQ](https://nyanpasu.elaina.moe/others/faq)
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make multiply issue for multiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by Nothingtodoforma** [comment]
我不是在xsus代理订阅加了代理链吗？为什么墙外流量没走我选择的自建节点呢？还是我理解错了，代理链不能这样用？

**Comment by Nothingtodoforma** [comment]
> 说明该规则走了XSUS代理组，你应该将XSUS代理组修改为需要用的节点


我不是在xsus代理订阅加了代理链吗？为什么墙外流量没走我选择的自建节点呢？还是我理解错了，代理链不能这样用？

**Comment by keiko233** [comment]
> > 说明该规则走了XSUS代理组，你应该将XSUS代理组修改为需要用的节点
> 
> 我不是在xsus代理订阅加了代理链吗？为什么墙外流量没走我选择的自建节点呢？还是我理解错了，代理链不能这样用？

代理链是修改配置文件的一个操作，修改好的具体行为需要根据内核的执行逻辑与最终的配置文件决定
