### ISSUE TITLE
控制台面板，点击关闭，直接退出了。

### ISSUE THREAD

**Issue by mayiming0708** [libnyanpasu/clash-nyanpasu#2041]
### 需求 / Requirement

希望关闭面板不退出，隐藏到托盘

### 建议实现 / Suggested implements

希望关闭面板不退出，隐藏到托盘

### Clash Nyanpasu 版本号 / Clash Nyanpasu

2.0.0-alpha

### 是否为 Pre-release / Is pre-release version

91e4661

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 中的内容 / You have checked [Q&A](https://nyanpasu.elaina.moe/others/issues) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make multiply issue for multiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该功能在最新 Pre-release 版本中并未实现 / This feature have not implemented in latest Pre-release version

**Comment by greenhat616** [comment]
提供一下日记，看看是哪里 panic 了

**Comment by greenhat616** [comment]
是 macos 吗？好像是 macos 15 之后有的一个 bug，目前还不清楚是 Tauri 还是应用自身导致的。需要调查（目前没有设备）。
cc @keiko233

**Comment by mayiming0708** [comment]
OK,感谢回答，是macOS，希望可以修复，1.X版本是没有这个问题的

**Comment by keiko233** [comment]
手头暂无macos15设备，可能要延期一下才能看看

**Comment by Melody** [comment]
> 手头暂无macos15设备，可能要延期一下才能看看

点击关闭后报
异常: EXC_BAD_ACCESS (code=1, address=0x20)

堆
[libobjc.A.dylib] objc_release 0x000000019e684280
[libobjc.A.dylib] AutoreleasePoolPage::releaseUntil(objc_object**) 0x000000019e68bd94
[libobjc.A.dylib] objc_autoreleasePoolPop 0x000000019e688138
[CoreFoundation] _CFAutoreleasePoolPop 0x000000019eafc578
[CoreFoundation] __CFRunLoopPerCalloutARPEnd 0x000000019ec0eda0
[CoreFoundation] __CFRunLoopDoObservers 0x000000019eb3cf8c
[CoreFoundation] __CFRunLoopRun 0x000000019eb3c634
[CoreFoundation] CFRunLoopRunSpecific 0x000000019eb3bbc4
[HIToolbox] RunCurrentEventLoopInMode 0x00000001a9fabf64
[HIToolbox] ReceiveNextEventCommon 0x00000001a9fb1d54
[HIToolbox] _BlockUntilNextEventMatchingListInModeWithFilter 0x00000001a9fb1eb8
[AppKit] _DPSNextEvent 0x00000001a2667a08
[AppKit] -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] 0x00000001a2fa7e0c
[AppKit] -[NSApplication run] 0x00000001a265aae0
[clash-nyanpasu] <() as objc::message::MessageArguments>::invoke mod.rs:128
[clash-nyanpasu] objc::message::platform::send_unverified mod.rs:27
[内联] [clash-nyanpasu] objc::message::send_message mod.rs:178
[clash-nyanpasu] tao::platform_impl::platform::event_loop::EventLoop<T>::run_return event_loop.rs:237
[clash-nyanpasu] tao::platform_impl::platform::event_loop::EventLoop<T>::run event_loop.rs:204
[clash-nyanpasu] tao::event_loop::EventLoop<T>::run event_loop.rs:215
[clash-nyanpasu] <tauri_runtime_wry::Wry<T> as tauri_runtime::Runtime<T>>::run lib.rs:2812
[clash-nyanpasu] tauri::app::App<R>::run app.rs:1146
[clash-nyanpasu] app_lib::run lib.rs:332
[clash-nyanpasu] clash_nyanpasu::main main.rs:4
[clash-nyanpasu] core::ops::function::FnOnce::call_once function.rs:250
[clash-nyanpasu] std::sys::backtrace::__rust_begin_short_backtrace backtrace.rs:154
[clash-nyanpasu] std::rt::lang_start::{{closure}} rt.rs:195
[内联] [clash-nyanpasu] core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once function.rs:284
[内联] [clash-nyanpasu] std::panicking::try::do_call panicking.rs:557
[内联] [clash-nyanpasu] std::panicking::try panicking.rs:520
[内联] [clash-nyanpasu] std::panic::catch_unwind panic.rs:358
[内联] [clash-nyanpasu] std::rt::lang_start_internal::{{closure}} rt.rs:174
[内联] [clash-nyanpasu] std::panicking::try::do_call panicking.rs:557
[内联] [clash-nyanpasu] std::panicking::try panicking.rs:520
[内联] [clash-nyanpasu] std::panic::catch_unwind panic.rs:358
[clash-nyanpasu] std::rt::lang_start_internal rt.rs:174
[clash-nyanpasu] std::rt::lang_start rt.rs:194
[clash-nyanpasu] main 0x00000001000a5dbc
[dyld] start 0x000000019e6d4274

**Comment by greenhat616** [comment]
已修复，欢迎下载明早的版本测试
