### ISSUE TITLE
Nightly 版本无法创建 JS / Lua 脚本链

### ISSUE THREAD

**Issue by Jeremy-Hibiki** [libnyanpasu/clash-nyanpasu#2069]
### 复现步骤 / Step to reproduce

1. 添加新链
2. 选 JS 或 Lua
3. 保存

### 预期行为 / Expected behavior

Should work

### 实际行为 / Actual behavior

开发者工具控制台报错：
Uncaught (in promise) Anyhow(
    "the type field is null",
)

应该是 Rust 端的报错

### 应用日志 / App logs

[clash-nyanpasu.2024-11-24.app.log](https://github.com/user-attachments/files/17894155/clash-nyanpasu.2024-11-24.app.log)

### 环境信息 / Environment information

> ----------- System -----------
> OS: Windows 11 Pro 26100
> Arch: x86_64
> ----------- Device -----------
> CPU: Intel(R) Core(TM) i7-14700KF @ 3.40GHz x 28
> Memory: 47.82 GiB
> ----------- Core -----------
> clash-rs: `clash-rs 0.7.1`
> clash: `Clash n2023-09-05-gdcc8d87 windows amd64 with go1.21.0 Tue Sep  5 14:32:57 UTC 2023`
> mihomo: `Mihomo Meta v1.18.10 windows amd64 with go1.23.2 Sun Nov  3 09:22:09 UTC 2024
> Use tags: with_gvisor`
> mihomo-alpha: `Mihomo Meta alpha-eb985b0 windows amd64 with go1.23.3 Thu Nov 21 14:54:03 UTC 2024
> Use tags: with_gvisor`
> clash-rs-alpha: `clash-rs 0.7.2-alpha+sha.19ea847`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 2.0.0-alpha+44ca87e
> Commit Hash: 44ca87ef9930389aa5113e2787ea14ee12fe6b82
> Commit Author: Jonson Petard
> Commit Date: 2024-11-24T14:12:47.000Z
> Build Date: 2024-11-24T14:31:35.674Z
> Build Profile: Nightly
> Build Platform: x86_64-pc-windows-msvc
> Rustc Version: rustc 1.85.0-nightly (a47555110 2024-11-22)
> Llvm Version: 19.1
> 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日志，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues) and [FAQ](https://nyanpasu.elaina.moe/others/faq)
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make multiply issue for multiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
https://github.com/libnyanpasu/clash-nyanpasu/commit/778a3e498abe8727e627f44fb4c219d1987b150c
