### ISSUE TITLE
[功能请求]-在设置里面增加是否检测更新的按钮开关

### ISSUE THREAD

**Issue by ixxc** [LibNyanpasu/clash-nyanpasu#207]
### 需求 / Requirement

RT，这样每次启动时就不会发起一个检测更新的请求

### 建议实现 / Suggested implements

在设置里面增加按钮开关，类似下图

![image](https://github.com/keiko233/clash-nyanpasu/assets/105781599/242b752a-c28a-4066-a95b-9e4c84cbcaf4)

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.2

### 是否为 Pre-release / Is pre-release version

否

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
[compla](https://github.com/LibNyanpasu/clash-nyanpasu/commit/a17510a84c495d24d227f663ba1e8932f3309703)
