### ISSUE TITLE
开发版降到正式版配置文件无法使用

### ISSUE THREAD

**Issue by txl263** [libnyanpasu/clash-nyanpasu#2102]
### 复现步骤 / Step to reproduce

正在使用的是Clash.Nyanpasu_1.6.1版本，升级到开发版Clash.Nyanpasu_2.0.0_x64后因为有问题所以卸载重新安装了1.6.1版本，配置文件保留。
降回1.6.1后原有的配置文件不会读取，配置里是空的。
但是如果新导入配置就会把profiles.yaml覆写。
退出程序把profiles.yaml重新覆盖还是不会读取。

### 预期行为 / Expected behavior

会自动读取原有的配置文件

### 实际行为 / Actual behavior

开发版会自动读取原有的配置文件，正式版配置为空。

### 备注 / Addition details

另外问下，像这样的规则集是怎么添加的？从什么地方或者哪个文件？profiles.yaml？
![image](https://github.com/user-attachments/assets/8c27f2f1-e51f-4da9-8e85-7ef6ac845ada)

### 环境信息 / Environment information

Windows11专业版 24H2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日志，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues) and [FAQ](https://nyanpasu.elaina.moe/others/faq)
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make multiply issue for multiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
我们只尽可能保证前向兼容性，**不**保证后向兼容性。
