### ISSUE TITLE
macOS 系统服务无法安装也无法卸载

### ISSUE THREAD

**Issue by RainC7** [libnyanpasu/clash-nyanpasu#2152]
### 复现步骤 / Step to reproduce

1. 使用v1.6.1安装系统服务（实际上没有安装成功）
2. 更新到dev版本
3. 尝试卸载

### 预期行为 / Expected behavior

应该成功被卸载

### 实际行为 / Actual behavior

lynn@Mac MacOS % sudo ./nyanpasu-service uninstall
2024-12-06T10:25:03.005510Z  INFO nyanpasu_service/src/cmds/uninstall.rs:23: service already stopped, so we can uninstall it directly
2024-12-06T10:25:03.009380Z ERROR nyanpasu_service/src/main.rs:42: Error: IO {
    source: Os {
        code: 2,
        kind: NotFound,
        message: "No such file or directory",
    },
    backtrace: <disabled>,
}

### 环境信息 / Environment information

> ----------- System -----------
> OS: MacOS 15.1  24.1.0
> Arch: arm64
> ----------- Device -----------
> CPU: Apple M4 @ 0.00GHz x 10
> Memory: 24 GiB
> ----------- Core -----------
> mihomo: `Mihomo Meta v1.18.10 darwin arm64 with go1.23.2 Sun Nov  3 09:19:49 UTC 2024
> Use tags: with_gvisor`
> clash-rs-alpha: `clash-rs 0.7.3-alpha+sha.e711fd9`
> clash-rs: `clash-rs 0.7.3`
> clash: `Clash n2023-09-05-gdcc8d87 darwin arm64 with go1.21.0 Tue Sep  5 14:20:06 UTC 2023`
> mihomo-alpha: `Mihomo Meta alpha-d6b496d darwin arm64 with go1.23.3 Wed Dec  4 00:54:22 UTC 2024
> Use tags: with_gvisor`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 2.0.0-alpha+9d45eec
> Commit Hash: 9d45eec2a44ffb2126bdf5cdbc4eeff07676e3e5
> Commit Author: GitHub
> Commit Date: 2024-12-05T22:19:45.000Z
> Build Date: 2024-12-06T00:42:19.458Z
> Build Profile: Nightly
> Build Platform: aarch64-apple-darwin
> Rustc Version: rustc 1.85.0-nightly (acabb5248 2024-12-04)
> Llvm Version: 19.1
> 

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日志，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues) and [FAQ](https://nyanpasu.elaina.moe/others/faq)
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make multiply issue for multiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
重启一下系统就好了。macOS 的 launchctl 问题导致不重启系统不能正确清理。

**Comment by greenhat616** [comment]
给服务模式，和安装脚本都做了一下修复，应该没有问题了
