### ISSUE TITLE
macOS (Apple M4) 调整窗口大小导致应用崩溃

### ISSUE THREAD

**Issue by StageGuard** [libnyanpasu/clash-nyanpasu#2207]
### 复现步骤 / Step to reproduce

1. 打开 Clash Nyanpasu
2. 用鼠标调整窗口大小

### 预期行为 / Expected behavior

正常调整窗口大小

### 实际行为 / Actual behavior

应用崩溃

### 应用日志 / App logs

系统反馈的崩溃日志 [crash.log](https://github.com/user-attachments/files/18133961/crash.log)
应用日志 [clash-nyanpasu.2024-12-14.app.log](https://github.com/user-attachments/files/18133974/clash-nyanpasu.2024-12-14.app.log)

### 环境信息 / Environment information

> ----------- System -----------
> OS: MacOS 15.2  24.2.0
> Arch: arm64
> ----------- Device -----------
> CPU: Apple M4 @ 0.00GHz x 10
> Memory: 32 GiB
> ----------- Core -----------
> clash-rs-alpha: `clash-rs 0.7.3-alpha+sha.e711fd9`
> mihomo-alpha: `Mihomo Meta alpha-c7fc93d darwin arm64 with go1.23.3 Thu Dec 12 11:02:54 UTC 2024
> Use tags: with_gvisor`
> clash-rs: `clash-rs 0.7.3`
> mihomo: `Mihomo Meta v1.19.0 darwin arm64 with go1.23.3 Mon Dec  9 09:51:17 UTC 2024
> Use tags: with_gvisor`
> clash: `Clash n2023-09-05-gdcc8d87 darwin arm64 with go1.21.0 Tue Sep  5 14:20:06 UTC 2023`
> ----------- Build Info -----------
> App Name: clash-nyanpasu
> App Version: 0.1.0
> Pkg Version: 2.0.0-alpha+34e464d
> Commit Hash: 34e464db8ed8349c3195eb2b00bf34458f795e02
> Commit Author: GitHub
> Commit Date: 2024-12-13T23:39:23.000Z
> Build Date: 2024-12-14T00:42:02.922Z
> Build Profile: Nightly
> Build Platform: aarch64-apple-darwin
> Rustc Version: rustc 1.85.0-nightly (d4025ee45 2024-12-12)
> Llvm Version: 19.1
> 

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日志，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues) and [FAQ](https://nyanpasu.elaina.moe/others/faq)
- [X] 您已搜索过 [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/libnyanpasu/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make multiply issue for multiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
看起来像是 macOS 直接杀死应用造成的崩溃，日记里似乎没看到相关的崩溃信息。稍晚我 bump 一下 tauri 看看能不能缓解这个问题吧。

**Comment by monk-after-90s** [comment]
用的是哪个release啊？我这Mac mini4根本装不起啊

**Comment by greenhat616** [comment]
<img width="1000" alt="image" src="https://github.com/user-attachments/assets/19582098-5abb-440b-a204-250e38a39347" />
15.2 可以复现这个问题，推测为上游 Tauri 的问题

**Comment by greenhat616** [comment]
已修复问题。
https://github.com/libnyanpasu/clash-nyanpasu/commit/ae9fb0c6fe2a9877fff34fe8

https://github.com/user-attachments/assets/615bece1-2054-4836-9ec8-c17dd3b4550d
