### ISSUE TITLE
内核端口9090占用切换

### ISSUE THREAD

**Issue by balrogsxt** [LibNyanpasu/clash-nyanpasu#242]
### 需求 / Requirement

内核端口9090被占用的情况下,内核切换到其他随机端口或提示报错信息

### 建议实现 / Suggested implements

建议实现里下写提供三个选项,表示这个是用户可三选一
1.随机端口
2.固定端口(报错提示)
3.固定端口,被占用后使用随机端口

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.2

### 是否为 Pre-release / Is pre-release version

5c486df

### 自查步骤 / Verify steps

- [x] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by rjys365** [comment]
另外默认没有core secret会不会有安全问题呢？要不要随机生成一个作为默认值？
