### ISSUE TITLE
添加延迟测试 Ping 和 TCPPing 切换支持

### ISSUE THREAD

**Issue by dogpem** [libnyanpasu/clash-nyanpasu#274]
### 复现步骤 / Step to reproduce

使用默认的延迟测试，测出来值的是 Ping 值，而不是 http 连通延迟
![图片](https://github.com/keiko233/clash-nyanpasu/assets/115675753/3af575e1-e9b9-44ea-893c-637073af84b1)

### 预期行为 / Expected behaviour

使用默认的延迟测试，显示的值为 Ping 值

### 实际行为 / Actual Behaviour

显示http延迟测试值

### 应用日志 / App logs

Trance日志在附件(启动程序后，进行一次延迟测试并退出软件)

### 备注 / Addition details

[2024-01-17-1424.log](https://github.com/keiko233/clash-nyanpasu/files/13959457/2024-01-17-1424.log)

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.2

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windows 10

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by dogpem** [comment]
已测试更换测试链接，结果不变

**Comment by greenhat616** [comment]
能确认 1.4.0 1.4.1 是 http 测速吗

**Comment by dogpem** [comment]
无法，但是印象中一直是 http 测速，有什么办法修改吗？ 谢谢 QAQ

**Comment by greenhat616** [comment]
之后加个选项吧。等我有空的时候看看。

**Comment by keiko233** [comment]
应该不是ping值吧，内核一直都是http延迟，可能是因为默认开启了unified-delay 的原因所以看起来像 ping值 

https://github.com/LibNyanpasu/clash-nyanpasu/commit/eafb0274a7736211cc74b93bcd3a6accc8a6e6ab

如果不想要这个功能可以去设置的clash字段自行关闭一下
