### ISSUE TITLE
win11 家庭版无法安装

### ISSUE THREAD

**Issue by shuaixiaomi** [LibNyanpasu/clash-nyanpasu#283]
### 复现步骤 / Step to reproduce

Clash.Nyanpasu_1.4.1_x64-setup
![image](https://github.com/keiko233/clash-nyanpasu/assets/77660384/ba049765-c0e5-4f55-9c7a-d5424605507f)
Clash.Nyanpasu_1.4.1_x64_zh-CN
![image](https://github.com/keiko233/clash-nyanpasu/assets/77660384/aa8500be-cb17-4d08-9f26-4162df3d8173)

### 预期行为 / Expected behaviour

正常安装

### 实际行为 / Actual Behaviour

无

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.1

### 是否为 Pre-release / Is pre-release version

yes

### 操作系统及版本 / OS version

win11 家庭版

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
请提供系统版本以及架构信息，以及为何不使用 1.4.2，pre-release 进行测试

**Comment by shuaixiaomi** [comment]
> 请提供系统版本以及架构信息，以及为何不使用 1.4.2，pre-release 进行测试
系统版本：10.0.22621 暂缺 build 22621
系统架构：x64-based PC
看 #190 win11用问题，才用1.4.1

**Comment by greenhat616** [comment]
请尝试 1.4.3

**Comment by shuaixiaomi** [comment]
> 请尝试 1.4.3

一样的报错

**Comment by greenhat616** [comment]
确认 webkit2 是否正确安装了？

还不行的话修复下系统看看吧。
