### ISSUE TITLE
Windows 下启动 Nyanpasu 出现 PanicInfo 包含 `FailedToReceiveMessage`

### ISSUE THREAD

**Issue by toisard** [LibNyanpasu/clash-nyanpasu#307]
### 复现步骤 / Step to reproduce

启动后

### 预期行为 / Expected behaviour

弹出错误窗口

### 实际行为 / Actual Behaviour

![屏幕截图 2024-01-22 105523](https://github.com/keiko233/clash-nyanpasu/assets/27621397/1246ab1c-13f4-49ae-8187-d7ab805b682c)

### 应用日志 / App logs

[Clash Nyanpasu.exe.3872.dmp](https://github.com/keiko233/clash-nyanpasu/files/14004202/Clash.Nyanpasu.exe.3872.dmp)

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.3

### 是否为 Pre-release / Is pre-release version

20bc733

### 操作系统及版本 / OS version

Windows 11

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
能否提供下应用目录下的日记？以及能否尝试下 pre-release 版本，谢谢！

**Comment by wilsonjor** [comment]
143已经不支持Win7了，新内核不支持Win7，可以用旧内核替换

**Comment by greenhat616** [comment]
最新的开发版能复现吗？我们准备发最后一次补丁版本了，之后开始推 1.5.x。

**Comment by NuoFang6** [comment]
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/137974286/7bc27383-8af6-408d-a19f-2db2aec87c71)
相同问题，pre-release版，win11企业，无法启动程序

**Comment by toisard** [comment]
> ![image](https://private-user-images.githubusercontent.com/137974286/309707952-7bc27383-8af6-408d-a19f-2db2aec87c71.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1MDk4ODQsIm5iZiI6MTcxMjUwOTU4NCwicGF0aCI6Ii8xMzc5NzQyODYvMzA5NzA3OTUyLTdiYzI3MzgzLThhZjYtNDA4ZC1hMTlmLTJkYjJhZWM4N2M3MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwN1QxNzA2MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOWM1YTA2OGVlMTNjMDJiMDY0ZDkxZDFkNjJiYTUyZWIzODUzNDcyMzlhMTUyZjAyZTgwMjNmM2MzMGNjMmUwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.d3R9E24yK9LVzYuZt009jYVOZFoH0nXV49uK3xJ5gq4) 相同问题，pre-release版，win11企业，无法启动程序 —————— 我的问题已解决。 解决方法：想办法重装 Microsoft Edge WebView2 Runtime

解决了，果然是Microsoft Edge WebView2 Runtime的问题

**Comment by 4o3F** [comment]
Should be tracked in upstream Tauri

**Comment by aliuq** [comment]
windows 11 可以执行下面命令

```powershell
winget install Microsoft.EdgeWebView2Runtime
```
