### ISSUE TITLE
配置文件不包含discord时无法正常被country.mpmm、geoip等分配至代理，而是强制被IPCIDR分配至直连

### ISSUE THREAD

**Issue by beserah** [LibNyanpasu/clash-nyanpasu#313]
### 复现步骤 / Step to reproduce

打开系统代理，在规则模式下访问discord.com

### 预期行为 / Expected behaviour

通过country.mpmm等，自动将discord相关域名/IPmatch至需要代理而非Direct

### 实际行为 / Actual Behaviour

![QQ截图20240123143022](https://github.com/keiko233/clash-nyanpasu/assets/46437378/598166f0-1f40-4701-b143-45d09a2d1351)
如图将discord错误分至direct

### 应用日志 / App logs

[TCP] dial DIRECT (match IPCIDR/127.0.0.0/8) 127.0.0.1:51627 --> discord.com:443 error: dial tcp 127.0.0.1:443: connectex: No connection could be made because the target machine actively refused it.

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.4

### 是否为 Pre-release / Is pre-release version

是

### 操作系统及版本 / OS version

WINDOWS10

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by Miracle-Sakuno** [comment]
直接加入Discord规则让它走代理不就好了

**Comment by greenhat616** [comment]
> 直接加入Discord规则让它走代理不就好了

他那个 discord 解析成 127.0.0.1 了。感觉要么是 DNS 问题，要么就是本地开了 steam++这种东西。

**Comment by S-T-eve** [comment]
这个我也遇到过，不知道为毛YouTube被解析成192.168.******，然后就直连了
我的解决办法是dns字段里加上`use-hosts: false`，然后把出问题域名的代理规则置顶，直连规则往下排，然后就解决了
解析成127.***大概率是非正常退出反代工具结果hosts没清，毕竟如果是单纯没关反代工具是直接和clash的系统代理冲突然后一堆东西连不上

**Comment by beserah** [comment]
看了一下还真是host没清，不过衍生问题是，verge系是不是好像目前都没啥比较好办法可以绕过host代理（

**Comment by greenhat616** [comment]
绕过 Host 的理由是？

**Comment by beserah** [comment]
兼容反代工具（
