### ISSUE TITLE
无法访问ipv6网站

### ISSUE THREAD

**Issue by LiXiaYu** [LibNyanpasu/clash-nyanpasu#315]
### 复现步骤 / Step to reproduce

关闭软件时，可以访问ipv6网站。
打开软件后，无法访问ipv6网站。

### 预期行为 / Expected behaviour

在打开ipv6后，应当能够正常的访问ipv6网站。

### 实际行为 / Actual Behaviour

实际上，无法通过ipv6地址正常访问外网，无法通过192.18.0.2 dns获取到正确的ipv6地址。

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.2

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windows 11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
这个是 DNS 关闭 ipv6 解析了，你可以研究一下 clash 内核的配置。让他允许ipv6 解析。
