### ISSUE TITLE
允许自定义修改应用目录

### ISSUE THREAD

**Issue by youwei5683** [LibNyanpasu/clash-nyanpasu#323]
### 复现步骤 / Step to reproduce

Clash.Nyanpasu_1.4.3_x64_portable如何修改应用目录

### 预期行为 / Expected behaviour

在Clash.Nyanpasu.exe 目录内新建了.config 文件夹并不能修改应用目录

### 实际行为 / Actual Behaviour

Clash.Nyanpasu_1.4.3_x64_portable如何修改应用目录

### Clash Nyapasu 版本号 / Clash Nyapasu

最新版

### 是否为 Pre-release / Is pre-release version

最新版

### 操作系统及版本 / OS version

win10

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
Portable 无修改注册表的操作，如果应用目录还需要修改，请问，我该通过何种手段来让喵帕斯确认从哪读取配置？

另，目前这个功能是安装版也不支持的，如果要实现自定义用户目录，势必要写入注册表，且修改应用目录后，必须有个迁移逻辑来把之前的配置都迁移过去。

因此，这个功能优先级并不高，至少是低于我们从 `clash-verge` 迁移至 `clash-nyanpasu` 的优先级的。换句话说，这个功能起码要拖到 `1.5.x`。

**Comment by leic4u** [comment]
看到已经到 v1.5.x了，我也有类似需求，但我只需要配置文件（订阅文件）支持自定义目录即可。

解释下为什么会有这个需求：

因为我是手写的配置文件，但是又有多台设备。当我修改了配置文件后，我必须在每台设备上都去做一次修改，这有点太难受了。
目前我是通过把整个 Portable 版安装到到 Onedrive 目录下进行同步的，多台设备同时开启时，又会出现同步问题。

请开发者大佬们酌情考虑下。

**Comment by greenhat616** [comment]
今天稍晚提交个补丁，届时各位测试一下哈。（不支持 portable）

**Comment by leic4u** [comment]
> 今天稍晚提交个补丁，届时各位测试一下哈。（不支持 portable）

感谢开发者大佬，看到 PR 已经 merge 了，release 后立即测试。

**Comment by greenhat616** [comment]
明早可以试一下，开发版每天上午九点左右编译。
