### ISSUE TITLE
请问fedora下面用AppImage能够有开机自启动选项么？

### ISSUE THREAD

**Issue by golovo** [libnyanpasu/clash-nyanpasu#370]
### 需求 / Requirement

希望添加开机自启动选项，谢谢。

### 建议实现 / Suggested implements

flathub包要不考虑做一个？毕竟这种发行版比较主流了。

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.4

### 是否为 Pre-release / Is pre-release version

no

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
flatpak 上游还未支持
https://github.com/tauri-apps/tauri/issues/4402

自动启动似乎不是 AppImage 的功能吧，你可以试试加一个 desktop 文件，处理一下

**Comment by greenhat616** [comment]
> > flatpak 上游还未支持 [tauri-apps/tauri#3619](https://github.com/tauri-apps/tauri/issues/3619)
> > 自动启动似乎不是 AppImage 的功能吧，你可以试试加一个 desktop 文件，处理一下
> 
> flatpak 不是不能支持，我也可以来帮忙打包（之前尝试过并且除了个别需要提权的功能以外成功运行，连设置系统代理的功能都可以用），但是不想打，并且未来的 tauri v2 未必会支持 flatpak ， rpm 倒是有戏。
> 
> 主要原因有3
> 
> 1 项目用的是 pnpm ，flathub 官方的 Sdk 不支持 pnpm ，所以只能解压 deb 包 [flatpak/flatpak-builder-tools#383](https://github.com/flatpak/flatpak-builder-tools/issues/383) 2 GNOME Runtime 里的 webkit2gtk 版本跟目前的 tauri v1 不兼容，所以要编译一个能用的旧版 webkit2gtk ，这也太变态了，官方的 flathubbot 要编译两个多小时才好。 3 clash-rs 内核我在 flatpak 还打不出来，相关 issue [flatpak/flatpak-builder-tools#367](https://github.com/flatpak/flatpak-builder-tools/issues/367)

看来 flatpak 还不堪大用。此外，flatpak 没办法直接打包 binary 么？

提权问题看来在 AppImage 这些免安装环境都存在。之后得给内核更新器这种功能加上feature flag，允许关闭了。

**Comment by madoka773** [comment]
> 看来 flatpak 还不堪大用。此外，flatpak 没办法直接打包 binary 么？

可以，也能用，但是我是想在flatpak提供的sdk和环境进行源码编译，目前flatpak提供的工具做不到

**Comment by madoka773** [comment]
另外如果应用想上架flathub商店的话最好还需要linux arm版本，希望以后会有

**Comment by greenhat616** [comment]
现在可以测试一下，之前的难点是 rquickjs 不支持 Linux arm64，目前已经提供了 binding，可以尝试构建下看看了。



发自我的iPhone


------------------ 原始邮件 ------------------
From: madoka773 ***@***.***&gt;
发送时间: 02/15/2024, 23:23
To: LibNyanpasu/clash-nyanpasu ***@***.***&gt;
抄送: Jonson Petard ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [LibNyanpasu/clash-nyanpasu] 请问fedora下面用AppImage能够有开机自启动选项么？ (Issue #370)





 
另外如果应用想上架flathub商店的话最好还需要linux arm版本，希望以后会有

**Comment by greenhat616** [comment]
👋目前已经针对 Linux 下移植了一批修复补丁，此外对于 AppImage 自启动请参考 <https://wiki.archlinux.org/title/Autostarting> 下 KDE、Gnome 自启动一节。

关于 Flatpak 请新开一个 issue 方便追踪，谢谢！
