### ISSUE TITLE
连接里的过滤条件希望加上对进程名称的过滤

### ISSUE THREAD

**Issue by bakasine** [LibNyanpasu/clash-nyanpasu#377]
### 需求 / Requirement

连接里的过滤条件希望加上对进程名称的过滤

### 建议实现 / Suggested implements

过滤条件只对连接名称有效, 希望再加上进程名称

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.4

### 是否为 Pre-release / Is pre-release version

no

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
之后考虑做个 Tag 做匹配支持。目前先做成全过滤的情况。

**Comment by greenhat616** [comment]
Closeing it. https://github.com/LibNyanpasu/clash-nyanpasu/commit/d277e477dfeb3faac9c07bd289d8e71d7d4df1cf

**Comment by SUGARYeUNGG** [comment]
迫切需要
