### ISSUE TITLE
启动程序报错，以一种访问权限不允许的方式做了一个访问套接字的尝试

### ISSUE THREAD

**Issue by Soniceso** [LibNyanpasu/clash-nyanpasu#379]
### 复现步骤 / Step to reproduce

启动程序就会出现如下提示
![image](https://github.com/keiko233/clash-nyanpasu/assets/10915608/c78e5084-2db6-4138-afa4-670eea4820c2)
****

### 预期行为 / Expected behaviour

正常启动

### 实际行为 / Actual Behaviour

弹窗报错，点击确认后UI会直接消失，但服务依旧可用，如果不点让报错一直挂着UI也可以正常使用，点了则会直接消失。

### 应用日志 / App logs

2024-02-05 09:13:46 ERROR - panic hook: PanicInfo { payload: Any { .. }, message: Some(error binding to 127.0.0.1:33331: error creating server listener: 以一种访问权限不允许的方式做了一个访问套接字的尝试。 (os error 10013)), location: Location { file: "C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\warp-0.3.6\\src\\server.rs", line: 217, col: 27 }, can_unwind: true, force_no_backtrace: false }

### 备注 / Addition details

测试版一样会报错

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.4

### 是否为 Pre-release / Is pre-release version

eb61d94

### 操作系统及版本 / OS version

WIN11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
我想确认一下，
杀毒软件有拦截日记么？
是否同时打开了 verge？

**Comment by Soniceso** [comment]
杀软没啥问题的，一起用了有一段时间了，就昨天电脑开机时候刚出现的问题。verge是没开的，昨天试着像之前UI崩溃那样直接把配置文件删了重装又好了，就很奇怪。

**Comment by greenhat616** [comment]
有没有开启 HyperV？如果没有的话，试着用管理员权限启动喵帕斯看看。

1.5.0 我把 Verge 利用端口进行单例检测的特性砍掉，改成基于 pid 的好了。

**Comment by Soniceso** [comment]
Hyper-V确实没开，因为要用WSA兼容性有些问题就没开，删干净重装了一次已经好了。

**Comment by easyinplay** [comment]
1.4.6遇到同样的问题
