### ISSUE TITLE
[Feature] 使用弹性动画库，提升部分动画效果

### ISSUE THREAD

**Issue by greenhat616** [LibNyanpasu/clash-nyanpasu#39]
可以引入 [framer-motion](https://www.framer.com/motion/)，来构建更自然的过度。
比如说 Modal 组件，部分按钮的交互逻辑，以及可以戳一戳的 Logo 🐱 

P.S 是不是可以考虑往 outline 风格过度，以向 Material You 风格迁移？虽然 Material UI 6（Material You 风格化） 的进度不容乐观：https://github.com/mui/material-ui/issues/29345

PP.SS: 或许也可以引入譬如 UnoCSS、Tailwindcss 改善布局的体验

Blocked: https://github.com/mui/material-ui/issues/36695

**Comment by keiko233** [comment]
1. 当然可以添加motion库来实现动画，欢迎实现；
2. 后续风格会往material you发展，mui next进度缓慢目前我也不好拿定主意要不要使用；
3. 至于第三方css库也可以添加但是出于两点不太考虑：
- 一是verge整体框架基本成型，使用手写样式已经能够满足目前的需求；
- 二是后期如果mui next开发完成迁移的工作量可能会更大

**Comment by greenhat616** [comment]
> 1. 当然可以添加motion库来实现动画，欢迎实现；
> 
> 2. 后续风格会往material you发展，mui next进度缓慢目前我也不好拿定主意要不要使用；
> 
> 3. 至于第三方css库也可以添加但是出于两点不太考虑：
> 
> - 一是verge整体框架基本成型，使用手写样式已经能够满足目前的需求；
> 
> - 二是后期如果mui next开发完成迁移的工作量可能会更大

确实，如果考虑到迁移的话，现阶段确实弊大于利。后期迁移后，可以考虑配合 CSS Modules + @apply 的用法。实操下，感觉复用度还可以。
