### ISSUE TITLE
ArchLinux下通过AppimageLauncher安装无法正常使用

### ISSUE THREAD

**Issue by xmh0511** [libnyanpasu/clash-nyanpasu#402]
### 复现步骤 / Step to reproduce

直接运行appimage 或 通过AppImageLauncher安装appimage可执行文件

### 预期行为 / Expected behaviour

正常使用

### 实际行为 / Actual Behaviour

代理无效，无法提升clash内核root权限`Failed to set capabilities on file '/tmp/.mount_clash-zQXFZn/usr/bin/mihomo': Permission denied `

切换到设置，提示`Failed to get core version: failed to get core version `

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.4

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

linux， manjaro, archlinux

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by 4o3F** [comment]
Arch下请尝试添加archlinuxcn的aur后通过[Stable Release](https://aur.archlinux.org/packages/clash-nyanpasu) / [Binary Package](https://aur.archlinux.org/packages/clash-nyanpasu-bin)安装

**Comment by madoka773** [comment]
你用sudo运行appimage就不会了

**Comment by xmh0511** [comment]
> 你用sudo运行appimage就不会了

sudo没法用AppimageLauncher合并到系统应用中

**Comment by Kimiblock** [comment]
> Arch下请尝试添加archlinuxcn的aur后通过[Stable Release](https://aur.archlinux.org/packages/clash-nyanpasu) / [Binary Package](https://aur.archlinux.org/packages/clash-nyanpasu-bin)安装

AUR 是用户软件打包脚本的聚集地, 不是仓库.

Nyanpasu 也没有进入 CN 仓库.

**Comment by greenhat616** [comment]
v1.6.0 已经针对 AppImage 做了一些修复。
目前存在的限制请参考此节：https://nyanpasu.elaina.moe/zh-CN/tutorial/install#appimage
