### ISSUE TITLE
[Feature]可以提供Windows on arm的版本吗

### ISSUE THREAD

**Issue by luoquan-30** [libnyanpasu/clash-nyanpasu#41]
**需要一个Windows on arm的版本**
十分感谢，或者可以请教一下如何自己进行编译

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by keiko233** [comment]
我没有arm测试环境，可以自己修改check.ts添加支持后编译

**Comment by greenhat616** [comment]
`clash-rs` 还未提供 win-arm64 版本，你可以去 https://github.com/Watfaq/clash-rs/issues 要求一下。
Tauri 的 win arm 编译可以参考此节 https://tauri.app/v1/guides/building/windows#building-for-32-bit-or-arm
`pnpm build --target aarch64-pc-windows-msvc`

**Comment by greenhat616** [comment]
https://github.com/Watfaq/clash-rs/issues/210

**Comment by uprprc777** [comment]
upvote, need this too

**Comment by keiko233** [comment]
close & tracked on https://github.com/LibNyanpasu/clash-nyanpasu/issues/41

**Comment by greenhat616** [comment]
已经在开发版中支持
