### ISSUE TITLE
[BUG]用触摸板使用webview后退手势时触发快捷手势

### ISSUE THREAD

**Issue by NBWSLeee** [LibNyanpasu/clash-nyanpasu#44]
**Describe the bug**
[BUG]用触摸板使用webview后退手势时触发快捷手势

**Screenshots**
![Snipaste_2023-12-03_12-25-47](https://github.com/keiko233/clash-nyanpasu/assets/93495737/cc488307-5d55-4619-a35b-1f43a569b431)

**Information**
- OS: Windows 11
- Clash Nyanpasu Version: 1.4.0
- Clash Core: Clash Meta

**Comment by greenhat616** [comment]
这个似乎是 Webview2 的问题？
