### ISSUE TITLE
clash-rs 内核 切换节点时不会自动关闭链接

### ISSUE THREAD

**Issue by ningsibuqu** [libnyanpasu/clash-nyanpasu#445]
### 复现步骤 / Step to reproduce

切换至clash-rs 内核

切换节点 例如从 日本1 切换到 日本2

活动链接没有自动断开 

mihomo premium 都正常断开全部活动链接 

### 预期行为 / Expected behaviour

预期在连接那里会关闭全部链接 然后切换到日本2

### 实际行为 / Actual Behaviour

活动链接没有自动断开

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.5

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windows 10

### 自查步骤 / Verify steps

- [] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
试一下 dev build 看看？

**Comment by ningsibuqu** [comment]
> 试一下 dev build 看看？

一样 切换到新加坡后到连接里查看 日本连接没自动断开 依旧保留
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/51028975/914d8480-e7c1-4e00-81bd-195ca35e255d)

**Comment by greenhat616** [comment]
稍晚如果我的笔电正常的话。我调查一下看看是上游内核的问题，还是这里的问题。

**Comment by ningsibuqu** [comment]
> 稍晚如果我的笔电正常的话。我调查一下看看是上游内核的问题，还是这里的问题。

而且我发现运行一段时间后切换节点，想手动点击「关闭全部 」关闭链接 是没有反应的

**Comment by greenhat616** [comment]
看起来像是内核的 api 实现问题。

我的笔电故障了，目前还没有线索确定到底是何原因导致的。

**Comment by ningsibuqu** [comment]
> 看起来像是内核的 api 实现问题。
> 
> 我的笔电故障了，目前还没有线索确定到底是何原因导致的。

https://github.com/LibNyanpasu/clash-nyanpasu/issues/454

我在切换到开发版的时候也遇到一样的问题

**Comment by ningsibuqu** [comment]
> 看起来像是内核的 api 实现问题。
> 
> 我的笔电故障了，目前还没有线索确定到底是何原因导致的。

话说可以复现吗？

**Comment by greenhat616** [comment]
cc @4o3F

**Comment by 4o3F** [comment]
我这里使用1.4.5无法复现，但是最新开发版没法切clash-rs内核....

**Comment by ningsibuqu** [comment]
> 我这里使用1.4.5无法复现，但是最新开发版没法切clash-rs内核....

测试了1.4.6最新开发版，现在情况是这样，选择切换节点后还得切换到其他页面（连接）再切换回代理，才能限时切换成功，但先前的连接没有自动关闭，反复操作几次后，最后点击连接页面中的关闭连接，是完全没有反应了

https://github.com/LibNyanpasu/clash-nyanpasu/assets/51028975/6d25c5d8-09b6-484c-a21c-d2e1fb89985e

**Comment by ningsibuqu** [comment]
1.5.0 问题依旧

**Comment by ningsibuqu** [comment]
[v0.1.15](https://github.com/Watfaq/clash-rs/releases/tag/v0.1.15)

手动更新了内核，也一样

**Comment by greenhat616** [comment]
您好，FAQ 已经更新，能否将内核日记级别修改到 `Debug`，App Log level 修改到 `Trace`。然后将日记文件提交上来？

<https://nyanpasu.elaina.moe/zh-CN/others/faq.html#_2-clash-nyanpasu-%E5%BA%94%E7%94%A8-%E6%97%A5%E8%AE%B0%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C>

**Comment by ningsibuqu** [comment]
> 您好，FAQ 已经更新，能否将内核日记级别修改到 `Debug`，App Log level 修改到 `Trace`。然后将日记文件提交上来？
> 
> https://nyanpasu.elaina.moe/zh-CN/others/faq.html#_2-clash-nyanpasu-%E5%BA%94%E7%94%A8-%E6%97%A5%E8%AE%B0%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C

我不确定有木有敏感信息 先发你邮箱了？谢谢

**Comment by ningsibuqu** [comment]
> 您好，FAQ 已经更新，能否将内核日记级别修改到 `Debug`，App Log level 修改到 `Trace`。然后将日记文件提交上来？
> 
> https://nyanpasu.elaina.moe/zh-CN/others/faq.html#_2-clash-nyanpasu-%E5%BA%94%E7%94%A8-%E6%97%A5%E8%AE%B0%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C

有收到我发的日记文件吗  谢谢

**Comment by greenhat616** [comment]
切换内核不关闭链接应该是 202 状态码导致的。
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/41122242/84c0d12b-2ed8-4429-b4e6-2e7acdced175)
Nyanpasu 认为 202 是不正确的状态码，我们这里之后做一下处理，或者和 clash-rs 作者沟通一下，修正这个问题。

![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/41122242/301ad686-5438-4656-a735-be6e0474c622)
链接那里 close 之后 connection 不清理，目前判断下来应该是 clash-rs 的 bug 居多，在不修改 config 和 rule selector 下关闭是正常的，但是切换之后会出现问题。当然也不排除是前端报错后，导致一直无法出发刷新。


这个等我这段时间忙完之后，看看能不能去上游修复这个问题吧。最近是没时间了。

**Comment by greenhat616** [comment]
看起来最新 Clash Rust 版本已经修复这个问题了。如果还有问题请重新创建问题。
