### ISSUE TITLE
GUI不明原因崩溃并导致系统右键菜单异常

### ISSUE THREAD

**Issue by S-T-eve** [LibNyanpasu/clash-nyanpasu#454]
### 复现步骤 / Step to reproduce

复现方法不明确，打开Clash Nyanpasu后一段时间就出现问题，最早出现在正常使用中edge浏览器异常崩溃，后续发现系统其他功能如explorer的右键窗口无法弹出，通过任务管理器关闭Clash Nyanpasu并重启explorer后恢复正常。
已排除由core导致的可能，并与Verge对照组确定问题由Clash Nyanpasu GUI导致，疑似与托盘图标右键快速切换功能有关

### 预期行为 / Expected behaviour

正常运行无异常

### 实际行为 / Actual Behaviour

如上述

### 应用日志 / App logs

log文件异常巨大
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/53549980/e93f9f8b-ab1a-4621-8010-34e89010f150)
明确的异常内容如下：
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/53549980/dc78e695-841a-47e9-8b26-92f70bcfc4a7)
并且出现此报错前都有巨长的`DEBUG [clash_verge::core::tray::proxies] - proxies info:`
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/53549980/f6457991-a60b-47c8-93f5-f41e7786afc5)

### 备注 / Addition details

可以的话，麻烦添加给每次会话的log文件前几行输出一下当前会话的GUI和core版本号等基本信息的功能，便于排除

### Clash Nyapasu 版本号 / Clash Nyapasu

v1.4.6-alpha

### 是否为 Pre-release / Is pre-release version

2a19c35

### 操作系统及版本 / OS version

Windows 10.0.19045.4046

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
按理说频繁更新托盘不因造成系统耗尽内存的，虽然确实有性能问题。我目前没做 diff 算法，因此每十秒会固定刷新一下托盘。

> 如果是这个原因导致的话， Tray 的坑太深了。

**Comment by easyinplay** [comment]
遇到同样的问题

**Comment by greenhat616** [comment]
今晚我加个简易的基于 Hash 的 Diff 算法看看对这个问题有没有帮助吧。

**Comment by S-T-eve** [comment]
又崩了一次，这次情况明确多了
首先开启了Clash Nyanpasu正常使用并打开浏览器上网，然后edge整个窗体突然黑掉无法作任何操作，同时桌面和开始菜单右键菜单不弹出，桌面图标有鼠标上置高亮但是双击无法打开任何东西，系统托盘右键无菜单弹出，开始菜单可呼出但是打不开任何东西，ctrl+alt+del可呼出但是点击任务管理器无法打开，托盘图标无法呼出右键菜单，托盘图标可呼出Nyanpasu窗体且窗体可点×关闭并且窗体内控件可操作且log正常显示，进入设置页关闭系统代理有反应
由于忘了事先打开任务管理器于是无法关闭，本来打算重启，结果Nyanpasu自己崩了进程退了（mihomo core没崩，在后台），然后除了edge还卡在黑屏无法操作外其他系统功能正常，用任务管理器重启edge后也一切正常

**Comment by greenhat616** [comment]
本质上是系统炸了😂，极大可能是tauri 使用的托盘 api导致的。我们的刷新频率，我印象里是十秒一次（没有 diff 算法的情况下）。

**Comment by greenhat616** [comment]
稍晚请试一下最新的 dev build：https://github.com/LibNyanpasu/clash-nyanpasu/actions/runs/7972764102
谢谢。

**Comment by S-T-eve** [comment]
> 稍晚请试一下最新的 dev build：https://github.com/LibNyanpasu/clash-nyanpasu/actions/runs/7972764102 谢谢。

炸了

**Comment by greenhat616** [comment]
试一下最新的：https://github.com/LibNyanpasu/clash-nyanpasu/actions/runs/7988957087

可不可以延缓（比如一周、一个月）或者完全不触发崩溃。
还不行的话，等我下周写个 Diff 算法，非不要不完全重新刷新，只更新选中部分。

**Comment by S-T-eve** [comment]
物理机直接打不开，进程有了托盘也有了但是窗体不出来，然后报错崩了
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/53549980/af4f6708-f720-4bb3-95c4-24d3c6a36d4e)
`
2024-02-21 21:56:17 ERROR [clash_verge] - panic hook: PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: FailedToReceiveMessage), location: Location { file: "C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tauri-1.6.0\\src\\window.rs", line: 750, col: 48 }, can_unwind: true, force_no_backtrace: false }
`
虚拟机本来挂上了，结果也崩了，老样子右键没反应
66784行log 214mb，2024-02-21 22:35:50-2024-02-21 23:48:53，没什么特别明显的error信息
不确定是我切到虚拟机动了之后进程崩了还是怎样，反正切进去时GUI还在能操作，edge也还在，但是右键菜单已经挂了，然后edge也崩了，右上角叉掉GUI窗体之后呼出来时窗体卡了，一段时间后也崩退进程，GUI挂了之后系统右键浏览器右键啥的就正常了

**Comment by greenhat616** [comment]
这个 panic 是 Tauri 触发的，应该算它内部的 bug。不知道是 Tauri，还是Webview2 的锅子。 你能把日记压缩一下上传到 GitHub 吗？如果存在敏感信息可以去除后发我邮箱。

**Comment by S-T-eve** [comment]
更新到`d4d9ba6`又能正常打开了，然后就照旧崩了
log:[2024-02-22-1337.log.filterDNSline.7z.zip](https://github.com/LibNyanpasu/clash-nyanpasu/files/14370579/2024-02-22-1337.log.filterDNSline.7z.zip)

**Comment by greenhat616** [comment]
日记似乎没啥线索，但是我发现托盘更新依然太频繁了，似乎计算数据 hash 的方式没有用。周日我看看能不能实现个 diff 算法解决这个。



发自我的iPhone


------------------ 原始邮件 ------------------
From: STeveBlocks ***@***.***&gt;
发送时间: 02/22/2024, 15:48
To: LibNyanpasu/clash-nyanpasu ***@***.***&gt;
抄送: Jonson Petard ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [LibNyanpasu/clash-nyanpasu] GUI不明原因崩溃并导致系统右键菜单异常 (Issue #454)





 
更新到d4d9ba6又能正常打开了，然后就照旧崩了
 log:2024-02-22-1337.log.filterDNSline.7z.zip

**Comment by mpbizn** [comment]
Windows 10 专业版 22H2 19045.4046 体验：Windows Feature Experience Pack 1000.19053.1000.0
现在也遇到类似的问题了，表现为鼠标双击桌面图标、单击任务栏和开始菜单某些区域无效，进而卡死导致资源管理器崩溃，键盘徽标键也不能用，只能通过Ctrl+Alt+Del组合注销和重启计算机才能恢复

**Comment by mpbizn** [comment]
系统环境：
Windows 10 专业版 22H2 19045.4046 体验：Windows Feature Experience Pack 1000.19053.1000.0
现在也遇到类似的问题了，表现为鼠标双击桌面图标、单击任务栏和开始菜单某些区域无效，进而卡死导致资源管理器崩溃，键盘徽标键也不能用，只能通过Ctrl+Alt+Del组合注销和重启计算机才能恢复

**Comment by greenhat616** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/actions/runs/8028633901

等这个 build 完成后试一下。应该是解决了 Hash 的问题，以及新增了 Diff 算法。

**Comment by S-T-eve** [comment]
`2024-02-25 04:16:05`挂到`2024-02-25 16:40:00`，883191行log没崩正常用，应该是没问题了
