### ISSUE TITLE
代理组页面空白

### ISSUE THREAD

**Issue by nekokristalo** [LibNyanpasu/clash-nyanpasu#458]
### 复现步骤 / Step to reproduce

打开 Clash Nyanpasu

### 预期行为 / Expected behaviour

代理组页面显示节点

### 实际行为 / Actual Behaviour

代理组页面空白
![屏幕截图 2024-02-19 172431](https://github.com/LibNyanpasu/clash-nyanpasu/assets/105288787/e7472fe7-f466-4582-9a17-d6f3f309dcf3)

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.5

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windows 11 insider preview 10.0.26058.1100

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
有尝试开发版么？
以及，注意：你的日记包含订阅信息，记得移除。

**Comment by nekokristalo** [comment]
> 有尝试开发版么？ 以及，注意：你的日记包含订阅信息，记得移除。

依然无法正常显示代理组，版本为 1.4.6-alpha+2a19c
![屏幕截图 2024-02-19 212610](https://github.com/LibNyanpasu/clash-nyanpasu/assets/105288787/1dd4d4a6-f289-4d05-b845-8f8472900458)
35

**Comment by greenhat616** [comment]
profile 发到我的邮箱，我测试一下看看。
