### ISSUE TITLE
   如何实现 读取并使用电脑hosts 的结果, 以免dns查询

### ISSUE THREAD

**Issue by ffgg536956** [LibNyanpasu/clash-nyanpasu#478]
### 需求 / Requirement

  我想将 某个域名A所对应的 解析出来的ip保存在  Clash 的yaml配置文件中。 这样就免去了后续访问域名A 时的频繁查询dns，请教如何操作？
     如果不能操作的话，   如何实现 读取并使用电脑hosts 的结果, 以免dns查询。
   感谢

### 建议实现 / Suggested implements

   如何实现 读取并使用电脑hosts 的结果, 以免dns查询

### Clash Nyapasu 版本号 / Clash Nyapasu

无

### 是否为 Pre-release / Is pre-release version

否

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by ttyy33** [comment]
use-hosts: true
