### ISSUE TITLE
开启代理和关闭代理时，webview2 占用过高

### ISSUE THREAD

**Issue by Canda15** [libnyanpasu/clash-nyanpasu#483]
### 复现步骤 / Step to reproduce

开启系统代理和关闭代理时，所有chrome内核的浏览器或者使用webview2的程序CPU 占用都飙升。CPU肯定是够得，i9的。
webview2和edge是无法卸载的，所以没有办法重装。尝试过修复webview2也没有用。
尝试过其他基于clash.meta内核的其他gui，也是这样。网上也没搜到相同情况的。以前用verge的时候并没有这个情况。

![图片](https://github.com/LibNyanpasu/clash-nyanpasu/assets/124772373/3ee30a83-aa0f-46fe-bf96-344f8dbc17b0)

### 预期行为 / Expected behaviour

·

### 实际行为 / Actual Behaviour

·

### 应用日志 / App logs

·

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.5

### 是否为 Pre-release / Is pre-release version

`

### 操作系统及版本 / OS version

win10

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
和微软反馈一下。我们修改为使用系统调用修改代理了——解决直接使用PPPOE连接网络时候，系统调用不生效的问题。

**Comment by greenhat616** [comment]
有试过更新系统吗？

https://github.com/LibNyanpasu/clash-nyanpasu/blob/33c28db6de0119190e1dcb1fe92506d6953042e2/backend/sysproxy-rs/src/windows.rs#L199

你可以看到我们只是常规的调用了windows的系统调用。

**Comment by HeroTch** [comment]
Windows	22631.3155 复现 开启关闭代理 任务管理器中所有webview2应用与浏览器共同占用CPU 100%。
因为这个问题我现在使用TUN了

**Comment by greenhat616** [comment]
可以在 windows 11 中复现么？

**Comment by huangyy126** [comment]
1.5版本，勾选桌面右下角图标里面的代理后，代理那里长时间没出现勾选的提示，图标也长时间没有变色，此时CPU占用飙升到100%，风扇呼呼的响。

**Comment by shum-elli** [comment]
最新版本依旧在，我记得在clash verge较早版本的时候也存在这个问题，现在verge也不会有这个问题了，或许可以看看verge的commit记录

**Comment by m430** [comment]
Apple M3 Max 直接把CPU干满，尽快看下这个bug吧

**Comment by hosence** [comment]
同样的问题，用clash verge没这种情况

**Comment by greenhat616** [comment]
尝试重装下 webview2?

**Comment by greenhat616** [comment]
这个问题应该在 1.6.0 中已经修复，如果还有此问题请新开问题讨论。
