### ISSUE TITLE
win10 无反应

### ISSUE THREAD

**Issue by a224327780** [LibNyanpasu/clash-nyanpasu#488]
### 复现步骤 / Step to reproduce

右下角图标点击无反应

webview2 已安装

### 预期行为 / Expected behaviour

右下角图标点击无反应

webview2 已安装

### 实际行为 / Actual Behaviour

右下角图标点击无反应

webview2 已安装

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.5

### 是否为 Pre-release / Is pre-release version

2e94b33

### 操作系统及版本 / OS version

windows10

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
请用开发版测试一下。

**Comment by a224327780** [comment]
> 请用开发版测试一下。

开发版也一样

**Comment by greenhat616** [comment]
日志呢？

**Comment by a224327780** [comment]
这会正常了
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/78008038/8a686028-25ce-405f-816f-a2ff8ac29801)
