### ISSUE TITLE
A panic caused the whole application terminated

### ISSUE THREAD

**Issue by xmh0511** [LibNyanpasu/clash-nyanpasu#489]
### 复现步骤 / Step to reproduce
<img width="266" alt="截屏2024-02-24 17 23 35" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/17973891/934e1c28-35b9-4a87-8b58-a3ca2fbb9502">

### 预期行为 / Expected behaviour

No panic

### 实际行为 / Actual Behaviour

如图

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.4

### 是否为 Pre-release / Is pre-release version

no

### 操作系统及版本 / OS version

macOs12

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
The panic error illustrated that no space left on your disk. and please try the latest nightly version. The bug report of previous stable version shall not get resolved, and will be closed directly next time.

thanks.

**Comment by greenhat616** [comment]
Closing it due to no further action taken.
