### ISSUE TITLE
[BUG]调整窗口大小会导致连接页面统计上传下载和活动连接的文字堆叠

### ISSUE THREAD

**Issue by Soniceso** [LibNyanpasu/clash-nyanpasu#51]
**Describe the bug**
调整窗口大小会导致连接页面统计上传下载和活动连接的文字堆叠

**To Reproduce**
将窗口缩小到一定程度即可复现

**Expected behavior**
横或竖加个滚动条？或者把字体改小一些？反正不应该堆在一起就是了

**Screenshots**
![jietu](https://github.com/keiko233/clash-nyanpasu/assets/10915608/0c27722c-4932-4c61-abf8-1e560eb7220f)

**Information**

- OS: [WIN11]
- Clash Nyanpasu Version: [1.4.0]
- Clash Core: [ Clash Meta]

**Comment by greenhat616** [comment]
我觉得需要修改成卡片样式比较合理。

**Comment by keiko233** [comment]
close https://github.com/LibNyanpasu/clash-nyanpasu/commit/3fd461922344264f5debfc74e6a508248bc7591c
