### ISSUE TITLE
[Feature]主题设置中添加调色板进行调色

### ISSUE THREAD

**Issue by Soniceso** [LibNyanpasu/clash-nyanpasu#53]
目前主题可以通过颜色代码进行主题的个性化设置，但通过颜色代码定制终究是有些麻烦，很多用户并不明确的知道自己喜欢的颜色是什么代码或者想要什么颜色，如果可以增加调色板（与目前代码调色并存）个人认为可以进一步提升主题设置这项功能的易用性，进而鼓励用户对主题进行个性化设置。

**Comment by deepinsc2020** [comment]
这种调色板应用多的是吧   去那边调好了再复制过来 何必重新造轮子
