### ISSUE TITLE
vmess节点，配置的path过长，在clash-nyanpasu下连接测试失败

### ISSUE THREAD

**Issue by deepdream** [LibNyanpasu/clash-nyanpasu#532]
### 复现步骤 / Step to reproduce

该vmess节点使用sing-box\nekobox\v2rayN等客户端连接都是正常的，
然而手搓clash 的配置文件，节点配置的path值较长，
是uuid+“-vm” 
例如：78bb5af6-3a71-4059-8166-ae921a1815f6-vm

### 预期行为 / Expected behaviour

应该能正常连接

### 实际行为 / Actual Behaviour

使用clash Npanpasu客户端，连接测试总是error，
后来将节点的值改短，改为类似"/tjmtjm"的形式，就成功了

### 应用日志 / App logs

客户端日志文件中有这样的错误信息：
 20:05:58 INFO - [clash]: [37mDEBU[0m[2024-03-01T20:05:58.7361418+08:00] Health Checked, proxy: HK-vm-ws-CDN, url: https://cp.cloudflare.com/generate_204, alive: false, delay: 65535 ms uid: {bcbe78d3-f99a-42a6-b876-368f6290e328} 

### Clash Nyapasu 版本号 / Clash Nyapasu

1.4.2

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

win10 2019 ltsc

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
使用的什么内核？有使用过裸核测试吗？

**Comment by keiko233** [comment]
请确保  您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
Closing this issue due to no further actions taken.
