### ISSUE TITLE
[BUG] The core `clash-rs` cannot be used

### ISSUE THREAD

**Issue by xmh0511** [LibNyanpasu/clash-nyanpasu#54]
Configuration group is empty uder the use of `clash-rs`.

The log is
```
ERROR clash_lib::app::profile: failed to read cache file: stream did not contain valid UTF-8, initializing a new one

AT
clash_lib/src/app/profile/mod.rs:119

AT
clash_lib/src/proxy/converters/vmess.rs:28

WARN clash_lib::proxy::converters::vmess: skipping TLS cert verification for 

startERROR:
invalid config: unsupported network: grpc

thread'MAIN'
panicked at clash/src/main.rs:68:6:

called`RESULT::UNWRAP()`
on an `Err` value: InvalidConfig("unsupported network: grpc")

ERROR clash_lib: panic hook: PanicInfo { payload: Any { .. }, message: Some(called `Result::unwrap()` on an `Err` value: InvalidConfig("unsupported network: grpc")), location: Location { file: "clash/src/main.rs", line: 68, col: 6 }, can_unwind: true, force_no_backtrace: false }

AT
clash_lib/src/lib.rs:158
```

**Comment by greenhat616** [comment]
clash-rs 的 GRPC 支持还没完全实现（目前遇到了实现上的一些问题）。
* 目前尝试的两个方法都不是按照 meta、sing 的思路走的。接下来应该会尝试完全复刻 Gun 的。
可以在这两个问题里进行跟踪：
* https://github.com/Watfaq/clash-rs/pull/203 https://github.com/Watfaq/clash-rs/issues/69

**Comment by xmh0511** [comment]
> `clash-rs` 的 **GRPC** 支持还没完全实现（目前遇到了实现上的一些问题）。
> 
>     * 目前尝试的两个方法都不是按照 meta、sing 的思路走的。接下来应该会尝试完全复刻 Gun 的。
> 
> 
> 可以在这两个问题里进行跟踪：
> 
>     * [implement grpc for trojan and vmess Watfaq/clash-rs#203](https://github.com/Watfaq/clash-rs/pull/203) [grpc Watfaq/clash-rs#69](https://github.com/Watfaq/clash-rs/issues/69)

After such two PR had merged, I tried to re-compiler the latest one and replace the compiled `clash-rs` with the original packed one in this release version. The configure group is OK, however, test latency always give the error.

**Comment by greenhat616** [comment]
> > `clash-rs` 的 **GRPC** 支持还没完全实现（目前遇到了实现上的一些问题）。
> > ```
> > * 目前尝试的两个方法都不是按照 meta、sing 的思路走的。接下来应该会尝试完全复刻 Gun 的。
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可以在这两个问题里进行跟踪：
> > ```
> > * [implement grpc for trojan and vmess Watfaq/clash-rs#203](https://github.com/Watfaq/clash-rs/pull/203) [grpc Watfaq/clash-rs#69](https://github.com/Watfaq/clash-rs/issues/69)
> > ```
> 
> After such two PR had merged, I tried to re-compiler the latest code and replace the original packed clash-rs in this release version with the compiled `clash-rs`. The configure group is OK, however, test latency always gives the error.

I tested it in latest dev build, the latency test in `clash-rs` is ok. Can you paste  core and nyanpasu log here?
As far as I'm concerned, It could be `clash-rs` issue, if something wrong shown your log.

**Comment by xmh0511** [comment]
> > > `clash-rs` 的 **GRPC** 支持还没完全实现（目前遇到了实现上的一些问题）。
> > > ```
> > > * 目前尝试的两个方法都不是按照 meta、sing 的思路走的。接下来应该会尝试完全复刻 Gun 的。
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 可以在这两个问题里进行跟踪：
> > > ```
> > > * [implement grpc for trojan and vmess Watfaq/clash-rs#203](https://github.com/Watfaq/clash-rs/pull/203) [grpc Watfaq/clash-rs#69](https://github.com/Watfaq/clash-rs/issues/69)
> > > ```
> > 
> > 
> > After such two PR had merged, I tried to re-compiler the latest code and replace the original packed clash-rs in this release version with the compiled `clash-rs`. The configure group is OK, however, test latency always gives the error.
> 
> ![image](https://private-user-images.githubusercontent.com/41122242/288720308-52823d7a-c6db-42e3-8262-2ef598f9682a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTI3NTAsIm5iZiI6MTcwMTk1MjQ1MCwicGF0aCI6Ii80MTEyMjI0Mi8yODg3MjAzMDgtNTI4MjNkN2EtYzZkYi00MmUzLTgyNjItMmVmNTk4Zjk2ODJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDEyMzQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmMGI5OWI1MDJkNDg2OTM1NzYwZWUxOGE3OWZmZmUzYTVkYTIzNjA2MTZiZDg5YWFiYTYxMzgyYzM0ZTE5YzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U7hOVqJMS2E3sAxWzdMXl7zhdXfQ-p5zVUaMfnf47uM)
> 
> ![image](https://private-user-images.githubusercontent.com/41122242/288720248-52ca9639-8a05-47f3-9938-e26e615889d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTI3NTAsIm5iZiI6MTcwMTk1MjQ1MCwicGF0aCI6Ii80MTEyMjI0Mi8yODg3MjAyNDgtNTJjYTk2MzktOGEwNS00N2YzLTk5MzgtZTI2ZTYxNTg4OWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDEyMzQxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTcwZjdiZmM1ZGU4ZjUwMGNmZDE5NTcwNGNhMmFjYzRmNTc1NWZiN2I2OTUwNzk5NTNjMDY4ZWMzOTYwYmU4Y2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qm3BQ00I1JW3CvIanqLI9sXP-mOcWrgSmIOw_KQZwLk)
> 
> I tested it in latest dev build, the latency test in `clash-rs` is ok. Can you paste core and nyanpasu log here? As far as I'm concerned, It could be `clash-rs` issue, if something wrong shown your log.

![2042733795](https://github.com/keiko233/clash-nyanpasu/assets/17973891/f55d2d9f-c908-4dcc-a563-fa6dd20aef34)


![2865959016](https://github.com/keiko233/clash-nyanpasu/assets/17973891/a709c08a-5482-4539-a4b5-b1cd7723ad00)

**Comment by greenhat616** [comment]
Can upload the latest log file from this dir?
![image](https://github.com/keiko233/clash-nyanpasu/assets/41122242/1f6cb995-3b07-4d15-83bf-d2b844c385c8)

**Comment by xmh0511** [comment]
> Could u upload the latest log file from this dir? ![image](https://private-user-images.githubusercontent.com/41122242/288763508-1f6cb995-3b07-4d15-83bf-d2b844c385c8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIwMDM4MzcsIm5iZiI6MTcwMjAwMzUzNywicGF0aCI6Ii80MTEyMjI0Mi8yODg3NjM1MDgtMWY2Y2I5OTUtM2IwNy00ZDE1LTgzYmYtZDJiODQ0YzM4NWM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA4VDAyNDUzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiMzkwZTgzYzhlOTQ0NGMwYzRhY2U0NjEwZjYyM2E3MjdhMDRlNzJkNmFkMDQ1NzRkZmUxNWI5YTAxMzFmZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LXlFNwtOliZwBPOcTxM_pE_--4zfA6y2B3O5fbs2ORU)

The log has some secret key, it's not safe to upload it here.

**Comment by xmh0511** [comment]
> If you don't mind, you can delete any secret info, then send it to my email.

I sent them to your email.

**Comment by greenhat616** [comment]
> > If you don't mind, you can delete any secret info, then send it to my email.
> 
> I sent them to your email.

I have received logs you sent. I noticed `closed with error crypto error: BAD_DECRYPT` are thrown when you visit sites that should match `Proxy` group. It seems `clash-rs`'s vmess impl issue.

If possible, you can draft a minimal reproduction or post config in your proxies group, with secret removed, and create a issue to `clash-rs`.

**Comment by 4o3F** [comment]
Fixed by clash-rs core
