### ISSUE TITLE
mac新版本提示Failed to create single instance

### ISSUE THREAD

**Issue by utopeadia** [LibNyanpasu/clash-nyanpasu#544]
### 复现步骤 / Step to reproduce

每次开启应用弹窗

### 预期行为 / Expected behaviour

打开app

### 实际行为 / Actual Behaviour

弹窗，点击OK后可以正常使用
![](https://s2.loli.net/2024/03/03/ptuoYNRkgvPwzKi.png)

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.0

### 是否为 Pre-release / Is pre-release version

no

### 操作系统及版本 / OS version

macos 14

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by zhuxining** [comment]
+1

**Comment by lswmxl** [comment]
+1

**Comment by zachzhao1984** [comment]
+1

**Comment by JimmyLX** [comment]
+1

**Comment by AkkunYo** [comment]
+1

**Comment by engureguo** [comment]
有报错，但功能不受影响。我是安装后先运行 `sudo xattr ...` 命令，再打开....

**Comment by hubumulity** [comment]
+1

**Comment by liukaiwen0422** [comment]
i have the same problem,but groups & providers are error.
<img width="1072" alt="Snipaste_2024-03-05_20-38-14" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/53621063/12d97bee-5fff-48c1-841a-bc4424461b2e">
<img width="1072" alt="Snipaste_2024-03-05_20-38-25" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/53621063/46d98c6c-8062-4d86-9bed-265cdf53bf62">

**Comment by 4o3F** [comment]
Fixed in 6a48cf3ca1e678f6fc380f814fa49c991b3816dd

**Comment by Kurt-Shiwz** [comment]
+1，报错关掉后不影响使用
