### ISSUE TITLE
WIN版本中似乎GEOIP规则被跳过了

### ISSUE THREAD

**Issue by how1ewu** [LibNyanpasu/clash-nyanpasu#548]
### 复现步骤 / Step to reproduce

规则文件最后两个分别为GEOIP=CN=直连和final=代理
我尝试访问了解析为大陆服务器的自建网址，但是在win客户端中提示使用了final兜底策略，我尝试了不同客户端发现相同内核并手动更新了geoip文件只有nyanpasu无法使用GEOIP规则。同时我注意到，macos版本nyanpasu不存在这个问题。
我不确定是我的个人问题还是共性问题，发出讨论

### 预期行为 / Expected behaviour

访问解析为大陆应匹配GEOIPCN规则

### 实际行为 / Actual Behaviour

跳过了GEOIP直接访问了final

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.0

### 是否为 Pre-release / Is pre-release version

no

### 操作系统及版本 / OS version

win11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
日记和使用的内核版本呢？

**Comment by how1ewu** [comment]
> 日记和使用的内核版本呢？
我将关闭这个issus，这个问题可能存在于内核
