### ISSUE TITLE
更新后, 无法识别旧的服务模式

### ISSUE THREAD

**Issue by TomyJan** [LibNyanpasu/clash-nyanpasu#551]
### 复现步骤 / Step to reproduce

1. 旧版本 Nyanpasu 安装并启用服务模式
2. 更新并运行 Nyanpasu

### 预期行为 / Expected behaviour

应该正确识别到服务模式

### 实际行为 / Actual Behaviour

新版本 Nyanpasu 无法识别在旧版本安装的服务模式, 并且由于识别不到已经安装, 按钮是 install 导致无法卸载

![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/67973160/615051f6-4263-4ce3-90ba-3d2aa21395e4)

必须手动管理员运行 Nyanpasu ./resources 目录下的 `uninstall-service.exe` 进行卸载后打开 Nyanpasu 才能安装使用

### 备注 / Addition details

这个 bug 存在好几个版本了, 不清楚从哪个版本开始有的

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.0

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Win11 23H2

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by TomyJan** [comment]
哦, 还有个问题, 每次安装服务模式后, 左下角流量统计一直是0, 重启后流量统计才能正常显示

**Comment by Bformax** [comment]
我也遇到了

**Comment by Bformax** [comment]
Tun开启服务模式我还遇到：
关机以后再开机Proxy页面空白，Profile无法切换，需要关了Nyanpasu再开一次
重启不会有问题，感觉这次更新的服务模式有点问题

**Comment by greenhat616** [comment]
本次更新没有引入服务模式的更新。似乎是迁移配置导致的服务模式无法被正确检测，具体原因还需要调查。

**Comment by Bformax** [comment]
> 本次更新没有引入服务模式的更新。似乎是迁移配置导致的服务模式无法被正确检测，具体原因还需要调查。

我删掉.config内的文件，新建以后还是一样有问题，退回1.45用了

**Comment by TomyJan** [comment]
> 本次更新没有引入服务模式的更新。似乎是迁移配置导致的服务模式无法被正确检测，具体原因还需要调查。

之前版本也存在这问题

**Comment by greenhat616** [comment]
之前的版本引入了安装程序时杀死服务的特性，由于 verge 的实现问题，服务被杀死后不会自动唤起。如果你尝试过重启系统的话，应该能发现这种情况下的服务在重启后能正确启动。这个原因导致的问题，在 v1.5.0 中修复了。



发自我的iPhone


------------------ 原始邮件 ------------------
From: TomyJan ***@***.***&gt;
发送时间: 03/05/2024, 21:59
To: LibNyanpasu/clash-nyanpasu ***@***.***&gt;
抄送: Jonson Petard ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [LibNyanpasu/clash-nyanpasu] 更新后, 无法识别旧的服务模式 (Issue #551)





  
本次更新没有引入服务模式的更新。似乎是迁移配置导致的服务模式无法被正确检测，具体原因还需要调查。
  
之前版本也存在这问题

**Comment by greenhat616** [comment]
服务模式的重构可以关注这个 issue：https://github.com/LibNyanpasu/clash-verge-service/issues/4，
由于迁移配置导致的服务无法识别的问题，等我有空了我去修复一下。
