### ISSUE TITLE
unified-delay 和 tcp-concurrent 去掉这两个选项，运行配置中还有是这两个配置都为true

### ISSUE THREAD

**Issue by ttyy33** [LibNyanpasu/clash-nyanpasu#554]
### 复现步骤 / Step to reproduce

勾选这两个选项再去掉
<img width="155" alt="10176b43513c3e321b59754db8d4978" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/127597621/3e1ce1c3-f678-4bb3-8a56-98d28738cd09">

### 预期行为 / Expected behaviour

运行只读配置中应该没有这两个配置

### 实际行为 / Actual Behaviour

<img width="419" alt="cbd98481a0692d7d3c52499c1941fb6" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/127597621/d30b82a6-91a5-4fd6-b1ed-6634b6995862">

在merge方式的配置文件注释后，刷新配置后，查看运行配置还是有这两个选项
<img width="226" alt="eac3e39d8108fd4f726189e23cd49ff" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/127597621/18139431-8c10-46fb-97b0-cd705496c9db">

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.0

### 是否为 Pre-release / Is pre-release version

github下载

### 操作系统及版本 / OS version

Microsoft Windows [版本 10.0.19044.4046]

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by ttimochan** [comment]
This is a default behavior, you need to set it to false in Merge type files，you can see it https://github.com/LibNyanpasu/clash-nyanpasu/releases/tag/v1.4.0

**Comment by ttyy33** [comment]
> This is a default behavior, you need to set it to false in Merge type files, should enable these two Clash fields in the GUI. You can see it https://github.com/LibNyanpasu/clash-nyanpasu/releases/tag/v1.4.0

thanks

**Comment by ttimochan** [comment]
> I’ve tried setting those two options to false, and it still doesn’t work.


You should enable these two Clash fields in the GUI , and enable this merge file. If you have another issue, please describe it in detail

**Comment by Vulcankta** [comment]
> > This is a default behavior, you need to set it to false in Merge type files, should enable these two Clash fields in the GUI. You can see it https://github.com/LibNyanpasu/clash-nyanpasu/releases/tag/v1.4.0
> 
> I’ve tried setting those two options to false, and it still doesn’t work.

I enable these two Clash fields in the GUI, I also use Merge, set unified-delay: false tcp-concurrent: true but it still shows unified-delay: true tcp-concurrent: true
![PixPin_05-03-2024_18-52-58](https://github.com/LibNyanpasu/clash-nyanpasu/assets/61764871/bc1ff09d-94e9-452d-9c51-4d94c0af54a7)
![PixPin_05-03-2024_18-54-00](https://github.com/LibNyanpasu/clash-nyanpasu/assets/61764871/5634e128-8d0f-4f2e-80f0-e1a00a32d716)
![PixPin_05-03-2024_18-53-40](https://github.com/LibNyanpasu/clash-nyanpasu/assets/61764871/de4705a3-1e90-44fe-bee5-31874868355f)

**Comment by ttyy33** [comment]
> > > This is a default behavior, you need to set it to false in Merge type files, should enable these two Clash fields in the GUI. You can see it https://github.com/LibNyanpasu/clash-nyanpasu/releases/tag/v1.4.0
> > 
> > 
> > I’ve tried setting those two options to false, and it still doesn’t work.
> 
> I enable these two Clash fields in the GUI, I also use Merge, set unified-delay: false tcp-concurrent: true but it still shows unified-delay: true tcp-concurrent: true ![PixPin_05-03-2024_18-52-58](https://private-user-images.githubusercontent.com/61764871/310088349-bc1ff09d-94e9-452d-9c51-4d94c0af54a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzcyMjcsIm5iZiI6MTcwOTYzNjkyNywicGF0aCI6Ii82MTc2NDg3MS8zMTAwODgzNDktYmMxZmYwOWQtOTRlOS00NTJkLTljNTEtNGQ5NGMwYWY1NGE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDExMDg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY5OTg2MjQyNGE3MzIxODcxZmM5MDdjYzZmOGJhYzYwZTM2YWExZTIxNDczMjMwZjkwZTI2N2NkOTI2ZmNjMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rgziQelewZDf6JnHZ_6BhQ_yK4ifDI3zTAO00-ZF9K4) ![PixPin_05-03-2024_18-54-00](https://private-user-images.githubusercontent.com/61764871/310088385-5634e128-8d0f-4f2e-80f0-e1a00a32d716.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzcyMjcsIm5iZiI6MTcwOTYzNjkyNywicGF0aCI6Ii82MTc2NDg3MS8zMTAwODgzODUtNTYzNGUxMjgtOGQwZi00ZjJlLTgwZjAtZTFhMDBhMzJkNzE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDExMDg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyN2JmMmFjNTk5ZDY3NWNhZTM5YTIyYWY5OTczMWVjZmE3MTRlOWFkNDFjNzBkMWU3MGM5Mzc0YjJlMGFiNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.muMbM0jd7G2XJuTdjICKXHYa6fFzMdvbuJMkiTV0JOU) ![PixPin_05-03-2024_18-53-40](https://private-user-images.githubusercontent.com/61764871/310088417-de4705a3-1e90-44fe-bee5-31874868355f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2MzcyMjcsIm5iZiI6MTcwOTYzNjkyNywicGF0aCI6Ii82MTc2NDg3MS8zMTAwODg0MTctZGU0NzA1YTMtMWU5MC00NGZlLWJlZTUtMzE4NzQ4NjgzNTVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDExMDg0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ODIxYTAyZWFiZTViNDdlNDRlZDgwYWY0NDNkZWUwOWRkMDkzY2FhZTkwN2Q4NDQzMjM4MjNlODVjOTBhNDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AH5scYzsuov9UY11RTrwZUtB6NcPNeh3fjScwUD74dg)

跟我测试的一样，我也是这样的情况

**Comment by ttimochan** [comment]
> 跟我测试的一样，我也是这样的情况

I tried to reproduce it and the behavior was as expected (my platform is ArchLinux). You may need to enable TUN mode.

configuration screenshot 
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/91021824/107b008e-40d1-4716-a5b1-d82a81afbaae)
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/91021824/56134e32-b8da-4bf7-a419-6b8f3897420c)

**Comment by greenhat616** [comment]
Please have a try with `Script` Chain? Thank you.
`Merge` Chain should be refactoring in the future. I can do a survey at the end of this weeks.

Wiki Ref: https://nyanpasu.elaina.moe/tutorial/proxy-chain.html

**Comment by Vulcankta** [comment]
> > 跟我測試的一樣，我也是這樣的情況
> 
> I attempted to replicate it, and I believe the software's behavior aligns with expectations (my platform is archlinux). You may need to enable TUN mode. I utilized a Clash subscription configuration file and then applied a Merge-type configuration file to patch it. In my understanding, Merge-type files are designed to patch subscription files and serve as a means to keep subscription files updated. Using Merge-type files to modify the default GUI configuration does not seem to be the primary purpose of Merge files, in my view.
> 
> configuration screenshot ![image](https://private-user-images.githubusercontent.com/91021824/310117886-107b008e-40d1-4716-a5b1-d82a81afbaae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDQxMTEsIm5iZiI6MTcwOTY0MzgxMSwicGF0aCI6Ii85MTAyMTgyNC8zMTAxMTc4ODYtMTA3YjAwOGUtNDBkMS00NzE2LWE1YjEtZDgyYTgxYWZiYWFlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEzMDMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlYmYzYWU1ZDNlNGFiNDNhNGI0ODRlMzUyMDY1M2M5MjllYjkxODIwMTMzMmRhM2JmMjcwYTNhNDg5MTFhZDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.J9gKMyMeH550_PUPK5xP9R-FcYYw-J6LPDV8lTpq1N4) ![image](https://private-user-images.githubusercontent.com/91021824/310117966-56134e32-b8da-4bf7-a419-6b8f3897420c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDQxMTEsIm5iZiI6MTcwOTY0MzgxMSwicGF0aCI6Ii85MTAyMTgyNC8zMTAxMTc5NjYtNTYxMzRlMzItYjhkYS00YmY3LWE0MTktNmI4ZjM4OTc0MjBjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEzMDMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2ZGU0YmFhZmY2MDUzNTdiMjUyMGIzNTFkMzQ5ZTgzOTUzYTk4MzAzOGM4YWJjMWRlNTJjNjBiNTZmMTMzNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UD8QyrWR_ZG2gIuTAamhkqMQ7G6OHQql7lnk4b_IN4s) ![image](https://private-user-images.githubusercontent.com/91021824/310121032-004da385-05ce-40a4-b5ad-f44b4542b3c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NDQxMTEsIm5iZiI6MTcwOTY0MzgxMSwicGF0aCI6Ii85MTAyMTgyNC8zMTAxMjEwMzItMDA0ZGEzODUtMDVjZS00MGE0LWI1YWQtZjQ0YjQ1NDJiM2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDEzMDMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2M2NmYzIwNTlkOWVkNjEyOTU4OTQ4ZjdmYTJhMjVlZjBiZGUxOGZjMzMzNzExMmE0MTM4MzljYjFhMGM5YzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ClusC75B6LtPU02wf2iftkwHmAHf6LK4WFnIZSJJ1P0)

Unfortunately I can't enable tun for testing, my damn Windows reports Start TUN listening error: configure tun interface: set ipv4 dns: The RPC server is unavailable every time I enable tun with mihomo. I don't get this error with Premium but then I don't have to use Clash fields.

**Comment by Vulcankta** [comment]
> > Unfortunately I can't enable tun for testing, my damn Windows reports Start TUN listening error: configure tun interface: set ipv4 dns: The RPC server is unavailable every time I enable tun with mihomo. I don't get this error with Premium but then I don't have to use Clash fields.
> 
> Perhaps you don't need the TUN mode. You can try adding a Clash subscription configuration file and then use a Merge type file to patch it.

I will try this. I now think that the Clash fields feature is buggy on Windows, so I hope more people will read this issue and try to test it on Windows.

**Comment by ttyy33** [comment]
> > > Unfortunately I can't enable tun for testing, my damn Windows reports Start TUN listening error: configure tun interface: set ipv4 dns: The RPC server is unavailable every time I enable tun with mihomo. I don't get this error with Premium but then I don't have to use Clash fields.
> > 
> > 
> > Perhaps you don't need the TUN mode. You can try adding a Clash subscription configuration file and then use a Merge type file to patch it.
> 
> I will try this. I now think that the Clash fields feature is buggy on Windows, so I hope more people will read this issue and try to test it on Windows.

I also encountered this problem on the Windows platform.

**Comment by greenhat616** [comment]
请尝试最新的开发版，应该是没有问题了。
https://github.com/LibNyanpasu/clash-nyanpasu/actions/runs/8315834614
