### ISSUE TITLE
在设置中-选择是否在“右键菜单”显示规则组

### ISSUE THREAD

**Issue by xiaoyangdkj** [LibNyanpasu/clash-nyanpasu#574]
### 需求 / Requirement

我不希望它表现成这样......(它在v1.4.0的时候不长这样的...)
![屏幕截图_20240308_112921](https://github.com/LibNyanpasu/clash-nyanpasu/assets/82305021/d4407b06-dedb-4119-bb77-c77cc8be67b3)

### 建议实现 / Suggested implements

在"杂项设置"或"界面设置"中增加“开启右键菜单代理组显示”选项，让我在右键菜单中找到"打开面板"(而不是去桌面菜单那里找到快捷方式并双击打开)

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.0

### 是否为 Pre-release / Is pre-release version

否

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
Duplicated by #545

**Comment by xiaoyangdkj** [comment]
好吧，这是上个月才出现的更新...或许我应该回退版本
