### ISSUE TITLE
failed to create single instance

### ISSUE THREAD

**Issue by 100kgMaizi** [LibNyanpasu/clash-nyanpasu#586]
### 复现步骤 / Step to reproduce

Caused by:
0: file open or create error
1: Read-only file system (os error 30)
请将此问题汇报到 Github 问题追踪器

### 预期行为 / Expected behaviour

Caused by:
0: file open or create error
1: Read-only file system (os error 30)
请将此问题汇报到 Github 问题追踪器

### 实际行为 / Actual Behaviour

Caused by:
0: file open or create error
1: Read-only file system (os error 30)
请将此问题汇报到 Github 问题追踪器

### 应用日志 / App logs

Start TUN listening error: configure tun interface: Connect: operation not permitted

### 备注 / Addition details

Start TUN listening error: configure tun interface: Connect: operation not permitted

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.0

### Clash 核心及其版本号 / Clash core and version

v 1.8.1 meta

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

macOS 12.7.4

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
您已搜索过 Issue Tracker，没有找到类似内容。

https://github.com/LibNyanpasu/clash-nyanpasu/issues/544

请尝试开发版。
