### ISSUE TITLE
支持NAT的节点在Nyanpasu上只能测试出UnsupportedServer

### ISSUE THREAD

**Issue by SakiTomato822** [libnyanpasu/clash-nyanpasu#590]
### 复现步骤 / Step to reproduce

1. 使用相同节点（以日本04为例），在NekoRay上测试通过，得到FullCone：
![Screenshot 2024-03-10 211929](https://github.com/LibNyanpasu/clash-nyanpasu/assets/136449079/b6491535-4674-4b34-8020-871bd53a443e)
2.关闭Nekoray，切换至Nyanpasu，开启TUN和服务模式，得到UnsupportedServer:
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/136449079/c2535fbe-b7e4-4936-b590-a8fff2de89a9)
3.使用Nyanpasu直连，得到结果：
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/136449079/90814582-36b0-4219-a5df-a9df363125a1)

### 预期行为 / Expected behaviour

和NekoRay的测试一样，应该呈现为FullCone。

### 实际行为 / Actual Behaviour

测试多个国家多个节点，均有UnsupportedServer。

### 应用日志 / App logs

[2024-03-10-2138.log](https://github.com/LibNyanpasu/clash-nyanpasu/files/14550384/2024-03-10-2138.log)

### 备注 / Addition details

同一节点：V2Ray测试同样FullCone，如切换为Clash Premium内核也可做到FullCone。

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.0

### Clash 核心及其版本号 / Clash core and version

v1.18.1 Mihomo

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windows 11 24H2

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by SakiTomato822** [comment]
> 这个会不会和 Mihomo 内核反馈更合适呢？

他们那边很多人提过，我从Meta时候就发过issue了，到现在他们也没解决

**Comment by greenhat616** [comment]
Clash Rs 有没有这个问题？内核问题我们这里是解决不了的，如果 Premium 或者 Rs 没问题的话，建议更换内核使用。

**Comment by SakiTomato822** [comment]
> Clash Rs 有没有这个问题？内核问题我们这里是解决不了的，如果 Premium 或者 Rs 没问题的话，建议更换内核使用。

使用非Mihomo内核，不管开不开服务模式，都无法正常开启TUN，只会弹出一个“错误”提示。
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/136449079/72b6f95c-26e8-4e69-990e-0c83f3ae4017)

**Comment by ibigbug** [comment]
有日志吗，看看是哪里panic了。

**Comment by SakiTomato822** [comment]
> 有日志吗，看看是哪里panic了。

[clash-nyanpasu.2024-04-05.app - Copy.log](https://github.com/LibNyanpasu/clash-nyanpasu/files/14883756/clash-nyanpasu.2024-04-05.app.-.Copy.log)

**Comment by SakiTomato822** [comment]
> > > Clash Rs 有没有这个问题？内核问题我们这里是解决不了的，如果 Premium 或者 Rs 没问题的话，建议更换内核使用。
> > 
> > 
> > 使用非Mihomo内核，不管开不开服务模式，都无法正常开启TUN，只会弹出一个“错误”提示。 ![image](https://private-user-images.githubusercontent.com/136449079/319066180-72b6f95c-26e8-4e69-990e-0c83f3ae4017.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzUzNjQsIm5iZiI6MTcxMjEzNTA2NCwicGF0aCI6Ii8xMzY0NDkwNzkvMzE5MDY2MTgwLTcyYjZmOTVjLTI2ZTgtNGU2OS05OTBlLTBjODNmM2FlNDAxNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QwOTA0MjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNTVlNmFiZGRlOGRiODk3NTQ1NDBiNDNlOWUzNjdiY2QwY2MyNmY0NzI4ZWJhN2U0OGRlNzk1OTM4YjViYzRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Wb3GxGt_GzrQ5BFFEiPq9fT8a_otioO6FUUHrn5zOsY)
> 
> 这个好像是 Clash Rust 的 bug，是不是使用了 rules provider? 检测配置通过，但是运行时会 panic。
> 
> cc @ibigbug

刚刚测过了，即使是Clash Premium内核也同样无法正常开启，即使开启了也没有出现TUN网卡，且关闭情况无法正常联网。

**Comment by ibigbug** [comment]
日志里面没有看到相关的panic，有些dns的报错

**Comment by greenhat616** [comment]
已知 mihomo 会出现 NAT 问题，Premium 没有这个问题，请使用 Premium 内核。
