### ISSUE TITLE
代理、连接和规则界面未正常显示信息

### ISSUE THREAD

**Issue by freeNestor** [LibNyanpasu/clash-nyanpasu#601]
### 复现步骤 / Step to reproduce

使用本地配置文件config.yaml，配置后重启或启动应用

### 预期行为 / Expected behaviour

代理界面显示配置的代理组；连接界面显示已建立的连接；规则界面则显示配置的rules

### 实际行为 / Actual Behaviour

<img width="912" alt="image" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/19606302/641e079c-264b-4f46-82a4-63816ed7480a">
<img width="912" alt="image" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/19606302/d8a15c1a-1403-4bc2-8434-462049dab8b5">
需要多次尝试退出、重启才有可能显示正常，并不是每次都正常显示。

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.1-alpha

### Clash 核心及其版本号 / Clash core and version

v1.18.1 meta

### 是否为 Pre-release / Is pre-release version

685179b

### 操作系统及版本 / OS version

macOS 14

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
