### ISSUE TITLE
关于全局模式下配置文件里rules的问题

### ISSUE THREAD

**Issue by user00036** [LibNyanpasu/clash-nyanpasu#605]
### 复现步骤 / Step to reproduce

我想问下全局模式下rules配置的规则生效吗，就是说全局模式下是不是只走选择的节点，不管配置什么规则都不生效。
但是我全局模式下把规则设置为空好像网速会下降不少不知道为啥

### 预期行为 / Expected behaviour

网速不变

### 实际行为 / Actual Behaviour

网速下降

### Clash Nyapasu 版本号 / Clash Nyapasu

v1.5.8 

### Clash 核心及其版本号 / Clash core and version

v1.18.1 meta

### 是否为 Pre-release / Is pre-release version

no

### 操作系统及版本 / OS version

windows11

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
全局顾名思义会接管全部的流量，届时网络性能可能会下降，全局+直连就相当于所有流量走了一遍内核，但是不走代理

**Comment by user00036** [comment]
> 全局顾名思义会接管全部的流量，届时网络性能可能会下降，全局+直连就相当于所有流量走了一遍内核，但是不走代理

那全局模式，配置的规则生效不，比如什么domain配置的域名
