### ISSUE TITLE
[BUG]1.4.1版本Clash rust内核下配置无法切换

### ISSUE THREAD

**Issue by deepinsc2020** [LibNyanpasu/clash-nyanpasu#61]
1、1.4.1版本Clash rust内核下配置无法切换
2、局域网连接、IPV6无法关闭

**Comment by greenhat616** [comment]
1、配置切换功能是正常的。报错可能是配置中使用的协议还不受 `clash-rs` 支持。你可以看一下你的配置文件里，使用了哪些协议。
* 不受支持的协议可以去 https://github.com/Watfaq/clash-rs/issues/190 反馈
* Vless 可以在这里点赞，提高优先级：https://github.com/Watfaq/clash-rs/issues/202
* Grpc 支持已经合并进主线，请等待新版本发布

2、已确认。是 `clash-rs` 的配置弃用问题，你可以去 `clash-rs` 开一个 issue，让他做一下兼容性适配；这边有空会专门适配下。
* `ipv6`:  https://github.com/Watfaq/clash-rs/blob/master/clash_lib/src/config/def.rs#L307-L308
* `allow-lan`: https://github.com/Watfaq/clash-rs/blob/master/clash_lib/src/config/def.rs#L343-L344

**Comment by deepinsc2020** [comment]
反馈下，配置切换我这边不是报错，是没有反应，点击无任何响应

**Comment by greenhat616** [comment]
> 反馈下，配置切换我这边不是报错，是没有反应，点击无任何响应

可以附上相关的日记吗？设置，日记目录下的。

**Comment by chen-jingliang** [comment]
> 反馈下，配置切换我这边不是报错，是没有反应，点击无任何响应

我只能使用clash内核，clash meta内核切换没有反应，点击输入密码后还是无反应。替换成clash meta dev可以正常使用。

**Comment by dyxushuai** [comment]
应该是配置格式不兼容导致的，看一下日志就知道了

**Comment by greenhat616** [comment]
上游已经在 `0.1.12` 中支持了，这几日会提交个 PR 彻底修复此问题。

**Comment by greenhat616** [comment]
dev build 中已经修复
