### ISSUE TITLE
这个软件可以出Android版本吗？

### ISSUE THREAD

**Issue by Stephenzero** [LibNyanpasu/clash-nyanpasu#611]
这个软件可以出Android版本吗？

**Comment by keiko233** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/issues/324
重复的issue，其次，没有用模板

**Comment by test4uninstall** [comment]
请使用ClashMetaForAndroid
https://github.com/MetaCubeX/ClashMetaForAndroid
