### ISSUE TITLE
[BUG] 任务栏图标出现在最左侧

### ISSUE THREAD

**Issue by dyxushuai** [libnyanpasu/clash-nyanpasu#62]
**Describe the bug**
出现双图标，任务栏最左侧也有一个图标，覆盖了apple图标并且能够点击，出现clash菜单，其他程序正常，很有可能是tarui的问题
系统版本： 14.1.2
clash-nyanpasu版本：v1.4.1
<img width="1109" alt="image" src="https://github.com/keiko233/clash-nyanpasu/assets/5157648/30e35e03-38b3-427f-b43c-c9dcae7c8adb">

**Comment by dyxushuai** [comment]
找到原因了，如果打开这个配置，就会出现双重icon的情况
<img width="473" alt="image" src="https://github.com/keiko233/clash-nyanpasu/assets/5157648/6dd2b36b-ff84-4900-ac51-f0a4224cc1c2">

**Comment by dyxushuai** [comment]
> > 找到原因了，如果打开这个配置，就会出现双重icon的情况 <img alt="image" width="473" src="https://private-user-images.githubusercontent.com/5157648/288646009-6dd2b36b-ff84-4900-ac51-f0a4224cc1c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzA3NTEsIm5iZiI6MTcwMjEzMDQ1MSwicGF0aCI6Ii81MTU3NjQ4LzI4ODY0NjAwOS02ZGQyYjM2Yi1mZjg0LTQ5MDAtYWM1MS1mMGE0MjI0Y2MxYzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDlUMTQwMDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWZlMDI0MDJlNzlmNjkwMWViNDZhZmYzYmNhNTM5ZDhkYTRlMGM2MmNkYjJjYzJjNTk1NDNkMWM5YjRkMTcxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jfISrjh3Dlw4V9uW0rxoG3IFZcdDaUr8suEsfjPiHA0">
> 
> 我也有这样的问题，你图上的windows具体在哪里？我没有找到

在dock的设置里

**Comment by greenhat616** [comment]
blocked by https://github.com/tauri-apps/tauri/issues/8570

**Comment by PelikanM400** [comment]
> > > 找到原因了，如果打开这个配置，就会出现双重icon的情况 <img alt="image" width="473" src="https://private-user-images.githubusercontent.com/5157648/288646009-6dd2b36b-ff84-4900-ac51-f0a4224cc1c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMzA3NTEsIm5iZiI6MTcwMjEzMDQ1MSwicGF0aCI6Ii81MTU3NjQ4LzI4ODY0NjAwOS02ZGQyYjM2Yi1mZjg0LTQ5MDAtYWM1MS1mMGE0MjI0Y2MxYzIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMDlUMTQwMDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWZlMDI0MDJlNzlmNjkwMWViNDZhZmYzYmNhNTM5ZDhkYTRlMGM2MmNkYjJjYzJjNTk1NDNkMWM5YjRkMTcxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.jfISrjh3Dlw4V9uW0rxoG3IFZcdDaUr8suEsfjPiHA0">
> > 
> > 
> > 我也有这样的问题，你图上的windows具体在哪里？我没有找到
> 
> 在dock的设置里

我也出现了这个问题，但没找到dock的设置。
