### ISSUE TITLE
1.5.1-alpha+347ce03 自定义应用目录时报错

### ISSUE THREAD

**Issue by leic4u** [LibNyanpasu/clash-nyanpasu#625]
### 复现步骤 / Step to reproduce

更换目录时可以选择自定义目录，但确定时报错

### 预期行为 / Expected behaviour

正常自定义应用目录

### 实际行为 / Actual Behaviour

![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/32786903/2e3681d6-ec90-4e82-b8c2-2ae53caf9116)
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/32786903/586cc80e-bc86-47d8-81b6-179f609f4997)

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.1-alpha+347ce03

### Clash 核心及其版本号 / Clash core and version

v1.81.1 mihomo

### 是否为 Pre-release / Is pre-release version

347ce03

### 操作系统及版本 / OS version

win11 x64

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by leic4u** [comment]
实测选择不迁移现有数据，可以正常更换目录，但是得手动迁移一遍原配置文件。

**Comment by greenhat616** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/actions/runs/8315834614
请尝试最新的开发版，应该是没有问题了

**Comment by leic4u** [comment]
> https://github.com/LibNyanpasu/clash-nyanpasu/actions/runs/8315834614 请尝试最新的开发版，应该是没有问题了

感谢，辛苦了。

刚试了下，确实没有报错了，不过迁移应用配置文件没成功。而且 nyanpasu 自动关闭了没有自动重启，我手动重启的，然后就生成了新的应用配置。

**Comment by leic4u** [comment]
我从新的目录迁移回原目录，报错了。

![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/32786903/d4d53656-fe66-4a22-8ecd-03bb6ae08027)

**Comment by leic4u** [comment]
> 我从新的目录迁移回原目录，报错了。

迁移回原目录时，选择不迁移应用配置，可以设置成功，手动重启后可以识别到原来的应用配置。

**Comment by greenhat616** [comment]
> > https://github.com/LibNyanpasu/clash-nyanpasu/actions/runs/8315834614 请尝试最新的开发版，应该是没有问题了
> 
> 感谢，辛苦了。
> 
> 刚试了下，确实没有报错了，不过迁移应用配置文件没成功。而且 nyanpasu 自动关闭了没有自动重启，我手动重启的，然后就生成了新的应用配置。

有没有日记给我看一下



> 我从新的目录迁移回原目录，报错了。
> 
> ![image](https://private-user-images.githubusercontent.com/32786903/313478243-d4d53656-fe66-4a22-8ecd-03bb6ae08027.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA2ODQ5NzksIm5iZiI6MTcxMDY4NDY3OSwicGF0aCI6Ii8zMjc4NjkwMy8zMTM0NzgyNDMtZDRkNTM2NTYtZmU2Ni00YTIyLThlY2QtMDNiYjZhZTA4MDI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDE0MTExOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlYTMxNmRjMzdkOWQyMTczYTYxZWEyYTc1MTczMmVmZWExOWJiNjgxY2Q1YmY5MDg0OGI3MjAzYmMyMTFjMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.grrw799e-Uhc6JMnhV_n3-K5p5prL6DvUpMbQtG9xP0)

这个看起来是服务模式没有正确退出 😢

**Comment by leic4u** [comment]
另外发现个问题，就是重启打开，或者从托盘区打开面板，会出现可视区域只有一半的问题。然后任意切换一下配置/连接/规则等再切回来就好了。

![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/32786903/01ee7427-6628-45b0-b423-56a4e492d068)

**Comment by leic4u** [comment]
> 这个看起来是服务模式没有正确退出 😢

从空白的自定义目录切回有配置的自定义目录时，报错变了。这次是报的没有正确关闭服务模式。（因为我还没有开服务模式）

![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/32786903/55b52ba4-5211-4956-9787-a896a867954b)

**Comment by leic4u** [comment]
从空白的自定义目录（其实重启后也生成了默认配置不算空白目录了）切回有配置文件的自定义目录时，日志如下：

```
{"timestamp":"2024-03-17T14:47:51.257899Z","level":"INFO","fields":{"message":"[clash]: time=\"2024-03-17T22:47:51.2482312+08:00\" level=info msg=\"Start initial configuration in progress\"\n","log.target":"app","log.module_path":"clash_verge::core::clash::core","log.file":"tauri\\src\\core\\clash\\core.rs","log.line":208},"target":"app","filename":"tauri\\src\\core\\clash\\core.rs","line_number":208}
{"timestamp":"2024-03-17T14:47:51.257983Z","level":"INFO","fields":{"message":"[clash]: time=\"2024-03-17T22:47:51.2577072+08:00\" level=info msg=\"Geodata Loader mode: memconservative\"\n","log.target":"app","log.module_path":"clash_verge::core::clash::core","log.file":"tauri\\src\\core\\clash\\core.rs","log.line":208},"target":"app","filename":"tauri\\src\\core\\clash\\core.rs","line_number":208}
{"timestamp":"2024-03-17T14:47:51.258080Z","level":"INFO","fields":{"message":"[clash]: time=\"2024-03-17T22:47:51.2577072+08:00\" level=info msg=\"Geosite Matcher implementation: succinct\"\n","log.target":"app","log.module_path":"clash_verge::core::clash::core","log.file":"tauri\\src\\core\\clash\\core.rs","log.line":208},"target":"app","filename":"tauri\\src\\core\\clash\\core.rs","line_number":208}
{"timestamp":"2024-03-17T14:47:51.258220Z","level":"INFO","fields":{"message":"[clash]: time=\"2024-03-17T22:47:51.2577072+08:00\" level=info msg=\"Initial configuration complete, total time: 0ms\"\n","log.target":"app","log.module_path":"clash_verge::core::clash::core","log.file":"tauri\\src\\core\\clash\\core.rs","log.line":208},"target":"app","filename":"tauri\\src\\core\\clash\\core.rs","line_number":208}
{"timestamp":"2024-03-17T14:47:51.258241Z","level":"INFO","fields":{"message":"[clash]: time=\"2024-03-17T22:47:51.2577072+08:00\" level=info msg=\"Sniffer is closed\"\n","log.target":"app","log.module_path":"clash_verge::core::clash::core","log.file":"tauri\\src\\core\\clash\\core.rs","log.line":208},"target":"app","filename":"tauri\\src\\core\\clash\\core.rs","line_number":208}
{"timestamp":"2024-03-17T14:47:51.259380Z","level":"INFO","fields":{"message":"[clash]: time=\"2024-03-17T22:47:51.2591586+08:00\" level=info msg=\"RESTful API listening at: 127.0.0.1:17650\"\n","log.target":"app","log.module_path":"clash_verge::core::clash::core","log.file":"tauri\\src\\core\\clash\\core.rs","log.line":208},"target":"app","filename":"tauri\\src\\core\\clash\\core.rs","line_number":208}
{"timestamp":"2024-03-17T14:47:51.259477Z","level":"INFO","fields":{"message":"[clash]: time=\"2024-03-17T22:47:51.2591586+08:00\" level=info msg=\"Mixed(http+socks) proxy listening at: 127.0.0.1:7890\"\n","log.target":"app","log.module_path":"clash_verge::core::clash::core","log.file":"tauri\\src\\core\\clash\\core.rs","log.line":208},"target":"app","filename":"tauri\\src\\core\\clash\\core.rs","line_number":208}
{"timestamp":"2024-03-17T14:47:51.262061Z","level":"INFO","fields":{"message":"[clash]: time=\"2024-03-17T22:47:51.2618861+08:00\" level=info msg=\"Start initial Compatible provider default\"\n","log.target":"app","log.module_path":"clash_verge::core::clash::core","log.file":"tauri\\src\\core\\clash\\core.rs","log.line":208},"target":"app","filename":"tauri\\src\\core\\clash\\core.rs","line_number":208}
{"timestamp":"2024-03-17T14:48:01.596517Z","level":"ERROR","fields":{"message":"failed to connect to the Clash Nyanpasu Service","log.target":"app","log.module_path":"clash_verge::cmds::service","log.file":"tauri\\src\\cmds.rs","log.line":432},"target":"app","filename":"tauri\\src\\cmds.rs","line_number":432}
{"timestamp":"2024-03-17T14:48:06.912727Z","level":"WARN","fields":{"message":"NewEvents emitted without explicit RedrawEventsCleared","log.target":"tao::platform_impl::platform::event_loop::runner","log.module_path":"tao::platform_impl::platform::event_loop::runner","log.file":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.7\\src\\platform_impl\\windows\\event_loop\\runner.rs","log.line":359},"target":"tao::platform_impl::platform::event_loop::runner","filename":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.7\\src\\platform_impl\\windows\\event_loop\\runner.rs","line_number":359}
{"timestamp":"2024-03-17T14:48:06.921536Z","level":"WARN","fields":{"message":"RedrawEventsCleared emitted without explicit MainEventsCleared","log.target":"tao::platform_impl::platform::event_loop::runner","log.module_path":"tao::platform_impl::platform::event_loop::runner","log.file":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.7\\src\\platform_impl\\windows\\event_loop\\runner.rs","log.line":345},"target":"tao::platform_impl::platform::event_loop::runner","filename":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.7\\src\\platform_impl\\windows\\event_loop\\runner.rs","line_number":345}
{"timestamp":"2024-03-17T14:48:08.973989Z","level":"ERROR","fields":{"message":"failed to connect to the Clash Nyanpasu Service","log.target":"app","log.module_path":"clash_verge::cmds::service","log.file":"tauri\\src\\cmds.rs","log.line":432},"target":"app","filename":"tauri\\src\\cmds.rs","line_number":432}
{"timestamp":"2024-03-17T14:48:12.154372Z","level":"ERROR","fields":{"message":"failed to kill clash-verge-service.exe","log.target":"app","log.module_path":"clash_verge::cmds","log.file":"tauri\\src\\cmds.rs","log.line":404},"target":"app","filename":"tauri\\src\\cmds.rs","line_number":404}
{"timestamp":"2024-03-17T14:50:18.432145Z","level":"WARN","fields":{"message":"NewEvents emitted without explicit RedrawEventsCleared","log.target":"tao::platform_impl::platform::event_loop::runner","log.module_path":"tao::platform_impl::platform::event_loop::runner","log.file":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.7\\src\\platform_impl\\windows\\event_loop\\runner.rs","log.line":359},"target":"tao::platform_impl::platform::event_loop::runner","filename":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.7\\src\\platform_impl\\windows\\event_loop\\runner.rs","line_number":359}
{"timestamp":"2024-03-17T14:50:18.444267Z","level":"WARN","fields":{"message":"RedrawEventsCleared emitted without explicit MainEventsCleared","log.target":"tao::platform_impl::platform::event_loop::runner","log.module_path":"tao::platform_impl::platform::event_loop::runner","log.file":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.7\\src\\platform_impl\\windows\\event_loop\\runner.rs","log.line":345},"target":"tao::platform_impl::platform::event_loop::runner","filename":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.7\\src\\platform_impl\\windows\\event_loop\\runner.rs","line_number":345}
```

**Comment by greenhat616** [comment]
有可能是 clash 和 logs 占用了文件，我明天写个 bat 来做迁移任务吧。

**Comment by leic4u** [comment]
> 有可能是 clash 和 logs 占用了文件，我明天写个 bat 来做迁移任务吧。

有没有可能是我有两个客户端导致的，因为开着 nyanpasu 的同时还开着 clash-verge-rev ，nyanpasu 我没开服务模式，但是 clash-verge-rev 开了。

刚刚我看任务管理器的时候，没有 clash-verge-sevice 进程，clash-verge-rev 里面的服务模式也损坏了。应该是 nyanpasu 在迁移目录的时候，给我关掉了（也就是第一次报的那个 *拒绝访问 os error 5*），第二次因为没得关了，才报了 *failed tokill clash-verge-service.exe*。

**Comment by greenhat616** [comment]
如果两个软件使用的是同一个配置目录，那么会的，反之，不会的



发自我的iPhone


------------------ 原始邮件 ------------------
From: leic4u ***@***.***&gt;
发送时间: 03/17/2024, 23:40
To: LibNyanpasu/clash-nyanpasu ***@***.***&gt;
抄送: Jonson Petard ***@***.***&gt;, State change ***@***.***&gt;
Subject: Re: [LibNyanpasu/clash-nyanpasu] 1.5.1-alpha+347ce03 自定义应用目录时报错 (Issue #625)





  
有可能是 clash 和 logs 占用了文件，我明天写个 bat 来做迁移任务吧。
  
有没有可能是我有两个客户端导致的，因为开着 nyanpasu 的同时还开着 clash-verge-rev ，nyanpasu 我没开服务模式，但是 clash-verge-rev 开了。
 
刚刚我看任务管理器的时候，没有 clash-verge-sevice 进程，clash-verge-rev 里面的服务模式也损坏了。应该是 nyanpasu 在迁移目录的时候，给我关掉了（也就是第一次报的那个 拒绝访问 os error 5），第二次因为没得关了，才报了 failed tokill clash-verge-service.exe。

**Comment by leic4u** [comment]
> 如果两个软件使用的是同一个配置目录，那么会的，反之，不会的 发自我的iPhone

不是同一个目录。

**Comment by greenhat616** [comment]
cc @4o3F  https://github.com/LibNyanpasu/clash-nyanpasu/commit/8cc9e8c653fc10f3a22e945699800fa6a0fe21a5

**Comment by greenhat616** [comment]
> 另外发现个问题，就是重启打开，或者从托盘区打开面板，会出现可视区域只有一半的问题。然后任意切换一下配置/连接/规则等再切回来就好了。
> 
> ![image](https://private-user-images.githubusercontent.com/32786903/313481567-01ee7427-6628-45b0-b423-56a4e492d068.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMzQ2MDMsIm5iZiI6MTcxMjEzNDMwMywicGF0aCI6Ii8zMjc4NjkwMy8zMTM0ODE1NjctMDFlZTc0MjctNjYyOC00NWIwLWI0MjMtNTZhNGU0OTJkMDY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAzVDA4NTE0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkMTQ2MTcyNzNhYTU1MTcyODJlYjM1MzM4ZGIwNmQ1Y2ZhMGM3YjNkOWRlOTg2M2I1MzU2NjY1NDI2YmJlYjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.h-DECTrCka5lNd00Hs3o8FV1kqggx9o-7fyg6af6dUk)

这个问题修复了

**Comment by leic4u** [comment]
好的，辛苦开发者。明天装个开发版试试。

**Comment by leic4u** [comment]
确实不报错了，但迁移没有成功，配置还是在原目录里面。

**Comment by greenhat616** [comment]
迁移等修复

**Comment by 4o3F** [comment]
Fixed in 363bb4bae8391954b213a26bfa2da6bf6cd64dc5

**Comment by leic4u** [comment]
已换着花样测试，没有发现其他 bug 了。感谢二位开发者！
