### ISSUE TITLE
托盘右键菜单跟随主题模式（浅色、深色）

### ISSUE THREAD

**Issue by leic4u** [libnyanpasu/clash-nyanpasu#627]
### 需求 / Requirement

目前托盘右键菜单为浅色，不会跟随主题模式改变。

![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/32786903/453aecc5-0fe3-4a19-8855-e252d591f9e5)

### 建议实现 / Suggested implements

期望实现可根据主题模式改变托盘区右键菜单颜色。

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.1

### 是否为 Pre-release / Is pre-release version

347ce03

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
可能要留到 Tauri v2 了。目前的菜单不支持设置主题色。
