### ISSUE TITLE
每次打开都会抛异常

### ISSUE THREAD

**Issue by xmh0511** [LibNyanpasu/clash-nyanpasu#631]
### 复现步骤 / Step to reproduce

<img width="258" alt="截屏2024-03-18 09 46 21" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/17973891/04be8fb7-c38a-4a0b-8b15-b4440c6d0e8f">

### 预期行为 / Expected behaviour

正常打开

### 实际行为 / Actual Behaviour

如图

### 应用日志 / App logs

  无

### 备注 / Addition details

无

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.0

### Clash 核心及其版本号 / Clash core and version

mihomo

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

macOs12

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by codedog1118** [comment]
而且左上角🍎图标旁边也会多出一个黑色图标
<img width="289" alt="image" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/29837242/048165c4-7009-4103-810e-c66e12571f7d">

**Comment by greenhat616** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/issues/544

您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found

**Comment by greenhat616** [comment]
> 而且左上角🍎图标旁边也会多出一个黑色图标 <img alt="image" width="289" src="https://private-user-images.githubusercontent.com/29837242/313529053-048165c4-7009-4103-810e-c66e12571f7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MjgxOTQsIm5iZiI6MTcxMDcyNzg5NCwicGF0aCI6Ii8yOTgzNzI0Mi8zMTM1MjkwNTMtMDQ4MTY1YzQtNzAwOS00MTAzLTgxMGUtYzY2ZTEyNTcxZjdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDAyMTEzNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3NDg5NjQyN2IxMjRjYmNkOTc2M2IwYjU5YTE4YzI5N2Q0ODQxOTU0YzE4MTc3NGNkYjRkNTFhNDRiZDk5ZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pnm4iYLuSGnnDFO6d1s0y4VBrsRHNPktJlas0W3xgvs">

https://github.com/LibNyanpasu/clash-nyanpasu/issues/62

https://github.com/LibNyanpasu/clash-nyanpasu/issues/97

您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
