### ISSUE TITLE
[BUG] 日志爆了

### ISSUE THREAD

**Issue by Ns2Kracy** [libnyanpasu/clash-nyanpasu#637]
### 复现步骤 / Step to reproduce

不清楚复现的过程。在日常使用中突然出现。

### 预期行为 / Expected behaviour

应该是很小的日志文件

### 实际行为 / Actual Behaviour

出现了一个单log 269GB,将c盘空间完全占用

### 备注 / Addition details

![a392c220fea074b6856a3072158e929e_720](https://github.com/LibNyanpasu/clash-nyanpasu/assets/89824014/72888599-290c-47dc-a64d-8ed9cc11e710)
![c4e550db71a82db963e400a00b8e3593](https://github.com/LibNyanpasu/clash-nyanpasu/assets/89824014/763f3e11-7241-43de-9366-70df4132fbfe)
![5f84d7f4dabd78d4f255ac7b1ba01c1f_720](https://github.com/LibNyanpasu/clash-nyanpasu/assets/89824014/fbf1b79a-f0bb-4197-89e0-d4063f4ebeb1)

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.0

### Clash 核心及其版本号 / Clash core and version

v1.18.1 Meta

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windows 11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
你是不是开了 trace level 忘记关了？正常使用建议开启 info 以上的等级



发自我的iPhone


------------------ 原始邮件 ------------------
From: Ns2Kracy ***@***.***&gt;
发送时间: 03/19/2024, 17:34
To: LibNyanpasu/clash-nyanpasu ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
Subject: Re: [LibNyanpasu/clash-nyanpasu] [BUG] 日志爆了 (Issue #637)





 
复现步骤 / Step to reproduce
 
不清楚复现的过程。在日常使用中突然出现。
 
预期行为 / Expected behaviour
 
应该是很小的日志文件
 
实际行为 / Actual Behaviour
 
出现了一个单log 269GB,将c盘空间完全占用
 
应用日志 / App logs
 
No response
 
备注 / Addition details
 
a392c220fea074b6856a3072158e929e_720.jpg (view on web)
 c4e550db71a82db963e400a00b8e3593.png (view on web)
 5f84d7f4dabd78d4f255ac7b1ba01c1f_720.jpg (view on web)
 
Clash Nyapasu 版本号 / Clash Nyapasu
 
1.5.0
 
Clash 核心及其版本号 / Clash core and version
 
v1.18.1 Meta
 
是否为 Pre-release / Is pre-release version
 
否
 
操作系统及版本 / OS version
 
Windows 11
 
自查步骤 / Verify steps
  
 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request 

 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly 

 您已仔细查看并知情 Q&amp;A 和 FAQ 中的内容 / You have read and understood the contents of Q&amp;A and FAQ. 

 您已搜索过 Issue Tracker，没有找到类似内容 / I have searched on Issue Tracker, No duplicate or related open issue has been found 

 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs 

 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by Ns2Kracy** [comment]
并不是。之前的log都是正常的大概几十kb。日志等级也是info
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/89824014/78a6820f-2709-41fe-a257-70aeeed1f064)

**Comment by greenhat616** [comment]
杂项设置里有个 App Level



发自我的iPhone


------------------ 原始邮件 ------------------
From: Ns2Kracy ***@***.***&gt;
发送时间: 03/19/2024, 17:47
To: LibNyanpasu/clash-nyanpasu ***@***.***&gt;
抄送: Jonson Petard ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [LibNyanpasu/clash-nyanpasu] [BUG] 日志爆了 (Issue #637)





 
并不是。之前的log都是正常的大概几十kb。日志等级也是info
 image.png (view on web)

**Comment by Ns2Kracy** [comment]
> 杂项设置里有个 App Level 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ From: Ns2Kracy ***@***.***&gt; 发送时间: 03/19/2024, 17:47 To: LibNyanpasu/clash-nyanpasu ***@***.***&gt; 抄送: Jonson Petard ***@***.***&gt;, Comment ***@***.***&gt; Subject: Re: [LibNyanpasu/clash-nyanpasu] [BUG] 日志爆了 (Issue #637) 并不是。之前的log都是正常的大概几十kb。日志等级也是info image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/89824014/8e1f9f32-d596-4501-b433-6fa9c752f8fb)

**Comment by Ns2Kracy** [comment]
> > 杂项设置里有个 App Level 发自我的iPhone
> > […](#)
> > ------------------ 原始邮件 ------------------ From: Ns2Kracy _**@**_._**> 发送时间: 03/19/2024, 17:47 To: LibNyanpasu/clash-nyanpasu _**@**_.**_> 抄送: Jonson Petard _**@**_._**>, Comment _**@**_.**_> Subject: Re: [LibNyanpasu/clash-nyanpasu] [BUG] 日志爆了 (Issue #637) 并不是。之前的log都是正常的大概几十kb。日志等级也是info image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> ![image](https://private-user-images.githubusercontent.com/89824014/314011003-8e1f9f32-d596-4501-b433-6fa9c752f8fb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA4NDMzNDUsIm5iZiI6MTcxMDg0MzA0NSwicGF0aCI6Ii84OTgyNDAxNC8zMTQwMTEwMDMtOGUxZjlmMzItZDU5Ni00NTAxLWI0MzMtNmZhOWM3NTJmOGZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE5VDEwMTA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxMDY4MGIzYzhiNDFmNmFjMzc4Yjk2MmRlZjNlMjM3YWMwYjg4N2IwODQyYWY2YWE0OGY5NjhmOGJkZWFhMDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r5BDBAr5_MvSiURR8r8rsPnyncsKGcfhkWj7seBT1aU)

所以说不知道形成这个日志炸弹的原因，也不知道该如何复现。

**Comment by greenhat616** [comment]
把超大的日记打开来看一下，如果打不开的话能否压缩一下，提交上来

**Comment by Ns2Kracy** [comment]
> 把超大的日记打开来看一下，如果打不开的话能否压缩一下，提交上来

这个文件将c盘所有空间都占了，1字节都没留，所以只能删除了，不然啥都干不了。

下午做的事大概就是开着代理开着腾讯会议看视频，期间有几次开启/关闭系统代理。

**Comment by Ns2Kracy** [comment]
> 把超大的日记打开来看一下，如果打不开的话能否压缩一下，提交上来

我想的原因是logger因为一些原因形成了一个txt炸弹？正常的log无论如何是到不了上百G并且将整个盘的容量吃干净

**Comment by LJason77** [comment]
我前段时间也遇上了，生成了一个 400 多G的日志，当时软件非常卡。
就是日常的操作，好像也没干啥，删除日志并且重启电脑就好了。

**Comment by LJason77** [comment]
复现了：
![屏幕截图 2024-05-01 173331](https://github.com/LibNyanpasu/clash-nyanpasu/assets/11374869/e7c319b3-3b4a-4322-b1ba-7587b1ce20d2)

硬盘爆了，但时间刚好卡在晚上 12 点，30 号的文件太大打不开，1 号的小一点，勉强打开看了一部分，最多的是：
```json
{"timestamp":"2024-05-01T01:10:13.550601Z","level":"ERROR","fields":{"message":"Incoming connection failed: 管道正在被关闭。 (os error 232)","log.target":"tauri_plugin_deep_link::platform_impl","log.module_path":"tauri_plugin_deep_link::platform_impl","log.file":"tauri-plugin-deep-link\\src\\windows.rs","log.line":62},"target":"tauri_plugin_deep_link::platform_impl","filename":"tauri-plugin-deep-link\\src\\windows.rs","line_number":62}
```

**Comment by 4o3F** [comment]
@LJason77 能看下这种错误的时间戳是紧挨着的，类似于爆炸式出现的么？还是隔一会出现一次？

**Comment by LJason77** [comment]
@4o3F 时间戳连续的，爆炸式出现的，文件太大已经删除了。

**Comment by 4o3F** [comment]
请问下你的杀软是哪个？pipeline被强制关闭这个一般来说是权限更高的程序才能做到

**Comment by LJason77** [comment]
没有使用任何杀软，只有微软自带的，并且开发需要把所有盘都设置为排除扫描了。
可能相关的操作：压缩虚幻引擎源码时把内存占用到 99%、编译虚幻引擎时把 CPU 占用到 100%（硬盘也疯狂读写）。

**Comment by LJason77** [comment]
看了记录，第一次遇上好像是在看剧（？），时间太久记不清了。
30 号晚上事发时并没有编译或压缩，就日常在写代码，没有特别重的任务。

**Comment by 4o3F** [comment]
开发版 5030fc9c3dd241e24f26fb3f4d7bf41a4bb9ef9f 对该问题有缓解，若仍出现问题请报告

**Comment by LJason77** [comment]
之前又出现了多次把硬盘拉爆写不进新东西导致丢数据的情况，所以我把日志设置为 Slient 直接关了，再也没有遇到过占满硬盘的情况，只是偶尔会断连，重新启动就好了。
所以没意外的话应该不会开启日志了，抱歉（丢数据真的非常让人头疼。

**Comment by greenhat616** [comment]
@4o3F  感觉还可以魔改 tracing appender 添加日记轮转的功能？

**Comment by 4o3F** [comment]
> @4o3F 感觉还可以魔改 tracing appender 添加日记轮转的功能？

那样只能是缓解把硬盘写爆的问题，没法缓解他不停的写的问题

**Comment by greenhat616** [comment]
问题原因是 blocking named pipe 遇到问题不断关闭，可能和操作系统有关系。目前新版本已经重构成 nonblocking 的 named pipe，不会遭遇这个问题了。
