### ISSUE TITLE
Dev-347ce03之后每个版本更新都会报错

### ISSUE THREAD

**Issue by w0ngzf325** [LibNyanpasu/clash-nyanpasu#639]
### 复现步骤 / Step to reproduce

1.使用x64-setup.exe一直默认指导安装完成。
2.或者将解压后portable文件夹中除【.config】以外的文件复制黏贴到【Clash Nyanpasu】文件夹。
3.尝试过卸载重装还是不行。Clash.Nyanpasu_1.5.1-alpha+860c016_x64版本可以正常打开。

### 预期行为 / Expected behaviour

正常开启

### 实际行为 / Actual Behaviour

打开任务管理器显示service、mihomo-core、nyanpasu已启动，但无法打开面板。
<img width="266" alt="1710846799982" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/128272180/50c0df63-9923-4f54-832d-3a4b9fd82131">

### 应用日志 / App logs

https://gist.github.com/w0ngzf325/4da96090a53166919b77709dc6b7141e

### Clash Nyapasu 版本号 / Clash Nyapasu

Clash.Nyanpasu_1.5.1- alpha+347ce03_x64及以后

### Clash 核心及其版本号 / Clash core and version

mihomo-windows-amd64-v1.18.1/mihomo-windows-amd64-alpha-b3db113

### 是否为 Pre-release / Is pre-release version

Clash.Nyanpasu_1.5.1- alpha+347ce03_x64及以后

### 操作系统及版本 / OS version

Windows 11 专业版 23H2 22635.3350

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
@keiko233 cc. 
Unwrap 在 `main.rs` 中的 `get_window` 方法，推测用户开启了 slient 启动模式。可以修改到 lib 里的 create_window fn 中吗？

**Comment by keiko233** [comment]
> @keiko233 cc. Unwrap 在 `main.rs` 中的 `get_window` 方法，推测用户开启了 slient 启动模式。可以修改到 lib 里的 create_window fn 中吗？

当然可以

**Comment by keiko233** [comment]
done https://github.com/LibNyanpasu/clash-nyanpasu/commit/41fdd906ddd89ae62787fbba48362792e50fce2b

等待下一个pre release构建即可安装修复
