### ISSUE TITLE
与Clash for Windows 同款的“代理规则预加载”功能

### ISSUE THREAD

**Issue by SDK-China** [LibNyanpasu/clash-nyanpasu#650]
### 需求 / Requirement

通过简单的代码设置，可以把自己想添加的代理规则添加进导入后的现有规则中，且每次代理更新后自动将自己设置的代理规则自动添加进代理规则中

这样做的好处是，可以自定义代理规则，用起来很舒服

### 建议实现 / Suggested implements

我也没什么好建议，我觉得和原版Clash做的一样就可以了吧...
<img width="638" alt="微信截图_20240320225214" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/90819364/c94cb5c8-e683-43a9-a68d-ff57ebdcfd76">
<img width="638" alt="微信图片_20240320225633" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/90819364/189074fa-a987-4b7a-bac3-725df256e28b">

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.0

### 是否为 Pre-release / Is pre-release version

0a915bf

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by SDK-China** [comment]
如果clash nyanpasu本身拥有此功能请告知我位置，谢谢，我没找到

**Comment by RESTART1230** [comment]
https://github.com/zzzgydi/clash-verge/issues/893
https://github.com/abrclano/Meandering.Path/tree/main

**Comment by greenhat616** [comment]
https://nyanpasu.elaina.moe/zh-CN/tutorial/proxy-chain.html

**Comment by bbhsky** [comment]
我想让任意url都可以使用这个加载如何配置？

**Comment by keiko233** [comment]
> 我想让任意url都可以使用这个加载如何配置？

1.5.1 及以往版本 script作用于全局，profile应用之前都会执行script和merge

**Comment by AdeSpike** [comment]
是否未来能够支持多订阅的不同自定义规则，类似CFW的parsers，通过-url参数指定不同订阅，并且在每个url下配置各自的prepend-rules。实现多个订阅拥有各自的预处理规则

**Comment by greenhat616** [comment]
profile 有自己的 chains 支持，可以在 profile 级别应用自己的的处理策略
