### ISSUE TITLE
哪个版本Win7可以用，希望说明一下

### ISSUE THREAD

**Issue by wilsonjor** [LibNyanpasu/clash-nyanpasu#664]
### 需求 / Requirement

我电脑是Win7 X64系统，新版本不能用，哪个版本能用希望说明一下

### 建议实现 / Suggested implements

Win7 能用的版本是哪个

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.0

### 是否为 Pre-release / Is pre-release version

正式版

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/issues/307

您已搜索过 Issue Tracker，没有找到类似内容 / I have searched on Issue Tracker, No duplicate or related open issue has been found

**Comment by test4uninstall** [comment]
1.4.5可以在Windows7环境下运行，版本再高就无法运行了。
记得下载compatible-go121的mihomo并替换。
如果想在Windows7环境下运行最新版本，可以借助vxkex项目来运行。

**Comment by test4uninstall** [comment]
1.4.5可以在Windows7环境下运行，版本再高就无法运行了。
记得下载compatible-go121版本的mihomo并替换。
如果想在Windows7环境下运行最新版本，可以借助vxkex项目来运行。

**Comment by test4uninstall** [comment]
1.4.5可以在Windows7环境下运行，版本再高就无法运行了。
记得下载compatible-go121版本的mihomo并替换。
如果想在Windows7环境下运行最新版本，可以借助VxKex项目来运行。
