### ISSUE TITLE
macOS启动报错，但点击后可正常使用

### ISSUE THREAD

**Issue by Majirefy** [LibNyanpasu/clash-nyanpasu#665]
### 复现步骤 / Step to reproduce

<img width="372" alt="image" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/3023607/bc8815ab-860b-47fc-8201-cf933a552a7a">

每次启动客户端，都会有如上报错，点击OK之后，有一定概率“代理”页面为空白，有时候可加载。均不影响正常使用。

### 预期行为 / Expected behaviour

应该正常启动，不报错。

### 实际行为 / Actual Behaviour

实际每次启动都会报错。

### Clash Nyapasu 版本号 / Clash Nyapasu

1.5.0

### Clash 核心及其版本号 / Clash core and version

v1.18.1 Meta

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

macOS 14.4

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/issues/639

pre release已修复，或者等1.5.1发布
