### ISSUE TITLE
Content-Disposition Filename 读取失败问题

### ISSUE THREAD

**Issue by SummonHIM** [LibNyanpasu/clash-nyanpasu#703]
### 复现步骤 / Step to reproduce

导入使用 Subconverter 转换后的订阅链接，无法正常读取文件名，订阅名称显示Remote file

### 预期行为 / Expected behaviour

导入使用 Subconverter 转换后的订阅链接，设置filename=ABC。导入订阅后订阅名称正常显示ABC

### 实际行为 / Actual Behaviour

导入使用 Subconverter 转换后的订阅链接，无法正常读取文件名，订阅名称显示Remote file

### 备注 / Addition details

和 [clash-verge-rev#165](https://github.com/clash-verge-rev/clash-verge-rev/issues/165) 一样
subconverter 返回的 Content-Disposition 是：
```
attachment; filename="<UTF8文本>"; filename*=utf-8''<utf8 url encode>
```
多了这个utf8转码就无法正确识别了，算是老verge开始就有的Bug

rev的解决方案：[99851b2](https://github.com/clash-verge-rev/clash-verge-rev/commit/99851b297d555b3724651408b57b714fae6a4a40)

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.0 & 1.5.1-alpha+593a2ed

### Clash 核心及其版本号 / Clash core and version

v1.18.1 Meta

### 是否为 Pre-release / Is pre-release version

593a2ed

### 操作系统及版本 / OS version

Windows 10.0.19045.4170

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
请尝试一下早上九时左右会自动构建的开发版。谢谢！

**Comment by SummonHIM** [comment]
> 请尝试一下早上九时左右会自动构建的开发版。谢谢！

抱歉 这几天没法用电脑 清明后尝试

**Comment by SummonHIM** [comment]
> 请尝试一下早上九时左右会自动构建的开发版。谢谢！

已测试 可以使用
