### ISSUE TITLE
Windows11 开机启动所有页面空白

### ISSUE THREAD

**Issue by wuxian** [LibNyanpasu/clash-nyanpasu#723]
### 复现步骤 / Step to reproduce

100%触发，设置开机启动的话开机启动后所有的ui空白，不要问日志，日志也是空白，但是功能是没问题的，走的代理，手动退出重启正常

### 预期行为 / Expected behaviour

他应该不空白

### 实际行为 / Actual Behaviour

![1712368877781](https://github.com/LibNyanpasu/clash-nyanpasu/assets/2416757/af57bff8-91e5-4955-a792-b540f99bb6eb)
![1712368904918](https://github.com/LibNyanpasu/clash-nyanpasu/assets/2416757/890ae54e-67bc-43ec-8504-593d30bbcd5e)
![1712368922706](https://github.com/LibNyanpasu/clash-nyanpasu/assets/2416757/07f844e9-b275-4c8a-9978-1c06989429e7)
![1712370066281](https://github.com/LibNyanpasu/clash-nyanpasu/assets/2416757/85ff0f45-44e6-4b72-ab05-11e98314c1de)

### 应用日志 / App logs

无

### Clash Nyanpasu 版本号 / Clash Nyanpasu

最新

### Clash 核心及其版本号 / Clash core and version

最新

### 是否为 Pre-release / Is pre-release version

最新

### 操作系统及版本 / OS version

Windows11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by Soniceso** [comment]
我也遇到了，不算百分百，差不多五五开吧

**Comment by greenhat616** [comment]
您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly

https://nyanpasu.elaina.moe/zh-CN/others/faq.html#_3-%E5%A6%82%E4%BD%95%E4%BF%AE%E6%94%B9%E6%97%A5%E8%AE%B0%E7%AD%89%E7%BA%A7

https://nyanpasu.elaina.moe/zh-CN/others/faq.html#_2-clash-nyanpasu-%E5%BA%94%E7%94%A8-%E6%97%A5%E8%AE%B0%E7%9B%AE%E5%BD%95%E5%9C%A8%E5%93%AA%E9%87%8C

**Comment by Status-Cai** [comment]
可以修改外部控制的端口策略为fixed临时解决
