### ISSUE TITLE
支持自定义应用目录下的 profiles 文件夹目录

### ISSUE THREAD

**Issue by leic4u** [LibNyanpasu/clash-nyanpasu#728]
### 需求 / Requirement

目前 Nyanpasu 已经支持了自定义整个应用目录 #323 ，感谢开发者们的辛苦支持。

期望可以单独自定义应用目录下的 profiles 文件夹，这里面存放的是导入的订阅。

原始需求在这里 [#323 comment](https://github.com/LibNyanpasu/clash-nyanpasu/issues/323#issuecomment-1975162977)

> 解释下为什么会有这个需求：
>
> 因为我是手写的配置文件，但是又有多台设备。当我修改了配置文件后，我必须在每台设备上都去做一次修改，这有点太难受了。
目前我是通过把整个 Portable 版安装到到 Onedrive 目录下进行同步的，多台设备同时开启时，又会出现同步问题。
>
> 请开发者大佬们酌情考虑下。

### 建议实现 / Suggested implements

在设置中增加一个配置目录，如下：
![Clip_2024-04-07_22-46-50](https://github.com/LibNyanpasu/clash-nyanpasu/assets/32786903/cde97936-d990-414a-af71-6d556e694a91)

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### 是否为 Pre-release / Is pre-release version

818dd0e

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
最新开发版已经分离配置目录和数据目录了，您可以随意修改配置目录到任何地方（用于云同步等目的）欢迎测试
