### ISSUE TITLE
没有定时同步订阅

### ISSUE THREAD

**Issue by MartinDai** [LibNyanpasu/clash-nyanpasu#730]
### 复现步骤 / Step to reproduce

我配置的是60分钟同步一次，但是过了2小时了还是没有同步
<img width="606" alt="image" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/11816720/ed8a8135-4e02-479a-8b29-3ff283bf47a1">

### 预期行为 / Expected behaviour

根据配置定时执行同步订阅

### 实际行为 / Actual Behaviour

没有定时执行订阅

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1-alpha+b60d680

### Clash 核心及其版本号 / Clash core and version

v1.18.3 Meta

### 是否为 Pre-release / Is pre-release version

b60d680

### 操作系统及版本 / OS version

macOS 14.4.1

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
请检查手动更新是否成功，默认更新不走代理，可能会导致因网络问题导致更新失败

**Comment by MartinDai** [comment]
最新版本好像正常了
