### ISSUE TITLE
怎麼每次安裝都要清空設定啊...

### ISSUE THREAD

**Issue by KomiyaTaichi** [LibNyanpasu/clash-nyanpasu#739]
### 需求 / Requirement

安裝保留設定內容

### 建议实现 / Suggested implements

安裝保留設定內容

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### 是否为 Pre-release / Is pre-release version

否

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
覆盖安装的时候选择了卸载以往版本嘛？

**Comment by KomiyaTaichi** [comment]
> 覆盖安装的时候选择了卸载以往版本嘛？

應用內檢查更新的，是直接安裝啊

**Comment by ningsibuqu** [comment]
是的 这回应用内更新 清空数据了

**Comment by Bformax** [comment]
这回确实清空了，不过之前的服务起不来的Bug修好了

**Comment by greenhat616** [comment]
目前开发版应该是不会清除数据的了
