### ISSUE TITLE
[Bug] 1.5.1 不支持 Hysteria 2(HY2) 协议, 而原来的 1.4.5 是支持的

### ISSUE THREAD

**Issue by foobarjohnny** [LibNyanpasu/clash-nyanpasu#751]
### 复现步骤 / Step to reproduce

1. 导入含有 HY2 节点的订阅地址, 例如 https://aa1.tcip.top/api/v1/client/subscribe?token=eed54358f653801ba3657084db0b37d5

### 预期行为 / Expected behaviour

像 1.4.5 版本一样能够导入 HY2 节点

### 实际行为 / Actual Behaviour

没有导入 HY2 节点, 只导入了 ss, vmess 等其他协议的节点.

### 备注 / Addition details

旧的 Clash Verge 1.3.8 本身支持导入 HY2 节点

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### Clash 核心及其版本号 / Clash core and version

v1.18.3 meta

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windows 10

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
需要你的机场适配nyanpasu客户端的ua ，或者支持clash meta订阅下发
https://github.com/LibNyanpasu/clash-nyanpasu/commit/88ccfcd8705cf192bd73f12f1e51b77accf46f7e#diff-b2a02de04097d124ea3ce0fcf6066ad39465f933e9989543ff406acf2b3c0633R216

**Comment by foobarjohnny** [comment]
我手上有 7 个提供 HY2 节点的机场, 目前全军覆没, 没一个支持 1.5.x 版的 Nyanpasu 客户端. 我都不知道说啥了.

**Comment by keiko233** [comment]
因为根本原因是机场没有适配，但是你依然可以手动修改nyanpasu发送的ua，修改为clash-verge/v.1.5.1，就可以了

![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/76520798/9a67d4d4-be32-40de-bd70-0056435395b2)

**Comment by greenhat616** [comment]
是否支持 Hy2 协议取决于内核，你这种是机场自己不给你发放 Hy2 配置。你应该要求机场支持识别 Nyanapsu 以便其提供 Hy2 协议，或者右键你的 Profile，手动修改 UA。

**Comment by greenhat616** [comment]
右键你的配置文件，点修改配置。



发自我的iPhone


------------------ 原始邮件 ------------------
From: foobarjohnny ***@***.***&gt;
发送时间: 04/11/2024, 17:39
To: LibNyanpasu/clash-nyanpasu ***@***.***&gt;
抄送: Jonson Petard ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [LibNyanpasu/clash-nyanpasu] [Bug] 1.5.1 不支持 Hysteria 2(HY2) 协议, 而原来的 1.4.5 是支持的 (Issue #751)





  
因为根本原因是机场没有适配，但是你依然可以手动修改nyanpasu发送的ua，修改为clash-verge/v.1.5.1，就可以了
 

  
是在源代码中修改, 还是在配置文件中修改 ?

**Comment by foobarjohnny** [comment]
> 右键你的配置文件，点修改配置。 发自我的iPhone

使用上面的订阅地址, 按你说的方法改了, 结果中虽然增加了 vless 节点, 但是仍然没有 Hy2 节点.

**Comment by greenhat616** [comment]
把订阅链接发邮件给 keiko，让他确认一下。

再次声明一下，处理订阅的只和内核有关系，系 Clash premium、Clash Meta、Clash Rust，我们没有修改任何行为。应优先要求机场不要搞那种花里胡哨的兼容需求才对。

**Comment by foobarjohnny** [comment]
了解, 已发邮件给 keiko
