### ISSUE TITLE
代理页面空白无法正常工作

### ISSUE THREAD

**Issue by Soniceso** [LibNyanpasu/clash-nyanpasu#763]
### 复现步骤 / Step to reproduce

具体复现步骤未知，设置为开机自启之后每次开机时都有概率触发

### 预期行为 / Expected behaviour

正常应该是这样
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/10915608/355c4483-31f9-4018-97f4-ed01bf848dcd)

### 实际行为 / Actual Behaviour

![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/10915608/1cc14f23-2780-4b00-b31b-fba94a12ea8d)

### 应用日志 / App logs

{"timestamp":"2024-04-12T03:46:27.363029Z","level":"WARN","fields":{"message":"NewEvents emitted without explicit RedrawEventsCleared","log.target":"tao::platform_impl::platform::event_loop::runner","log.module_path":"tao::platform_impl::platform::event_loop::runner","log.file":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.8\\src\\platform_impl\\windows\\event_loop\\runner.rs","log.line":359},"target":"tao::platform_impl::platform::event_loop::runner","filename":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.8\\src\\platform_impl\\windows\\event_loop\\runner.rs","line_number":359}
{"timestamp":"2024-04-12T03:46:27.378275Z","level":"WARN","fields":{"message":"RedrawEventsCleared emitted without explicit MainEventsCleared","log.target":"tao::platform_impl::platform::event_loop::runner","log.module_path":"tao::platform_impl::platform::event_loop::runner","log.file":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.8\\src\\platform_impl\\windows\\event_loop\\runner.rs","log.line":345},"target":"tao::platform_impl::platform::event_loop::runner","filename":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.8\\src\\platform_impl\\windows\\event_loop\\runner.rs","line_number":345}
{"timestamp":"2024-04-12T06:59:37.438193Z","level":"WARN","fields":{"message":"The external controller port has been changed to 127.0.0.1:34181","log.target":"clash_verge::config::clash","log.module_path":"clash_verge::config::clash","log.file":"tauri\\src\\config\\clash\\mod.rs","log.line":115},"target":"clash_verge::config::clash","filename":"tauri\\src\\config\\clash\\mod.rs","line_number":115,"span":{"self":"IClashTemp(Mapping {\"mixed-port\": Number(34173), \"log-level\": String(\"info\"), \"allow-lan\": Bool(false), \"mode\": String(\"rule\"), \"external-controller\": String(\"127.0.0.1:9090\"), \"secret\": String(\"\"), \"unified-delay\": Bool(true), \"tcp-concurrent\": Bool(true), \"ipv6\": Bool(false)})","name":"prepare_external_controller_port"},"spans":[{"self":"IClashTemp(Mapping {\"mixed-port\": Number(34173), \"log-level\": String(\"info\"), \"allow-lan\": Bool(false), \"mode\": String(\"rule\"), \"external-controller\": String(\"127.0.0.1:9090\"), \"secret\": String(\"\"), \"unified-delay\": Bool(true), \"tcp-concurrent\": Bool(true), \"ipv6\": Bool(false)})","name":"prepare_external_controller_port"}]}
{"timestamp":"2024-04-12T06:59:54.950363Z","level":"WARN","fields":{"message":"NewEvents emitted without explicit RedrawEventsCleared","log.target":"tao::platform_impl::platform::event_loop::runner","log.module_path":"tao::platform_impl::platform::event_loop::runner","log.file":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.8\\src\\platform_impl\\windows\\event_loop\\runner.rs","log.line":359},"target":"tao::platform_impl::platform::event_loop::runner","filename":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.8\\src\\platform_impl\\windows\\event_loop\\runner.rs","line_number":359}
{"timestamp":"2024-04-12T06:59:54.964462Z","level":"WARN","fields":{"message":"RedrawEventsCleared emitted without explicit MainEventsCleared","log.target":"tao::platform_impl::platform::event_loop::runner","log.module_path":"tao::platform_impl::platform::event_loop::runner","log.file":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.8\\src\\platform_impl\\windows\\event_loop\\runner.rs","log.line":345},"target":"tao::platform_impl::platform::event_loop::runner","filename":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.8\\src\\platform_impl\\windows\\event_loop\\runner.rs","line_number":345}
{"timestamp":"2024-04-12T06:59:59.345390Z","level":"WARN","fields":{"message":"update proxies failed: error sending request for url (http://127.0.0.1:34181/providers/proxies): error trying to connect: tcp connect error: 由于目标计算机积极拒绝，无法连接。 (os error 10061)\n\nCaused by:\n    0: error trying to connect: tcp connect error: 由于目标计算机积极拒绝，无法连接。 (os error 10061)\n    1: tcp connect error: 由于目标计算机积极拒绝，无法连接。 (os error 10061)\n    2: 由于目标计算机积极拒绝，无法连接。 (os error 10061)"},"target":"clash_verge::core::tray::proxies","filename":"tauri\\src\\core\\tray\\proxies.rs","line_number":23,"span":{"name":"loop_task"},"spans":[{"name":"loop_task"}]}
{"timestamp":"2024-04-12T06:59:59.345582Z","level":"ERROR","fields":{"message":"proxies not updated yet!!!!"},"target":"clash_verge::core::tray::proxies","filename":"tauri\\src\\core\\tray\\proxies.rs","line_number":29,"span":{"name":"loop_task"},"spans":[{"name":"loop_task"}]}
{"timestamp":"2024-04-12T07:00:23.131624Z","level":"WARN","fields":{"message":"update proxies failed: error sending request for url (http://127.0.0.1:34181/providers/proxies): error trying to connect: tcp connect error: 由于目标计算机积极拒绝，无法连接。 (os error 10061)\n\nCaused by:\n    0: error trying to connect: tcp connect error: 由于目标计算机积极拒绝，无法连接。 (os error 10061)\n    1: tcp connect error: 由于目标计算机积极拒绝，无法连接。 (os error 10061)\n    2: 由于目标计算机积极拒绝，无法连接。 (os error 10061)"},"target":"clash_verge::core::tray::proxies","filename":"tauri\\src\\core\\tray\\proxies.rs","line_number":23,"span":{"name":"loop_task"},"spans":[{"name":"loop_task"}]}
{"timestamp":"2024-04-12T07:00:23.131673Z","level":"ERROR","fields":{"message":"proxies not updated yet!!!!"},"target":"clash_verge::core::tray::proxies","filename":"tauri\\src\\core\\tray\\proxies.rs","line_number":29,"span":{"name":"loop_task"},"spans":[{"name":"loop_task"}]}
{"timestamp":"2024-04-12T07:00:47.008352Z","level":"WARN","fields":{"message":"update proxies failed: error sending request for url (http://127.0.0.1:34181/providers/proxies): error trying to connect: tcp connect error: 由于目标计算机积极拒绝，无法连接。 (os error 10061)\n\nCaused by:\n    0: error trying to connect: tcp connect error: 由于目标计算机积极拒绝，无法连接。 (os error 10061)\n    1: tcp connect error: 由于目标计算机积极拒绝，无法连接。 (os error 10061)\n    2: 由于目标计算机积极拒绝，无法连接。 (os error 10061)"},"target":"clash_verge::core::tray::proxies","filename":"tauri\\src\\core\\tray\\proxies.rs","line_number":23,"span":{"name":"loop_task"},"spans":[{"name":"loop_task"}]}
{"timestamp":"2024-04-12T07:00:47.008512Z","level":"ERROR","fields":{"message":"proxies not updated yet!!!!"},"target":"clash_verge::core::tray::proxies","filename":"tauri\\src\\core\\tray\\proxies.rs","line_number":29,"span":{"name":"loop_task"},"spans":[{"name":"loop_task"}]}
{"timestamp":"2024-04-12T07:00:49.841316Z","level":"WARN","fields":{"message":"NewEvents emitted without explicit RedrawEventsCleared","log.target":"tao::platform_impl::platform::event_loop::runner","log.module_path":"tao::platform_impl::platform::event_loop::runner","log.file":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.8\\src\\platform_impl\\windows\\event_loop\\runner.rs","log.line":359},"target":"tao::platform_impl::platform::event_loop::runner","filename":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.8\\src\\platform_impl\\windows\\event_loop\\runner.rs","line_number":359}
{"timestamp":"2024-04-12T07:00:49.852532Z","level":"WARN","fields":{"message":"RedrawEventsCleared emitted without explicit MainEventsCleared","log.target":"tao::platform_impl::platform::event_loop::runner","log.module_path":"tao::platform_impl::platform::event_loop::runner","log.file":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.8\\src\\platform_impl\\windows\\event_loop\\runner.rs","log.line":345},"target":"tao::platform_impl::platform::event_loop::runner","filename":"C:\\Users\\runneradmin\\.cargo\\registry\\src\\index.crates.io-6f17d22bba15001f\\tao-0.16.8\\src\\platform_impl\\windows\\event_loop\\runner.rs","line_number":345}
{"timestamp":"2024-04-12T07:00:54.112863Z","level":"INFO","fields":{"message":"reset proxy with no action","log.target":"app","log.module_path":"clash_verge::core::sysopt","log.file":"tauri\\src\\core\\sysopt.rs","log.line":137},"target":"app","filename":"tauri\\src\\core\\sysopt.rs","line_number":137,"span":{"name":"cleanup_processes"},"spans":[{"name":"on_system_tray_event"},{"name":"quit_application"},{"name":"cleanup_processes"}]}

### 备注 / Addition details

和这个情况一样https://github.com/LibNyanpasu/clash-nyanpasu/issues/723

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### Clash 核心及其版本号 / Clash core and version

1.18.3 meta

### 是否为 Pre-release / Is pre-release version

false

### 操作系统及版本 / OS version

win11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
主要问题是这个：
![图片](https://github.com/LibNyanpasu/clash-nyanpasu/assets/41122242/8fe728f0-c697-41d2-9a32-9750ea342373)

我们猜测和内核或者操作系统防火墙有关系，他们的 controller 接口不可用。不太清楚具体原因——你的代理可用，意味着内核已正确启动。

**Comment by Soniceso** [comment]
> 主要问题是这个： ![图片](https://private-user-images.githubusercontent.com/41122242/322191040-8fe728f0-c697-41d2-9a32-9750ea342373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwMDU2NjMsIm5iZiI6MTcxMzAwNTM2MywicGF0aCI6Ii80MTEyMjI0Mi8zMjIxOTEwNDAtOGZlNzI4ZjAtYzY5Ny00MWQyLTlhMzItOTc1MGVhMzQyMzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDEzVDEwNDkyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlMThhYTFlN2Y4NjUwMTc5ZDgyN2FkOTg2ZmUzM2Q4ZGY1MGZjMWU3OTI4OGRkYmMwMDZjZWEwNWVhZTZmMTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AXjckSYPs7_4NpZHxKitK25LLgD_GlvHlwbPOp02BlQ)
> 
> 我们猜测和内核或者操作系统防火墙有关系，他们的 controller 接口不可用。不太清楚具体原因——你的代理可用，意味着内核已正确启动。

防火墙的话我用的系统自带的，杀软也是WD，这个触发我目前来看确实只能是看概率，我今天重启两次也没遇到，昨天重启两次遇到两次，这个问题大概是前两个版本出现的，当时还以为是自己的问题，后来看到也有人发issue遇到了才又发了一遍。

**Comment by greenhat616** [comment]
目前初步判断与服务模式使用的端口和 UI 的端口存在差异，导致首次启动出现异常。这个问题可能要留到 1.6.0 中修复了。等修复了，可以先尝试开发版。1.6 预计要五月份发布。

**Comment by keiko233** [comment]
可以修改外部控制的secre为fixed临时解决，彻底修复需要等待重构service mode
![photo_4969865344814525751_y](https://github.com/LibNyanpasu/clash-nyanpasu/assets/76520798/c6938659-50a9-4553-bf17-348bcb6b4abb)

**Comment by Edge-coordinates** [comment]
Meet the same problem~ 期待修复！
