### ISSUE TITLE
最新DEV版本启动报错

### ISSUE THREAD

**Issue by chen-jingliang** [LibNyanpasu/clash-nyanpasu#776]
### 复现步骤 / Step to reproduce

1. 安装最新DEV版本
2. 启动时报错
3. 无法运行

### 预期行为 / Expected behaviour

能够正常启动

### 实际行为 / Actual Behaviour

报错内容见图
![2024-04-15 08 59 16](https://github.com/LibNyanpasu/clash-nyanpasu/assets/28627641/8c611762-7dee-44ba-8168-261048334cfe)

### Clash Nyanpasu 版本号 / Clash Nyanpasu

Clash Nyanpasu Nightly Build

### Clash 核心及其版本号 / Clash core and version

1.5.2

### 是否为 Pre-release / Is pre-release version

d9e60f2

### 操作系统及版本 / OS version

windows 11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
cc @4o3F

**Comment by 4o3F** [comment]
暂时可以通过手动删除storage目录来修复，晚些我会修复

**Comment by chen-jingliang** [comment]
手动删除了storage和storage.db目录后可以使用，但检查Nyanpasu版本信息为1.5.1，而不是1.5.2

**Comment by greenhat616** [comment]
> 手动删除了storage和storage.db目录后可以使用，但检查Nyanpasu版本信息为1.5.1，而不是1.5.2

cc @keiko233

**Comment by keiko233** [comment]
> > 手动删除了storage和storage.db目录后可以使用，但检查Nyanpasu版本信息为1.5.1，而不是1.5.2
> 
> cc @keiko233

应该是拆monorepo prepare脚本路径问题，稍晚时候修复
