### ISSUE TITLE
out of memory 如果长期不关闭 （内存持续增长）

### ISSUE THREAD

**Issue by lovitus** [LibNyanpasu/clash-nyanpasu#782]
### 复现步骤 / Step to reproduce

开启程序， 放置一晚

### 预期行为 / Expected behaviour

能正常使用

### 实际行为 / Actual Behaviour

空白显示，有类似浏览器的 out of memory， 点击刷新后， 程序界面重载。

### 备注 / Addition details

clash core 内存占用正常。
只是ui需要刷新。

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### Clash 核心及其版本号 / Clash core and version

16fadd2  clash meta(mihomo) alpha

### 是否为 Pre-release / Is pre-release version

16fadd2  

### 操作系统及版本 / OS version

windows 10 

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by lovitus** [comment]
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/14361541/6e80720a-f75a-46a4-9d38-8ea50175c6e1)
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/14361541/f5b08596-a394-44b2-a586-42bf28ba7f2b)

这是今天运行**7个小时以后的内存使用**。 
- 设备里没有其它应用使用这个edgewebview2。 
- kill掉这个进程以后，只有 Nyanpasu是奔溃的，其它所有程序都是正常显示。

**Comment by greenhat616** [comment]
得抽空做一下 profile，应该是之前哪里的 hooks 或者 inMemoryCache 泄露了

**Comment by keiko233** [comment]
pre release已经修复，经过我们的长期测试现在内存占用不再爆炸，欢迎使用。

但是考虑到Windows webview的共享特性，如果再出现类似问题建议排查下其他使用webview的程序

**Comment by lovitus** [comment]
! [image] (https://github.com/LibNyanpasu/clash-nyanpasu/assets/14361541/c65f9e42-c0e2-4027-88ed-faed0e47034f)

VER: 1.5.2  alpha a1f44fd    + mihomo alpha 

使用半小时后， 内存还是能到1G， kill掉edgewebview2后应用ui会奔溃，点击重载后内存使用恢复。
但是如果去选择节点然后最小化，内存又会增长起来 ，3-8M/s, 大概会停留在1.5G以下。

是否可能和我节点数量有关， 单个组可能有上百个节点， 有40+个组。
@keiko233 @greenhat616

**Comment by keiko233** [comment]
> ! [image] (https://github.com/LibNyanpasu/clash-nyanpasu/assets/14361541/c65f9e42-c0e2-4027-88ed-faed0e47034f)
> 
> VER: 1.5.2 alpha [a1f44fd](https://github.com/LibNyanpasu/clash-nyanpasu/commit/a1f44fd46cfe2cb3013d786c31d17845079c161f) + mihomo alpha
> 
> 使用半小时后， 内存还是能到1G， kill掉edgewebview2后应用ui会奔溃，点击重载后内存使用恢复。 但是如果去选择节点然后最小化，内存又会增长起来 ，3-8M/s, 大概会停留在1.5G以下。
> 
> 是否可能和我节点数量有关， 单个组可能有上百个节点， 有40+个组。 @keiko233 @greenhat616

滚动的地方我们都做了虚拟滚动条，理论上来说应该没有太大关系，有空的时候我再测试优化一下。

**Comment by Huiaei** [comment]
+1
长时间开着主界面或者最小化在任务栏里都会出现内存过大，关掉主界面到托盘再打开能清理一下。
![d3bc34d17ec872cf0e032d646c1e7fa2](https://github.com/LibNyanpasu/clash-nyanpasu/assets/36834765/9a468dce-7ec3-4d44-bba6-e8e24f7c6dc0)

**Comment by keiko233** [comment]
目前判断为react fiber问题，其中最大的问题在framer motion，大量的计算动画会带来内存开销。目前已经做了大量优化，可以使用最新的pre release进行测试。

**Comment by greenhat616** [comment]
![图片](https://github.com/user-attachments/assets/88836bb3-93b5-4381-af25-68c21d38a763)

**Comment by xuanxiaoyu69** [comment]
macos
1.6.1版本依旧存在，因为mac一直不关机，32G内存，居然占用了28G内存，因为太卡截不了图就重启了，下次卡住的时候再补一张图
