### ISSUE TITLE
geo配置无法加载完整

### ISSUE THREAD

**Issue by ttyy33** [LibNyanpasu/clash-nyanpasu#787]
### 复现步骤 / Step to reproduce

config.yaml里的配置文件如下:
geodata-mode: true
geox-url:
  geosite: "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat"
geodata-loader: standard
geo-auto-update: true # 
geo-update-interval: 4 

查看运行配置如下：
geox-url:
  geosite: https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat
geodata-mode: true

查看日志发现：Geodata Loader mode: memconservative

运行配置只有geox-url和geodate-mode这两个选项，没有geodata-loaader、geo-auto-update、geo-update-interval这些选项

### 预期行为 / Expected behaviour

运行配置不仅有geox-url和geodate-mode这两个设置，也要有geodata-loaader、geo-auto-update、geo-update-interval这些选项

### 实际行为 / Actual Behaviour

配置文件
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/127597621/f6a4ea3d-dfa3-465b-97f9-91939e27a46c)

运行配置
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/127597621/06cd594f-e247-440d-a75e-6a05a1cb0158)

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### Clash 核心及其版本号 / Clash core and version

v1.18.3 Meta

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Microsoft Windows [版本 10.0.19044.4046]

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
请在 Clash 字段里勾选这些选项：
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/41122242/eb19ddee-a4db-40e7-ba77-c56cfe680758)

我们计划在 1.6.0 中添加关闭字段过滤的选项，维护白名单肯定是不及时的，Clash Meta 新增字段还是蛮频繁的。 cc @keiko233 @4o3F

**Comment by ttyy33** [comment]
> 请在 Clash 字段里勾选这些选项： ![image](https://private-user-images.githubusercontent.com/41122242/323014856-eb19ddee-a4db-40e7-ba77-c56cfe680758.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzMzEzMjIsIm5iZiI6MTcxMzMzMTAyMiwicGF0aCI6Ii80MTEyMjI0Mi8zMjMwMTQ4NTYtZWIxOWRkZWUtYTRkYi00MGU3LWJhNzctYzU2Y2ZlNjgwNzU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDA1MTcwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjM2UxZjFiZTM4NjlkYWJmZDhmNWM3ODdiYzEyY2Q0OGJjNDRiYmIzNDc4OWViNTYwOTJkZjZjYmRiZGU0Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.csMCXq-OMUfZQlPqKRb8e-Xq70pN5BzeelNlyaNQsNM)
> 
> 我们计划在 1.6.0 中添加关闭字段过滤的选项，维护白名单肯定是不及时的，Clash Meta 新增字段还是蛮频繁的。 cc @keiko233 @4o3F

勾选过了，本来就勾选过了这两个选项，无法正常加载geo的所有配置。有些第三方的geosite(https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download)是在维护的，每天在更新的

**Comment by greenhat616** [comment]
哦，你是说缺少后面三个字段是吧。这是 Feature 不是 bug，Clash Meta 新增字段我们是不知道，这也是隔壁 Verge Rev 砍掉白名单模式的原因——每次新增了字段都会导致不兼容。

@keiko233 @4o3F cc 这几天有空的话，新增一下这三个字段吧。

我们未来会通过 Manifest v2、或者自定义 URL 提供 geoip 的更新支持：https://github.com/LibNyanpasu/clash-nyanpasu/issues/49

**Comment by keiko233** [comment]
> 哦，你是说缺少后面三个字段是吧。这是 Feature 不是 bug，Clash Meta 新增字段我们是不知道，这也是隔壁 Verge Rev 砍掉白名单模式的原因——每次新增了字段都会导致不兼容。
> 
> @keiko233 @4o3F cc 这几天有空的话，新增一下这三个字段吧。
> 
> 我们未来会通过 Manifest v2、或者自定义 URL 提供 geoip 的更新支持：#49

计划将写一个脚本自动生成字段，或者如果有其他更好的
