### ISSUE TITLE
启动后不能正运行，程序出现错误

### ISSUE THREAD

**Issue by Yu-xiaohei** [LibNyanpasu/clash-nyanpasu#796]
### 复现步骤 / Step to reproduce

1. 双击启动Clash nyanpasu
2. 弹出错误提示并正常打开了Clash nyanpasu
3. 所有功能均无法使用

### 预期行为 / Expected behaviour

打开后正常显示节点选择列表，代理正常工作

### 实际行为 / Actual Behaviour

![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/110207616/e54abf9f-6c7c-469a-80bf-469fa7e7f7f5)
所有基础功能均无法正常使用

### 应用日志 / App logs

错误日志：[clash-nyanpasu.2024-04-19.app.log](https://github.com/LibNyanpasu/clash-nyanpasu/files/15039867/clash-nyanpasu.2024-04-19.app.log)

### 备注 / Addition details

自行分析端口出现冲突或防火墙阻止，但电脑中仅安装 clash for windows 与 clash nyanpasu 前者端口为7891并为冲突也并未启用，防火墙未开启

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### Clash 核心及其版本号 / Clash core and version

v1.18.3 mihomo

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windows 11 beta 22635.3495

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
是否开启了服务模式，可以尝试按下面方法解决

https://github.com/LibNyanpasu/clash-nyanpasu/issues/763#issuecomment-2060237317
