### ISSUE TITLE
代理显示不一致，界面逻辑不清

### ISSUE THREAD

**Issue by chen-jingliang** [LibNyanpasu/clash-nyanpasu#815]
### 复现步骤 / Step to reproduce

1. （BUG）开启代理后，不同窗口显示的代理信息不一致，问题不定时出现，无规律
2. （UI） 按钮有偏移
3. （UI）下拉界面逻辑不清

### 预期行为 / Expected behaviour

上述问题得以解决，其中第3点，下拉节点列表应该与标题在同一个窗口，中间可以使用横线分开，而不应该分成2个窗口。

### 实际行为 / Actual Behaviour

1. 显示的代理内容不同步、不一致
![SCR-20240421-lwsj](https://github.com/LibNyanpasu/clash-nyanpasu/assets/28627641/6e0d44db-6ae3-4bb1-a1db-b006e9c86f2f)
2. 按钮有偏移
![SCR-20240420-iiky](https://github.com/LibNyanpasu/clash-nyanpasu/assets/28627641/93be7497-1c21-428c-9b5d-0fa6bb615125)
3.下拉界面逻辑不清
![2024-04-25 09 08 19](https://github.com/LibNyanpasu/clash-nyanpasu/assets/28627641/7fb432e5-b005-4758-bed2-487f0615720b)

### 备注 / Addition details

不知是否与我选择的内核有关，我选择的是clash premium内核，其它内核似乎也存在相同的问题

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.2beta

### Clash 核心及其版本号 / Clash core and version

1.18.3

### 是否为 Pre-release / Is pre-release version

beta版

### 操作系统及版本 / OS version

win11 23H2，mac14.4.1

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
It has been added as a feature in the latest preview version
