### ISSUE TITLE
请求适配，ubuntu升级到24.04版本后依赖出现问题

### ISSUE THREAD

**Issue by YXFY123** [libnyanpasu/clash-nyanpasu#829]
### 复现步骤 / Step to reproduce

![Screenshot_20240427_153309](https://github.com/LibNyanpasu/clash-nyanpasu/assets/120346621/9a441a15-6929-4418-ba11-e3084d5bb10f)

### 预期行为 / Expected behaviour

尝试了两台电脑，能确认是系统升级造成依赖被替换，最新开发版本仍存在此问题

### 实际行为 / Actual Behaviour

依赖出错

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### Clash 核心及其版本号 / Clash core and version

1.18.3

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

ubuntu 2404

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
需要等上游 Tauri 修复。目前上游还没有反馈这个问题，也许你可以尝试手动编译一下看看？

**Comment by shun2wang** [comment]
I also have this issue. because `libwebkit2gtk-4.0` not on Ubuntu 24.04 LTS, but `libwebkit2gtk-4.1-0` both available on Ubuntu 22.04 and Ubuntu 24.04, maybe upgrade build dependence will fix that?

**Comment by greenhat616** [comment]
cc @all: https://github.com/tauri-apps/tauri/issues/6151

Note that: in current point, Tauri decide not to upgrade the dependencies as this issue.

We should follow the tauri v2 as the RC channel get available.

**Comment by Love-in-idleness** [comment]
建议额外添加mantic的apt源，这样可以解决问题

**Comment by jackleeforce** [comment]
same issue for me.

**Comment by greenhat616** [comment]
https://github.com/tauri-apps/tauri/issues/9662
