### ISSUE TITLE
windows下clash-rs内核无法开启tun模式，希望添加支持

### ISSUE THREAD

**Issue by agczsz** [libnyanpasu/clash-nyanpasu#852]
### 复现步骤 / Step to reproduce

1.
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/121206519/9e642f80-f171-493f-bc87-d9763be719d4)
打开tun模式直接还原

### 预期行为 / Expected behaviour

能打开并代理系统流量

### 实际行为 / Actual Behaviour

直接被打开
![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/121206519/5803041c-73cf-4daf-bf96-f13878cee386)

### 应用日志 / App logs

后台显示并无日志

### 备注 / Addition details

tun:
  enable: false
  device-id: "dev://utun1989"
在维基上，还要开启局域网绕行
iptables -t mangle -N CLASH # Create Clash Chain

iptables -t mangle -A CLASH -d 0.0.0.0/8 -j RETURN
iptables -t mangle -A CLASH -d 10.0.0.0/8 -j RETURN
iptables -t mangle -A CLASH -d 127.0.0.0/8 -j RETURN
iptables -t mangle -A CLASH -d 169.254.0.0/16 -j RETURN
iptables -t mangle -A CLASH -d 172.16.0.0/12 -j RETURN
iptables -t mangle -A CLASH -d 192.168.0.0/16 -j RETURN
iptables -t mangle -A CLASH -d 224.0.0.0/4 -j RETURN
iptables -t mangle -A CLASH -d 240.0.0.0/4 -j RETURN
# ipset can be enabled optionally.
# iptables -t mangle -A CLASH -m set --match-set CN dst -j RETURN
iptables -t mangle -A CLASH -j MARK --set-xmark 129

iptables -t mangle -A PREROUTING -j CLASH  # have traffic come to the CLASH chain

# if you need to have the local machine(the machine clash is running on) traffic to go through clash TUN
# note: you should have clash running under the user `clash', see below systemd script
# iptables -t mangle -A OUTPUT -m owner --uid-owner clash -j RETURN
# iptables -t mangle -A OUTPUT -j CLASH

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.0

### Clash 核心及其版本号 / Clash core and version

rust0.1.15

### 是否为 Pre-release / Is pre-release version

no

### 操作系统及版本 / OS version

win11

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
tracked https://github.com/Watfaq/clash-rs/issues/396#issuecomment-2109293356

**Comment by carrotluo5** [comment]
感谢，找了半天原来是TUN模式用不了rust

**Comment by agczsz** [comment]
> tracked [Watfaq/clash-rs#396 (comment)](https://github.com/Watfaq/clash-rs/issues/396#issuecomment-2109293356)
<img width="556" alt="image" src="https://github.com/user-attachments/assets/506c0091-d081-41ec-9579-b8b42ebc0577">
官方已添加支持，可以在客户端添加路由修改支持了

**Comment by greenhat616** [comment]
开发版已经支持
