### ISSUE TITLE
system proxy doesn't support kde plasma(6)

### ISSUE THREAD

**Issue by wen-zheng** [LibNyanpasu/clash-nyanpasu#853]
### 需求 / Requirement

toggle system proxy supports kde plasma (I am on fedora 40 kde spin)

### 建议实现 / Suggested implements

no idea, but I know that fclash support kde plasma's system proxy

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### 是否为 Pre-release / Is pre-release version

no

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
@4o3F It seems that current Sysproxy not provide the KDE modifying. Should confirm it later. Thx.
https://github.com/LibNyanpasu/clash-nyanpasu/blob/main/backend/sysproxy-rs/src/linux.rs

**Comment by 4o3F** [comment]
Confirmed, KDE need a completely different way to set system proxy

**Comment by 4o3F** [comment]
Also KDE 4 and 5 need different command, `kwriteconfig` for KDE 4 and `kwriteconfig5` for KDE 5

**Comment by wen-zheng** [comment]
> Also KDE 4 and 5 need different command, `kwriteconfig` for KDE 4 and `kwriteconfig5` for KDE 5
 and `kwriteconfig6` for KDE 6

**Comment by 4o3F** [comment]
This should be fixed in 9064fe593b0081f60188f8c58496b39f82406916 , please reopen this if the issue persist
