### ISSUE TITLE
rpm package request

### ISSUE THREAD

**Issue by wen-zheng** [LibNyanpasu/clash-nyanpasu#854]
### 需求 / Requirement

I manullay converted the deb version package to rpm package and installed the rpm package in fedora successfully, so it seems that giving official rpm package is not hard. I have no idea where you build the release version package, if possible, I can help you

### 建议实现 / Suggested implements

supply the rpm package

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### 是否为 Pre-release / Is pre-release version

no

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已仔细查看并知情 [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) 中的内容 / You have checked [Q&A](https://github.com/keiko233/clash-nyanpasu/blob/main/ISSUE.md) carefully
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个功能。如果您有多个功能请求，烦请发起多个 Issue / Ensure there is only one feature request in this issue. Please make mutiply issue for mutiply feature request
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
Hello,

At the moment, the bundling process is automated by Tauri bundle. In Tauri v1, it primarily supports deb and AppImage formats for Linux platforms.

If you're interested in enhancing this process, such as incorporating the rpm packaging method (which was introduced in Tauri v2, a beta major version), you could modify the release, nightly-release CI workflow. It should involve uploading the necessary binary files to the CI artifacts, then initiating a new job block to handle the custom bundling process and uploading the results to GitHub Release artifacts.

Thank you for your involvement and contributions.

**Comment by keiko233** [comment]
rpm support backport on tauri https://github.com/tauri-apps/tauri/pull/9809
