### ISSUE TITLE
Dev版无法切换节点及无法固定全局模式

### ISSUE THREAD

**Issue by chen-jingliang** [LibNyanpasu/clash-nyanpasu#901]
### 复现步骤 / Step to reproduce

1. 安装最新DEV版(Clash.Nyanpasu_1.5.2-alpha+67e34fd)
2. 点击代理，点击全局，无法选择节点
3. 关闭窗口后，再次打开，原全局模式变成规则模式

### 预期行为 / Expected behaviour

1. 可以自由切换代理模式
2. 代理模式固定后，不会自动切换

### 实际行为 / Actual Behaviour

![2024-05-13 09 00 23](https://github.com/LibNyanpasu/clash-nyanpasu/assets/28627641/af26d82b-504c-43e0-b481-176077bbc71c)

### 备注 / Addition details

最近几天发布的DEV版本都存在无法切换节点的问题

### Clash Nyanpasu 版本号 / Clash Nyanpasu

Clash Nyanpasu Nightly Build

### Clash 核心及其版本号 / Clash core and version

1.18.4

### 是否为 Pre-release / Is pre-release version

beta版

### 操作系统及版本 / OS version

win11 23H2，mac14.5

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
fixed https://github.com/LibNyanpasu/clash-nyanpasu/commit/21f86f690c0afc6aa2db68875c095ef6e3a42941

**Comment by ericclose** [comment]
> fixed [21f86f6](https://github.com/LibNyanpasu/clash-nyanpasu/commit/21f86f690c0afc6aa2db68875c095ef6e3a42941)

I can confirm that it's **not fixed** even in [4273056](https://github.com/LibNyanpasu/clash-nyanpasu/commit/427305679989c3e51b2c120f6bf2feb4eb3424de)

**Comment by chen-jingliang** [comment]
涛声依旧，怎么说解决了呢？当切换到全局，根本无法选择节点。我已经升级到最新的DEV版本。

**Comment by Minonyah** [comment]
> > 声依旧，什么问题解决了呢？当切换到全局时，根本无法选择节点。我已经升级到最新的DEV版本。
> 
> 请尝试一下完全卸载旧版，清除以前的数据，重新安装最新版本

我在v1.5.2-alpha+09dcc6a中仍然遇到这个问题，这是我第一次安装Clash.Nyanpasu

**Comment by ericclose** [comment]
测试 [2835ea4](https://github.com/LibNyanpasu/clash-nyanpasu/commit/b802f3fc535b67c99b70ab05067047d53b725e10) 版本，目前已修复这个问题
