### ISSUE TITLE
从URL Scheme导入的订阅没有任何反应

### ISSUE THREAD

**Issue by SummonHIM** [LibNyanpasu/clash-nyanpasu#902]
### 复现步骤 / Step to reproduce

1. 从浏览器访问 clash-nyanpasu://subscribe-remote-profile?url={URLEncode之后的链接}&name={URLEncode之后的名称}。浏览器会正常提示是否打开Nyaapasu。
2. 点击后，Nyaapasu并没有做出任何反应，日志也没有任何信息。

### 预期行为 / Expected behaviour

应该正常导入url为url={URLEncode之后的链接}的订阅

### 实际行为 / Actual Behaviour

点击后，Nyaapasu并没有做出任何反应，日志也没有任何信息。

### 应用日志 / App logs

https://gist.github.com/SummonHIM/e355be83a0b93f2d432973eb7de8946e

### 备注 / Addition details

我首先打开的是Portable版本，然后我再回到1.5.1正式版进行测试。不知道是否Portable版本已经占用了URLScheme注册表。导致1.5.1检测到已存在的URLScheme注册表而跳过重新注册。

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1 & 1.5.2-alpha+67e34fd_x64_portable

### Clash 核心及其版本号 / Clash core and version

v1.18.4

### 是否为 Pre-release / Is pre-release version

67e34fd

### 操作系统及版本 / OS version

Windows 11 10.0.22631.3527

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by 4o3F** [comment]
唤起问题于bda1dc086c381c1bbba757cd388acf7c6e5642b8修复，前端窗口跳出问题等待修复

**Comment by greenhat616** [comment]
最新开发版已经修复：https://github.com/LibNyanpasu/clash-nyanpasu/commit/c9ddbfb69e25506cb07e021dbca7c9bc6553f811
![图片](https://github.com/user-attachments/assets/03a9a7bd-c4f2-45f9-90c8-63b1e4414a76)

**Comment by SummonHIM** [comment]
> 最新开发版已经修复：[c9ddbfb](https://github.com/LibNyanpasu/clash-nyanpasu/commit/c9ddbfb69e25506cb07e021dbca7c9bc6553f811) 而且已经兼容了 `clash://` 协议，但是会抢占其他软件注册的协议
> 
> ![图片](https://private-user-images.githubusercontent.com/41122242/354959505-03a9a7bd-c4f2-45f9-90c8-63b1e4414a76.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI4MjgyNzcsIm5iZiI6MTcyMjgyNzk3NywicGF0aCI6Ii80MTEyMjI0Mi8zNTQ5NTk1MDUtMDNhOWE3YmQtYzRmMi00NWY5LTkwYzgtNjNiMWU0NDE0YTc2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA1VDAzMTkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxZjNjN2FhY2U0MWFkMDc5NGI0YThjYmU4M2EwNDFlYzM3N2I0MWY4NGY2YzBkMGFhYmQ0Y2I4Y2I1NzEwMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zPB56ndNeqFlCgduCy4o_O9LyBEq_N89G_UGRHSGP9I)

其他软件其实也是一样启动时抢占的。应该算正常
