### ISSUE TITLE
Nyanpasu 1.6.0(1.5.2) 体验须知

### ISSUE THREAD

**Issue by keiko233** [LibNyanpasu/clash-nyanpasu#903]
### 公告/ Notice

Clash Nyanpasu 1.6.0 正在积极开发中，由于涉及到大量的代码重构，届时 dev 版可能会出现非常多奇奇怪怪的问题，以及功能缺失，欢迎大家反馈。

> 目前预计发布时间为**六月**，希望体验的童鞋请注意：
> **开发版本可能会造成配置数据丢失，部分配置需要重新配置。需要有一定动手能力，升级前一定要备份配置。**
> 我们会尽力在 stable 前做好迁移脚本，但并不保证一定能涵盖所有的边界情况。为了减少迁移失败的情况，欢迎大家踊跃测试并提交 issue。

#### 页面
- [x] Settings
- [x] Proxies
- [x] Profiles
- [x] Conntections
- [x] Rules
- [x] Logs
- [x] Provides
- [x] Dashboard(new page) - Ongoing

#### 细节
- [x] 侧边栏优化 - Ongoing

### 后端

新功能点:
- [x] 改進内核更新體驗（進行中）
  - [x] 提供實時速度、下載進度（大小）等相關信息 
  - [x] 使用多綫程進行下載
  - [x] 下載前自動選擇延遲最低的 Mirror 
- [x] 基于 Profile 的代理链支持
- [x] Lua 脚本支持
- [x] JavaScript 脚本 esm 支持 - https://github.com/LibNyanpasu/clash-nyanpasu/pull/973 https://github.com/LibNyanpasu/clash-nyanpasu/pull/1266
- [x] JavaScript 脚本 async 支持 - https://github.com/LibNyanpasu/clash-nyanpasu/pull/973 https://github.com/LibNyanpasu/clash-nyanpasu/pull/1266
- [ ] ~~JavaScript 脚本 fetch(get)支持~~ 移动到 v1.6.1
- [x] 跨平台服务模式 - https://github.com/LibNyanpasu/nyanpasu-service/releases/tag/v1.0.0
- [x] 改进 Merge 处理，支持递归合并处理，支持双向添加列表特性
 - [x] 考虑中的：添加表达式支持 

已经完成重构的部分可能存在大量的bug（因为开发组并没有完整的 UAT 测试流程，业余开发无太多精力），需要借助大家的力量一起来测试完善新代码。

可能会出现的问题:
- 没有做平台功能、UI上的区分
- 新UI修改设置旧UI不生效／新UI部分设置不能立即生效

这些问题会在日后慢慢提交commit修复，大家不必担心，希望大家耐心等待！

重构完成后为保证最终的质量，我们仍然需要一些时间进行代码的清理，这将可能需要一些时间。

**Comment by Rakau** [comment]
服务模式开关失效
