### ISSUE TITLE
无法切换为.yaml格式的在线订阅地址

### ISSUE THREAD

**Issue by chen-jingliang** [LibNyanpasu/clash-nyanpasu#915]
### 复现步骤 / Step to reproduce

1. 点击左侧配置按钮
2. 右侧无法切换为.yaml格式结尾的订阅地址

### 预期行为 / Expected behaviour

可以自由切换clash meta支持的订阅地址

### 实际行为 / Actual Behaviour

<img width="801" alt="SCR-20240515-stwf" src="https://github.com/LibNyanpasu/clash-nyanpasu/assets/28627641/9417cba6-fa97-41ee-b586-96fa79fe01fc">

### 备注 / Addition details

记得以前是可以切换为.yaml订阅地址的，现在1.5.1正式版和DEV版都不可以切换。
订阅地址为github分享地址：https://github.com/Misaka-blog/chromego_merge

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1正式版和DEV版

### Clash 核心及其版本号 / Clash core and version

1.18.3和1.18.4

### 是否为 Pre-release / Is pre-release version

正式版和beta版

### 操作系统及版本 / OS version

win11 23H2，mac14.5

### 自查步骤 / Verify steps

- [X] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
经过测试是可以使用的，请检查下自己操作的问题，例如网络不稳定等因素
