### ISSUE TITLE
install on ubuntu 24.04 failed

### ISSUE THREAD

**Issue by huoyushequ** [LibNyanpasu/clash-nyanpasu#940]
### 复现步骤 / Step to reproduce

sudo dpkg -i Downloads/clash-nyanpasu_1.5.1_amd64.deb 
[sudo] password for wesx: 
Selecting previously unselected package clash-nyanpasu.
(Reading database ... 151777 files and directories currently installed.)
Preparing to unpack .../clash-nyanpasu_1.5.1_amd64.deb ...
Unpacking clash-nyanpasu (1.5.1) ...
dpkg: dependency problems prevent configuration of clash-nyanpasu:
 clash-nyanpasu depends on libwebkit2gtk-4.0-37; however:
  Package libwebkit2gtk-4.0-37 is not installed.

dpkg: error processing package clash-nyanpasu (--install):
 dependency problems - leaving unconfigured
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1.1ubuntu3) ...
Processing triggers for desktop-file-utils (0.27-2build1) ...
Errors were encountered while processing:
 clash-nyanpasu

### 预期行为 / Expected behaviour

It should be installed successfully

### 实际行为 / Actual Behaviour

dpkg: dependency problems prevent configuration of clash-nyanpasu:
 clash-nyanpasu depends on libwebkit2gtk-4.0-37; however:
  Package libwebkit2gtk-4.0-37 is not installed.

### 应用日志 / App logs

ll /usr/lib/x86_64-linux-gnu/libwebkit2gtk*
libwebkit2gtk-4.1.so.0       libwebkit2gtk-4.1.so.0.13.4 

### 备注 / Addition details

on ubuntu 24.04, libwebkit2gtk has updated to 4.1 version, but nyanpasu still depend the old version

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### Clash 核心及其版本号 / Clash core and version

v1.18.1

### 是否为 Pre-release / Is pre-release version

no

### 操作系统及版本 / OS version

Ubuntu 24.04

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
**Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs**

duplicate https://github.com/LibNyanpasu/clash-nyanpasu/issues/829
