### ISSUE TITLE
操作的卡顿感很明显

### ISSUE THREAD

**Issue by chensimmons** [LibNyanpasu/clash-nyanpasu#941]
### 复现步骤 / Step to reproduce

clash 1.5.1，
在系统托盘里右键操作关闭/切换系统代理、tun模式时，总是要卡几十秒才能关闭或切换成功，还有退出程序时，也是要卡几十秒才能退出成功。
另外今天下载的每日构建版本，配置页面根本无法点击配置文件，左键右键都不行。

作为对比，隔壁的clash verge rev倒是切换得很快，一点击切换就能看到代理状态颜色上的改变

### 预期行为 / Expected behaviour

应该快速切换

### 实际行为 / Actual Behaviour

卡顿的感觉明显

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### Clash 核心及其版本号 / Clash core and version

1.18.1 meta

### 是否为 Pre-release / Is pre-release version

包括每日构建版本

### 操作系统及版本 / OS version

Windows 10专业版

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
1. 喵帕斯切换代理是通过syscall来调用，如果系统内有杀毒软件/不规范软件可能会导致被拦截，导致失败/时间长；
2. 退出卡顿大概率也是卡在cleanup；
3. 直接修改注册表固然快，但是是不推荐做法，不作详细解释；
4. 由于每日构建直接在主分支上，此次版本要做大量升级，主分支有很多未完成代码，目前每日构建的可用性不做保证；
5. **您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue**
