### ISSUE TITLE
1.5.0版本Win10下彻底无法启动，显示一个报错信息，随后闪退 

### ISSUE THREAD

**Issue by user-pc3kvn1850** [LibNyanpasu/clash-nyanpasu#942]
### 复现步骤 / Step to reproduce

之前一直可以正常使用，最近安装了一个cfosspeed，这个软件安装过程中好像会安装webview2，装完后最近clash nyanpasu变得无法启动，一启动就弹出这个报错画面，然后就闪退了，系统托盘里无clash nyanpasu图标。现在无论exe安装版还是便携版，都彻底无法使用clash nyanpasu了，求帮助。已卸载clash nyanpasu多次，重新安装也无法解决。

![clash nyanpasu crash](https://github.com/LibNyanpasu/clash-nyanpasu/assets/1773534/295674c3-c792-48ef-8ebb-a70d05127bc2)

### 预期行为 / Expected behaviour

双击Clash Nyanpasu.exe，应该正常启动

### 实际行为 / Actual Behaviour

双击Clash Nyanpasu.exe，显示报错信息，闪退，无法启动，无法使用。

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.0

### Clash 核心及其版本号 / Clash core and version

v1.81.1 meta

### 是否为 Pre-release / Is pre-release version

否

### 操作系统及版本 / OS version

Windows 10 x64

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/issues/307
