### ISSUE TITLE
Linux mint latest update broke the app

### ISSUE THREAD

**Issue by bryanray** [libnyanpasu/clash-nyanpasu#954]
### 复现步骤 / Step to reproduce

![176fc18e80c656892cec07a69636e74f](https://github.com/LibNyanpasu/clash-nyanpasu/assets/1768531/125f211e-b15e-4689-a093-ad01fa7bd992)

### 预期行为 / Expected behaviour

used to work fine

### 实际行为 / Actual Behaviour

Now its broken 

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.1

### Clash 核心及其版本号 / Clash core and version

No

### 是否为 Pre-release / Is pre-release version

No

### 操作系统及版本 / OS version

Linux mint

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
Please check if nyanpasu already exists in your process.

and need more logs or environment info

**Comment by greenhat616** [comment]
Let me jump in. Did you use Nyanpasu via AppImage? It seems a permission issue, although it show  a single instance check problem, while you are launching the app via AppImage.

**Comment by bryanray** [comment]
> Please check if nyanpasu already exists in your process.
> 
> and need more logs or environment info

I am a noob linux user please elaborate how to get more info via console, thanks :)

**Comment by bryanray** [comment]
> Let me jump in. Did you use Nyanpasu via AppImage? It seems a permission issue, although it show a single instance check problem, while you are launching the app via AppImage.

Yea AppImage, it works fine before the update, I also try the other format but the same error message.
It does not ask me for permission though.

additional info:
before the update,
nyanpasu has not imported any profile.
I do tick nyanpasu's "start with system" and maybe "system proxy" too.

**Comment by greenhat616** [comment]
Okay, thanks for you added information. I am on business trip, and the desktop was shutdown  by mistake. So it probably could not get reproduction these days.

CC @4o3F, could you have a look if  you are not busy?

**Comment by bryanray** [comment]
> Please check if nyanpasu already exists in your process.
> 
> and need more logs or environment info

yes there is a process and I've ended it, and restart it, also I have deactivate the autostart of nyanpasu in the panel of linux mint.

but still not working as it was, please help.

**Comment by Fros1er** [comment]
Maybe you can try `lsof -U | grep clash` to find whether there is remaining process of the app. I triggered the same bug after change the system name of my computer, and need to manually kill the process to make it work.

**Comment by greenhat616** [comment]
It should be solved by v1.6.0
