### ISSUE TITLE
Latest Nightly [May 25 2024] UI shows error

### ISSUE THREAD

**Issue by NalCol** [LibNyanpasu/clash-nyanpasu#969]
### 复现步骤 / Step to reproduce

Download the Nightly -> Sat May 25 09:30:45 CST 2024.
Launch it.

### 预期行为 / Expected behaviour

It should work.

### 实际行为 / Actual Behaviour

![image](https://github.com/LibNyanpasu/clash-nyanpasu/assets/58576200/9c903c99-ccbd-4ad5-ba34-3ba032788824)

### 应用日志 / App logs

https://hastebin.com/share/tugosoyaka.swift

### Clash Nyanpasu 版本号 / Clash Nyanpasu

Nightly Release created at Sat May 25 09:30:45 CST 2024.

### Clash 核心及其版本号 / Clash core and version

v1.18.5

### 是否为 Pre-release / Is pre-release version

b4c90e9

### 操作系统及版本 / OS version

Windows 11 22H2 Beta

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by greenhat616** [comment]
尝试删除下配置目录的 `verge.yml` 一下

**Comment by keiko233** [comment]
最新pre release测试已经可用

**Comment by NalCol** [comment]
> 尝试删除下配置目录的 `verge.yml` 一下

有用，可能是新版不兼容旧版的配置
btw新版界面很好看🥵

**Comment by NalCol** [comment]
> 最新pre release测试已经可用

最新pre release仍然需要删除verge.yml
