### ISSUE TITLE
[BUG] 图标位置错误，出现重合

### ISSUE THREAD

**Issue by chen-jingliang** [LibNyanpasu/clash-nyanpasu#97]
**Describe the bug**
图标位置错误，出现重叠。

**To Reproduce**
1. 点开软件后
2. 菜单栏最左侧就会出现图标重叠

**Screenshots**
![SCR-20231210-mbuk](https://github.com/keiko233/clash-nyanpasu/assets/28627641/74ebec30-dc0b-4dbe-87f9-0404314a3d69)

**Information**
- OS: [macOS 14.1.1]
- Clash Nyanpasu Version: [1.4.1]
- Clash Core: [Clash Meta]

**Additional context**
此MAC系统为通过OCLP升级的系统。

**Comment by greenhat616** [comment]
与 https://github.com/keiko233/clash-nyanpasu/issues/62 重复，请等待修复

**Comment by chen-jingliang** [comment]
我按照#62的方法进行了测试，所有选项均测试了一遍，图标依然会重合。目前系统已经升级到了14.3，情况依旧。需要说明的是我家里的MAC电脑也是14.3没有这个问题，而我工作室的这个电脑是通过OCLP升级到14.3（也就是老MAC不支持直接升级到最新系统，需要通过OCLP才能升级）。但是其他软件没有出现这个问题，希望解决。

**Comment by greenhat616** [comment]
tauri 上游的 bug，我们无能为力。只能等上游修复了。








 ----------回复的邮件信息----------
 ***@***.***&gt; 于2024年1月29日(周一) 上午8:32写道:

  

 
我按照#62的方法进行了测试，所有选项均测试了一遍，图标依然会重合。目前系统已经升级到了14.3，情况依旧。需要说明的是我家里的MAC电脑也是14.3没有这个问题，而我工作室的这个电脑是通过OCLP升级到14.3（也就是老MAC不支持直接升级到最新系统，需要通过OCLP才能升级）。但是其他软件没有出现这个问题，希望解决。

**Comment by PelikanM400** [comment]
> tauri 上游的 bug，我们无能为力。只能等上游修复了。
> […](#)
> ----------回复的邮件信息---------- ***@***.***&gt; 于2024年1月29日(周一) 上午8:32写道: 我按照#62的方法进行了测试，所有选项均测试了一遍，图标依然会重合。目前系统已经升级到了14.3，情况依旧。需要说明的是我家里的MAC电脑也是14.3没有这个问题，而我工作室的这个电脑是通过OCLP升级到14.3（也就是老MAC不支持直接升级到最新系统，需要通过OCLP才能升级）。但是其他软件没有出现这个问题，希望解决。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

同样遇到这个问题，等待修复🙏

**Comment by db131** [comment]
使用以下命令，重置 Dock 并重新启动（macos14.3）
defaults delete com.apple.dock; killall Dock

**Comment by 4o3F** [comment]
Duplicate issue, this issue will be tracked in #62
