### ISSUE TITLE
Windows Server 系统下，打开设置报错

### ISSUE THREAD

**Issue by sulele89757** [LibNyanpasu/clash-nyanpasu#981]
### 复现步骤 / Step to reproduce

由于一些原因必须使用Windows Server作为主力，从电报群下载安装Clash.Nyanpasu_1.5.2_x64-setup.exe后，打开设置页签时，报错如图。
![GIF 2024-5-28 15-42-00](https://github.com/LibNyanpasu/clash-nyanpasu/assets/11418032/ad5f2153-8485-4f90-9b8f-3afb77a616bc)

### 预期行为 / Expected behaviour

正常打开设置页签

### 实际行为 / Actual Behaviour

尝试过卸载后重新安装，依然报错
![GIF 2024-5-28 15-42-00](https://github.com/LibNyanpasu/clash-nyanpasu/assets/11418032/60c090ab-34a0-4b7d-b280-735a3819c157)

### Clash Nyanpasu 版本号 / Clash Nyanpasu

1.5.2

### Clash 核心及其版本号 / Clash core and version

v1.18.4 Meta

### 是否为 Pre-release / Is pre-release version

No

### 操作系统及版本 / OS version

Windows Server 2022 Standard 21H2 20348.2461

### 自查步骤 / Verify steps

- [ ] 如果您有足够的时间和能力，并愿意为此提交 PR ，请勾上此复选框 / Pull request is welcome. Check this if you want to start a pull request
- [X] 您已知悉如果没有提供正确的系统信息，以及日记，您的 Issue 会直接被关闭 / You have known that if you don't provide correct system information and logs, your issue will be closed directly
- [X] 您已仔细查看并知情 [Q&A](https://nyanpasu.elaina.moe/zh-CN/others/issues.html) 和 [FAQ](https://nyanpasu.elaina.moe/zh-CN/others/faq.html) 中的内容 / You have read and understood the contents of [Q&A](https://nyanpasu.elaina.moe/others/issues.html) and [FAQ](https://nyanpasu.elaina.moe/others/faq.html).
- [X] 您已搜索过 [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues)，没有找到类似内容 / I have searched on [Issue Tracker](https://github.com/keiko233/clash-nyanpasu/issues), No duplicate or related open issue has been found
- [X] 您确保这个 Issue 只提及一个问题。如果您有多个问题报告，烦请发起多个 Issue / Ensure there is only one bug report in this issue. Please make mutiply issue for mutiply bugs
- [X] 您确保已使用最新 Pre-release 版本测试，并且该问题在最新 Pre-release 版本中并未解决 / This bug have not solved in latest Pre-release version

**Comment by keiko233** [comment]
https://github.com/LibNyanpasu/clash-nyanpasu/issues/831#issuecomment-2081290706

先参考这条进行修复，正式版会提交commit做其他修复
