### ISSUE TITLE
[BUG]Windows任务栏的图标显示有锯齿

### ISSUE THREAD

**Issue by lainbo** [LibNyanpasu/clash-nyanpasu#99]
**Describe the bug**
在Windows的任务栏中，图标锯齿感明显，是故意为之的像素风格吗?

**To Reproduce**
1. 在Windows系统下打开软件

**Expected behavior**
期望有一个平滑清晰的图标

**Screenshots**
![image](https://github.com/keiko233/clash-nyanpasu/assets/46062895/66a600ff-a631-4117-ab1a-8fe7a8666397)
![image](https://github.com/keiko233/clash-nyanpasu/assets/46062895/6606abd2-9e34-4d4a-acfc-378b870837ac)

**Information**

- OS: Windows11 23H2
- Clash Nyanpasu Version: 1.4.1
- Clash Core: Clash Meta

**Additional context**
null

**Comment by greenhat616** [comment]
是开发版吗

**Comment by greenhat616** [comment]
可以试一下开发版。如果还是这样的话，那就是就是你屏幕的 DPI 太低了。等 @keiko233 以后绘制的超低 DPI 下的 icon 吧。
![image](https://github.com/keiko233/clash-nyanpasu/assets/41122242/33770c07-6c30-4f4d-badf-f4da642371d3)

**Comment by lainbo** [comment]
上面的图是1.4.1稳定版，屏幕是1920×1080的24寸屏幕，虽说dpi不高但确实是主流办公显示器尺寸
---
下面的图是1.4.1开发版，屏幕是3840×2160的27寸屏幕，也存在一些毛刺边缘
![image](https://github.com/keiko233/clash-nyanpasu/assets/46062895/5e343d76-2ce9-4fb1-9be0-586f2a8f88d8)

**Comment by keiko233** [comment]
> 可以试一下开发版。如果还是这样的话，那就是就是你屏幕的 DPI 太低了（windows 缩小分辨率后，并没有做平滑处理）。等 @keiko233 以后绘制的超低 DPI 下的 icon 吧。 ![image](https://private-user-images.githubusercontent.com/41122242/289471535-33770c07-6c30-4f4d-badf-f4da642371d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDU2NzMsIm5iZiI6MTcwMjM0NTM3MywicGF0aCI6Ii80MTEyMjI0Mi8yODk0NzE1MzUtMzM3NzBjMDctNmMzMC00ZjRkLWJhZGYtZjRkYTY0MjM3MWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAxNDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMTlmYThkNmU1YzRkZjg1ODMxMTAzNDNlNGZhNDVjN2MwYTgxMTk2NDNjMDdiZGE5NTMwNzRmOWJhZDU1ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FoMb61n6uLdrVAC957d8pejq6R59d12VUhV9ALvql2o)

图标有描边，低dpi不能很好的处理这种情况，解决方案待定

**Comment by lainbo** [comment]
> > 可以试一下开发版。如果还是这样的话，那就是就是你屏幕的 DPI 太低了（windows 缩小分辨率后，并没有做平滑处理）。等 @keiko233 以后绘制的超低 DPI 下的 icon 吧。 ![image](https://private-user-images.githubusercontent.com/41122242/289471535-33770c07-6c30-4f4d-badf-f4da642371d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDU2NzMsIm5iZiI6MTcwMjM0NTM3MywicGF0aCI6Ii80MTEyMjI0Mi8yODk0NzE1MzUtMzM3NzBjMDctNmMzMC00ZjRkLWJhZGYtZjRkYTY0MjM3MWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAxNDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMTlmYThkNmU1YzRkZjg1ODMxMTAzNDNlNGZhNDVjN2MwYTgxMTk2NDNjMDdiZGE5NTMwNzRmOWJhZDU1ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FoMb61n6uLdrVAC957d8pejq6R59d12VUhV9ALvql2o)
> 
> 图标有描边，低dpi不能很好的处理这种情况，解决方案待定

- 在windows下，不同的缩放档位，对应了不同的dpi
100%是96dpi，125%是120dpi，150%是144dpi，175%是168dpi，200%是192dpi
- 我的第二块显示器是3840×2160的27寸，开的175%缩放
- 根据上述数据，96×1.75/163 = 1.03，也就是175%缩放的dpi除以屏幕的像素密度(ppi)等于1.03近似于1，是一个比较合理的值。可能除了一些极其高端的台式设备和笔记本电脑(因为屏幕小所以参数会很高)，第二块显示器不能算低dpi设备，甚至在民用台式显示器里算中上了。但是看上去小猫像是炸了毛一样😂

如果你提到的描边问题是svg相关的话，我可以提供一张重绘了的svg，没有使用描边，不知道对这个问题的解决是否有帮助

再次感谢大佬的付出
![clash-nyanpasu-logo](https://github.com/keiko233/clash-nyanpasu/assets/46062895/c2e84fd3-c44e-4a0f-8250-cc73984e83db)

**Comment by keiko233** [comment]
> > > 可以试一下开发版。如果还是这样的话，那就是就是你屏幕的 DPI 太低了（windows 缩小分辨率后，并没有做平滑处理）。等 @keiko233 以后绘制的超低 DPI 下的 icon 吧。 ![image](https://private-user-images.githubusercontent.com/41122242/289471535-33770c07-6c30-4f4d-badf-f4da642371d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzNDU2NzMsIm5iZiI6MTcwMjM0NTM3MywicGF0aCI6Ii80MTEyMjI0Mi8yODk0NzE1MzUtMzM3NzBjMDctNmMzMC00ZjRkLWJhZGYtZjRkYTY0MjM3MWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDAxNDI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzMTlmYThkNmU1YzRkZjg1ODMxMTAzNDNlNGZhNDVjN2MwYTgxMTk2NDNjMDdiZGE5NTMwNzRmOWJhZDU1ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FoMb61n6uLdrVAC957d8pejq6R59d12VUhV9ALvql2o)
> > 
> > 
> > 图标有描边，低dpi不能很好的处理这种情况，解决方案待定
> 
> * 在windows下，不同的缩放档位，对应了不同的dpi
>   100%是96dpi，125%是120dpi，150%是144dpi，175%是168dpi，200%是192dpi
> * 我的第二块显示器是3840×2160的27寸，开的175%缩放
> * 根据上述数据，96×1.75/163 = 1.03，也就是175%缩放的dpi除以屏幕的像素密度(ppi)等于1.03近似于1，是一个比较合理的值。可能除了一些极其高端的台式设备和笔记本电脑(因为屏幕小所以参数会很高)，第二块显示器不能算低dpi设备，甚至在民用台式显示器里算中上了。但是看上去小猫像是炸了毛一样😂
> 
> 如果你提到的描边问题是svg相关的话，我可以提供一张重绘了的svg，没有使用描边，不知道对这个问题的解决是否有帮助
> 
> 再次感谢大佬的付出 ![clash-nyanpasu-logo](https://private-user-images.githubusercontent.com/46062895/289734970-c2e84fd3-c44e-4a0f-8250-cc73984e83db.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI0NTA4NjAsIm5iZiI6MTcwMjQ1MDU2MCwicGF0aCI6Ii80NjA2Mjg5NS8yODk3MzQ5NzAtYzJlODRmZDMtYzQ0ZS00YTBmLTgyNTAtY2M3Mzk4NGU4M2RiLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEzVDA2NTYwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM3N2Q2N2EzOWQ0MDg5NTIwOWUzZjg5ZjBmZDkwOTRmNGIwY2U2OGIzZjVjMjA0N2VjNmM1YTU4MjExZGEwOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7ZCIMr56bTqE2YJhhaLuHeHUzSEVQh6JRHIeX7PKPTU)

我这边有时间看看，如果你这边有空的话可以尝试修改这里的图标本地测试试试😂

https://github.com/keiko233/clash-nyanpasu/tree/dev/backend/tauri/icons

**Comment by greenhat616** [comment]
![image](https://github.com/keiko233/clash-nyanpasu/assets/41122242/f778cef6-7cdf-4108-a226-119fb343b622)
看起来确实嘴巴能看了 😄
